- dockerfiles/remote-plugin-runner-java/Dockerfile
- dockerfiles/remote-plugin-runner-java8/Dockerfile
Add Dockerfile for an image that can run Theia plugin runner sidecar that depends on Java 8
> Add Theia remote plugin runner with Java 8 runtime

- .gitignore
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-client.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-backend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts
- extensions/eclipse-che-theia-plugin-ext/yarn.lock
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
fixes https://github.com/eclipse/che/issues/11954
> CHE-11954: Add che.registerTaskRunner Theia Plugin API

- dockerfiles/theia/build.sh
Just as it is done for docker images.
> Only push CDN files on cron-triggered CI builds

- dockerfiles/theia/src/entrypoint.sh
This PR fixes syntax error in bash script which is responsible for Theia start.
> Fix syntax error in Theia entrypoint.sh script

- .travis.yml
- build_and_push_docker_images.sh
- dockerfiles/build.include
- dockerfiles/theia-dev/e2e/Dockerfile
- dockerfiles/theia/Dockerfile
- dockerfiles/theia/build.sh
- dockerfiles/theia/e2e/Dockerfile
- dockerfiles/theia/e2e/build.sh
- dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
- extensions/extensions.yml
Should fix #39
Also include build `che-theia-master` image from Theia and all extensions master branch.
Removes `che-theia-ssh-extension` and `github-extension` which is deprecated and no longer supported(there https://github.com/eclipse/che-theia/pull/31 pull which add ssh as plugin)
> Update to Theia 0.3.19, build another image from upstream

- README.md
- build_and_push_docker_images.sh
- extensions/extensions.yml
Set 'che-theia' extension to stable version branch
For #39
>  Fix extension branch

- dockerfiles/remote-plugin-runner-java8/Dockerfile
This PR changes base image of remote-plugin-runner-java8 because https://github.com/ws-skeleton/che-theia-remote-extension was moved into `che-theia`.
> Change base image of remote-plugin-runner-java8 image

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia-endpoint-runtime/Dockerfile
- dockerfiles/theia/Dockerfile
8.12.0 version was using yarn 1.9.4 and it doesn't work for building che-theia
Change-Id: I4c7e3c2059c5641aa8ce8ba8176a1687d395e879
> Update nodejs to 8.15.0 which is using a newer version of yarn

- extensions/eclipse-che-theia-user-preferences/.gitignore
- extensions/eclipse-che-theia-user-preferences/package.json
- extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-contribution.ts
- extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts
- extensions/eclipse-che-theia-user-preferences/src/node/che-theia-user-preferences-backend-module.ts
- extensions/eclipse-che-theia-user-preferences/tsconfig.json
- extensions/extensions.yml
- yarn.lock
Theia user preferences synchronizer is designed to handle Theia user settings synchronization between workspaces. It retrieves Theia user preferences from Che user preferences on Theia server start and watches changes, so when any update is done it will be reflected back to Che storage.
Depends on [Preferences API PR](https://github.com/eclipse/che-theia/pull/79)
> Add Theia user preferences synchronizer

- extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts
At [creating Che Tasks](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts#L45) we do not add context, so task manager [register](https://github.com/theia-ide/theia/blob/master/packages/task/src/node/task-manager.ts#L40) tasks without context.
But context is passed when we tried to get Che tasks by [taskManager.getTasks()](https://github.com/theia-ide/theia/blob/master/packages/task/src/node/task-manager.ts#L62) and we get no tasks for this case.
So we need to specify context at creating Che tasks.
Fixes: https://github.com/eclipse/che-theia/issues/76
> Add context at creating Che tasks

- extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts
This PR brings fix for https://github.com/eclipse/che-theia/pull/80.
It handles the situation when Theia user directory hasn't been created yet, but the `eclipse-che-theia-user-preferences` extension tries to create the settings.json file.
> Create Theia config directory if it doesn't exist

- dockerfiles/remote-plugin-runner-java8/Dockerfile
Current `ps` utility isn't full, it is a [BusyBox command](https://busybox.net/downloads/BusyBox.html#ps).
[Java Language Server](https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java#L66) checks if the process is alive by executing `ps -p [PID]`, but `-p` is unknown parameter for current version of `procps`.
This PR adds full `procps` into the `eclipse/che-remote-plugin-runner-java8` image.
> Install procps into java8 image

- dockerfiles/theia-endpoint-runtime/src/node/hosted-plugin-remote.ts
- dockerfiles/theia-endpoint-runtime/src/node/plugin-remote.ts
it will avoid to define mapping between a plugin id and remote endpoint on main theia instance
Change-Id: Ib3b6b9de2693f41850d1f92692b7ecc4e209e223
> avoid to declare plugin-id on main theia instance process

- dockerfiles/remote-plugin-go-1.10.7/Dockerfile
In OpenShift `anyuid` is off, as a result a user in a container does not have write permissions to some directories. This PR sets permissions for user to get access to `.cache` folder which is used by GO plugin.
> Set permissions for .cache folder

- dockerfiles/theia/Dockerfile
It is a proposal, WDYT ?
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
> Build che-theia plugins from che-theia-dev builder container rather than getting it from released travis built

- plugins/factory-plugin/src/ephemeral-workspace-checker.ts
- plugins/factory-plugin/src/factory-plugin.ts
- plugins/factory-plugin/src/workspace-manager.ts
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>
Show warning to user in Che Theia status bar - "Ephemeral mode" and tooltip "All changes to the source code will be lost when the workspace is stopped unless they are pushed to a source code repository."
Issue - https://github.com/eclipse/che/issues/12565
_A note: background of status bar item cannot be set by plugin API, thus only font color._
> Show status bar message if workspace is in ephemeral mode

- dockerfiles/theia/Dockerfile
Maybe this will fix the issue where extensions folder built
Have that on travis
> The job exceeded the maximum time limit for jobs, and has been terminated.
> Fix too long build, build only plugins folders for plugins

- plugins/factory-plugin/src/ephemeral-workspace-checker.ts
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>
Reverse logic on how ephemeral mode is detected.
**Ephemeral mode** : property `persistVolumes` exists and is `false`
**Not Ephemeral mode**: no property `persistVolumes` or `persistVolumes` is `true`
> Reverse logic on ephemeral mode detecting

- build_and_push_docker_images.sh
- dockerfiles/remote-plugin-openshift-connector-0.0.17/Dockerfile
- dockerfiles/remote-plugin-openshift-connector-0.0.17/build.sh
The PR adds Dockerfile to build an image for the [OpenShift Connector Che Plugin](https://github.com/eclipse/che-plugin-registry/pull/104).
The related issue https://github.com/eclipse/che/issues/11488
> Add Dockerfile to build an image for the OpenShift Connector Che Plugin

- dockerfiles/theia-endpoint-runtime/src/node/hosted-plugin-remote.ts
- dockerfiles/theia-endpoint-runtime/src/node/plugin-remote-backend-module.ts
- dockerfiles/theia-endpoint-runtime/src/node/plugin-remote-init.ts
- dockerfiles/theia-endpoint-runtime/src/node/server-plugin-proxy-runner.ts
- dockerfiles/theia-endpoint-runtime/src/node/websocket.ts
- dockerfiles/theia-endpoint-runtime/yarn.lock
- package.json
- yarn.lock
Also require to merge first https://github.com/theia-ide/theia/pull/4562
Should fix also the sidecar reloading issue https://github.com/theia-ide/theia/issues/3970
in improvements, manage clearly reloading of plug-ins from sidecar and ensure plug-ins are correctly stopped.
> Handle the changes introduced by upstream theia with allowing multiple clients on plug-ins

- build_and_push_docker_images.sh
Now all Docker images from `master` branch will be published with `next` tag
For: #63 
> Publish all images with :next tag

- dockerfiles/remote-plugin-runner-java8/Dockerfile
When playing with this image I got the following issue
<details>
<summary>Click to see the stack</summary>
<br>
Exception stack
<br><br>
<pre>
Exception in thread "main" java.lang.ExceptionInInitializerError
at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:188)
at sun.security.ssl.SSLSessionImpl.<init>(SSLSessionImpl.java:152)
at sun.security.ssl.SSLSessionImpl.<clinit>(SSLSessionImpl.java:79)
at sun.security.ssl.SSLSocketImpl.init(SSLSocketImpl.java:598)
at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:566)
at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:110)
at org.apache.maven.wagon.providers.http.httpclient.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:365)
at …
> [docker] [java] Add nss library

- extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts
Existing solution, which depends on user ''che", doesn't work with che-multiuser.
In this PR regexp and replacement were fixed.
> Fix the workspace URL for UD

- build_and_push_docker_images.sh
- dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
- dockerfiles/remote-plugin-dotnet-2.2.105/build.sh
Provides a dockerfile to build an image which will make it possible to run OmniSharp-Roslyn as a C# language support. 
It is need for https://github.com/eclipse/che/issues/12792
> Add Dockerfile to build an image with .Net Core SDK

- plugins/containers-plugin/package.json
- plugins/containers-plugin/resources/cube.svg
Recent changes in Theia requires to provide an icon for `viewContainer`, so this pull add icon for containers plugin. Icon copied from [there ](https://github.com/eclipse/che/blob/master/ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/machine/cube.svg)
> Add icon for 'Containers' view container

- che-plugins/che-editor-theia/etc/che-plugin.yaml
- dockerfiles/theia/Dockerfile
- plugins/ports-plugin/src/port-redirect-listener.ts
- plugins/ports-plugin/src/ports-plugin.ts
- plugins/ports-plugin/src/workspace-handler.ts
- plugins/ports-plugin/tests/workspace-handler/workspace-handler.spec.ts
- plugins/ports-plugin/tests/workspace-handler/workspace-output.stdout
- add extra routes in the editor plug-in
- simplify route extraction as there was an improvement in workspace model to get port through an attribute
- handle deletion of process routing when port is no longer listening
Linked to https://github.com/eclipse/che/issues/12061
I will update plug-in registry with the editor once it's merged
> Add ports plug-in by default in che-theia image.

- dockerfiles/theia/Dockerfile
We have a lot problem with plugin packager during work on che-theia plugins. 
So I suggest to remove `modules-folder` override from che-theia image
> Remove 'modules-folder' override

- dockerfiles/remote-plugin-kubernetes-tooling-0.1.17/Dockerfile
The PR extends the K8s plugin image:
- updates bundled `kubectl` version to 1.14.0;
- adds Helm client and certificates required by Helm to interact with the Chart repositories;
- sets up a local configuration for Helm to enable `Helm Repos` tree with no extra steps required from the user.
https://github.com/eclipse/che/issues/12982
> Add Helm into K8s plugin container to enable Helm funtionality

- che-plugins/che-editor-theia/etc/che-plugin.yaml
- plugins/ports-plugin/src/ports-plugin.ts
Limit the number of pre-defined routes to #3
Also do not propose redirect for ephemeral ports
#139 
Change-Id: I98570624346a5a63cfd55da66677cced634aa775
> [ports plug-in] Limit the number of pre-defined routes to #3

- build_and_push_docker_images.sh
- dockerfiles/remote-plugin-python-3.7.3/Dockerfile
- dockerfiles/remote-plugin-python-3.7.3/build.sh
Since python dev container will be based on official `python:3.7.3` image it is necessary to update Python version in LS container
https://github.com/eclipse/che/issues/12944
> Replace python 3.7.2 on 3.7.3

- extensions/extensions.yml
Preparing the inclusion of plugins when using `che:theia init` commands. https://github.com/eclipse/che-theia/issues/45
We would have folders for extensions and folders for plugins to create symblink.
So `folders` -> `extensionFolders`
and we would have a new section for plugins: `pluginFolders`
I kept the old version (`folders`) for the time being.
WDYT ?
https://github.com/eclipse/che-theia/issues/45
> Preparing next che:theia init generator model that would include plugins

- plugins/factory-plugin/src/projects.ts
- plugins/factory-plugin/src/theia-commands.ts
- plugins/factory-plugin/tests/projects.spec.ts
This is a copy of #144 but in a branch of the main repo so that CI is able to run on it.
This PR adds the ability to reset the freshly cloned repository to a specified tag, commitId or generally a startPoint.
This PR is to implement eclipse/che#12775 on the Theia side.
eclipse/che#12775
> Support checking out a specific tag/commit after cloning 

- plugins/task-plugin/src/che-workspace-client.ts
`machineName` is available in the `runtime` commands, not not the workspace config.
Fixing it to avoid user to choose a target container where component is already setted in devfile for a command.
#154
> Do not show list of containers where to run a che commands if target container/component is already defined in the devfile #154

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia-endpoint-runtime/Dockerfile
- dockerfiles/theia/Dockerfile
Since https://github.com/eclipse/che-theia/commit/009231cf97c9dc6c5cea65b8c222d08f013769af the version of Alpine was downgraded to 3.7.
This PR updates node to 10.15 with Alpine 3.8.
> Use node:10.15-alpine as a base image

- dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
We still need to have `musl` apk for `Alpine-3.8`
Should be merged after https://github.com/eclipse/che-theia/pull/175
> Revert removing musl apk

- plugins/containers-plugin/package.json
- plugins/containers-plugin/src/containers-plugin.ts
- plugins/containers-plugin/src/containers-service.ts
- plugins/containers-plugin/src/containers-tree-data-provider.ts
Renames `Containers` panel into `My Workspace`.
Moves user defined containers from root node to `User Runtimes` node, so root has only two nodes: `User Runtimes` and `Plugins`
https://github.com/eclipse/che/issues/12984
`Containers` panel is renamed into `My workspace`
For case, when no runtime containers are defined:
> Move user containers from root to 'User Runtimes' node. 

- dockerfiles/theia/Dockerfile
Some time CI cache `che:theia init` even if repo has new commits, this pull try to fix this
> Invalidate cache before che:theia init

- dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
Use node:10.15-stretch-slim as a base image for remote .Net plugin
https://github.com/eclipse/che/issues/12793
> Use node:10.15-stretch-slim as a base image for dotnet's plugins

- che-plugins/che-editor-theia/etc/che-plugin.yaml
Adds volume to persist global data of Theia, which includes (for all plugins):
- global state 
- workspace state 
- data directory
- Theia workspaces configuration (unless user defines another location for it)
https://github.com/eclipse/che/issues/12260
> Add volume for Theia data directory of the current user

- plugins/task-plugin/src/task/che-task-runner.ts
It was temporary solution to display output of a command to output channel. Within this [issue](https://github.com/eclipse/che/issues/11458) we depend on https://github.com/eclipse/che/issues/11442
So this PR is a workaround to improve displaying output for che commands in output channel
Then we switch task's output from output channel to terminal widget when https://github.com/eclipse/che/issues/11442  is resolved.
https://github.com/eclipse/che-theia/issues/192
> Improve displaying output for che commands in output channel

- che-theia-init-sources.yml
Propose the next format of `extensions.yml`, following the discussion https://github.com/ws-skeleton/che-theia-generator/pull/20#issuecomment-483263490:
- moving `extensions/extensions.yml` to `che-theia-init-sources.yml`
- renamed root `extensions` item to `sources`
- rename `pluginFolders` to `plugins`
- rename `extensionFolders` to `extensions`
https://github.com/eclipse/che-theia/issues/45
> Preparing next che:theia init generator model. Will move to the root …folder of the repo, rename root element and folders

- dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
To update dependencies for C# projects we need to have access to write files into home directory
https://github.com/eclipse/che/issues/13096
> Fix permission issue with updating dependencies for C# projects

- dockerfiles/theia-dev/Dockerfile
To restore build on CI we need to disable replacing ffmpeg for electron
> Disable replacing ffmpeg for electron

- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-quick-open.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
https://github.com/eclipse/che/issues/12950
> Use cwd for terminal creation

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-client.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- plugins/task-plugin/src/che-task-backend-module.ts
- plugins/task-plugin/src/machine/attach-client.ts
- plugins/task-plugin/src/machine/machine-exec-client.ts
- plugins/task-plugin/src/machine/machine-exec-watcher.ts
- plugins/task-plugin/src/machine/websocket.ts
- plugins/task-plugin/src/preview/task-events-handler.ts
- plugins/task-plugin/src/preview/tasks-preview-manager.ts
- plugins/task-plugin/src/task/che-task-runner.ts
- yarn.lock
TaskExitedEvent is fired when a che task is completed, so all interested entities have ability to:
- notify user when a che task is completed
- update UI
- clean up resources 
Please see a short demo https://youtu.be/-qafPjoU2dM
https://github.com/eclipse/che/issues/12838
> Add ability to track che tasks

- dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/Dockerfile
- dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/build.sh
- dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/etc/docker.sh
Allows the [Kubernetes Tooling Che Plugin](https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools) use [Buildah](https://github.com/containers/buildah) as an image builder instead of Docker daemon.
Currently, it's implemented with the `docker.sh` wrapper script that calls `buildah`.
In the future, we can add support for Buildah by [VS Code Kubernetes extension](https://github.com/Azure/vscode-kubernetes-tools/) natively and the wrapper script is not needed.
closes https://github.com/eclipse/che/issues/13316
> Allow Kubernetes Tooling Che Plugin use Buildah as an image builder instead of Docker daemon

- README.md
Adds a command line option to the build instruction.
`theia-dev` and `theia` should have same tag.
None.
> Fix the instruction for building images

- dockerfiles/theia/Dockerfile
- plugins/ports-plugin/src/ports-plugin.ts
Allow to exclude some ports for Ports Plugin
It will exclude for now 3130 port used in hosted mode of Theia
It fixes https://github.com/eclipse/che/issues/13300
Also move trace about ephemeral port to Ports Plugin output channel
It fixes https://github.com/eclipse/che-theia/issues/190
Change-Id: I50e4891028a7bacf60d7376fe05a99a835e429e9
> [Ports Plugin] excluding ports

- dockerfiles/build.include
Makes running `./build.sh` scripts with Bash version 4.3.x.
I checked the patch on both of  Ubuntu 16.04 (Bash 4.3) and Debian 9.8 (Bash  4.4.12).
None.
(Reference: https://stackoverflow.com/a/34361807 )
> Fix to run with Bash 4.3.

- dockerfiles/theia-endpoint-runtime/src/node/plugin-remote-init.ts
For now it was allowing too many `random` ports while running on the same pod and sharing network and pid is implying we could have a lot of random ports.
Change-Id: Ia2de2a14dd81d4e15dd97826dc0ec4661a91eaf3
> [endpoint] Increase the number of retries to able to find like 100 ports for all endpoints on a pod

- plugins/factory-plugin/src/file-uri.ts
- plugins/factory-plugin/src/projects.ts
- plugins/factory-plugin/src/workspace-projects-manager.ts
- plugins/factory-plugin/tests/file-uri.spec.ts
- plugins/factory-plugin/tests/projects.spec.ts
Make sure clone path is always relative and does not starts from slash as Che 6 project path.
https://github.com/eclipse/che/issues/13112
> Make sure clone path is always relative 

- dockerfiles/theia-endpoint-runtime/src/node/server-plugin-proxy-runner.ts
- dockerfiles/theia-endpoint-runtime/src/node/terminal-container-aware.ts
Replace '*/src/*' to '*/lib/*' in imports, to restore CI.
> Replace '*/src/*' to '*/lib/*' in imports

- dockerfiles/remote-plugin-php7/Dockerfile
- dockerfiles/remote-plugin-php7/build.sh
Based on che-theia-endpoint-runtime image.
Includes the following php7 packages:
php7 php7-fpm php7-opcache
php7-gd php7-mysqli php7-zlib php7-curl
php7-xdebug
In order to be used for VSCode PHP Language Support and Debugger extensions, it should be built using `--tag=next` which will add the support for node:10.15 and the latest VSCode API support required to run the mentioned VSCode extensions.
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>
Adds a docker image that is to be used in Che7 for PHP Language Support and Debugger and includes all the pre-requisite packages required to run the PHP plugins.
- PHP Language Support #12772 - https://github.com/eclipse/che/issues/12772
- Che 7 plugin: PHP Language Server #12797 - https://github.com/eclipse/che/issues/12797
- Che 7 plugin: …
> Docker image for PHP Language Support and Debugger

- dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/Dockerfile
Use `che-theia-endpoint-runtime` image tag passed as an argument instead of always `next`.
Seems I've overlooked it in my previous PR.
> Use theia-endpoint-runtime image tag from BUILD_TAG parameter

- che-plugins/che-editor-theia/etc/che-plugin.yaml
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-frontend-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-menu.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-preferences.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-view-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx
- extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/plugin/plugin-filter.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-backend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
- extensions/eclipse-che-theia-plugin-ext/tsconfig.json
- Displays a dedicated view with list of available plugins
- Installs / uninstalls a plugin by simple mouse click
- Displays installed plugins in separate list
- Allows the user to install a plugin from custom registry
- Installs VS Code extension using a command or drag and drop
Video demonstrating the feature
https://www.youtube.com/watch?v=2_GPZb1_Hew
https://github.com/eclipse/che/issues/12932
> Plugin management

- plugins/containers-plugin/src/containers-tree-data-provider.ts
If container in which command should be run cannot be detected from config, run the command in selected container.
A note about tasks priority. By default Theia looks first at provided tasks and then at configured tasks. That mean, if a user makes changes in tasks.json for a task defined in workspace recipe, the changes will not be applied and original task from workspace configuration will be used. But I believe this is another issue and if we need to change this behaviour, it should be done separately.
https://github.com/eclipse/che-theia/issues/222
https://github.com/theia-ide/theia/pull/5312
> Run Che command in selected container if container doesn't specified in configuration

- plugins/containers-plugin/src/containers-tree-data-provider.ts
Reverts eclipse/che-theia#253 because it depends on [this PR](https://github.com/theia-ide/theia/pull/5312) and do not work without that changes.
@monaka if you are not sure what and how a PR does, do not merge it please. If you are affected somehow, please ask about PR state.
> Revert "Run Che command in selected container if container doesn't specified in configuration"

- dockerfiles/theia/Dockerfile
Add ssh utility as before (when image was inside che repo) to allow ssh usage of git
Also as before, add less utility to better git diff output
https://github.com/eclipse/che/issues/12850
Change-Id: I1d1b7b83f02f5ebfc9957f3d5106c1ce13a080a6
> [docker image] Add ssh utility as before to allow ssh usage of git

- README.md
- build.sh
- build_and_push_docker_images.sh
- docker_image_build.include
`build.sh` will execute `yarn` and build all docker images.
Also PR include list of docker images which are builded during CI PR check.
> Note: Currently it is only 3 images: `theia-dev`, `theia` and `theia-endpoint-runtime`
> New 'build.sh' script, to build all repository

- che-theia-init-sources.yml
Add ssh-plugin to che-theia by default
As part of https://github.com/eclipse/che/issues/13494
> Add ssh-plugin to che-theia by default

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-frontend-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-menu.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx
- extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Makes it possible to view the list of built-in plugins
https://github.com/eclipse/che-theia/issues/244
> Display list of built-in plugins

- dockerfiles/build.include
Fixes the default docker tag `nightly` to `next`. `nightly` has not been used.
fixes #226
> Fix the default docker tag `nightly` to `next`.

- dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Sets `GOCACHE` explictly to a writable directory.
Removes the hardcoded location of /projects from the `GOPATH`. This is replaced by a dynamic resolution of `/projects` from the Che server done in https://github.com/eclipse/che-plugin-registry/pull/165.
This is to improve experience with the go plugin. The resetting of `GOCACHE` makes the warning about a directory not being writable disappear. `/projects` should not be hardcoded because it is actually configurable in the Che server.
https://github.com/eclipse/che/issues/13529
https://github.com/eclipse/che-plugin-registry/pull/165
> Set GOCACHE to a writable existing directory, change GOPATH

- dockerfiles/theia/extract-for-cdn.sh
Fix the error in case lack of parameters.
```
$ sh -c '[ "${image}" == "" ] && echo $?'
sh: 1: [: unexpected operator
```
```
$ sh -c '[ -z "${image}" ] && echo $?'
0
```
None.
> Use `-z` for empty checks.

- dockerfiles/theia/e2e/Dockerfile
Separated from #290.
And sudo command is used in entrypoint.sh.
I see it won't be called on Openshift. But it will be on other K8s based.
Partly #281
> Install `sudo` for the vanilla K8s.

- dockerfiles/theia/e2e/Dockerfile
- dockerfiles/theia/e2e/src/docker-run.sh
Some improvements to the e2e test for `che-theia`
The current test script wait booting Theia up by `sleep`.
But we can't estimate how long. So it's better to watch the status of TCP port.
None.
> Fix connection failure in the e2e test for `che-theia`

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-user-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-user.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
This PR adds `user` namespace to Che Plugin API and exposes there some methods of CheApiService.
fix https://github.com/eclipse/che/issues/13518
> Expose some methods of CheApiService to Che Plugin API

- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
Use 'ctrl+shift+`' key for new terminal in MacOS
> Use 'ctrl+shift+`' key for new terminal in MacOS

- dockerfiles/remote-plugin-kubernetes-tooling-1.0.0/Dockerfile
Updates Dockerfile for the Kubernetes Tooling Che Plugin:
- buildah 1.8.2 -> 1.9.0
- adds g+w permissions to user home dir
closes https://github.com/eclipse/che/issues/13537
also fixes https://github.com/eclipse/che/issues/13536
> [k8s plugin] fix Kubernetes: Run command

- dockerfiles/theia/Dockerfile
Adds the new argument named `THEIA_GITHUB_REPO`.
The default value is `theia-ide/theia` (same as the current)
Developers can use their forked versions of Theia.
None.
> Enable to use forked Theias.

- docker_image_build.include
- dockerfiles/remote-plugin-dependency-analytics-0.0.12/Dockerfile
- dockerfiles/remote-plugin-dependency-analytics-0.0.12/build.sh
It adds Dockerfile with required runtimes needed for Dependency Analytics Plugin https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics
https://github.com/redhat-developer/rh-che/issues/1045
N/A
> feat(dockerfile): adds dockerfile with required runtimes for analytics

- dockerfiles/remote-plugin-openshift-connector-0.0.17/Dockerfile
- dockerfiles/remote-plugin-openshift-connector-0.0.21/Dockerfile
The PR updates the links to download ODO for Openshift Connector Plugin image since the ODO repo has been recently moved from `redhat-developer` to `openshift` GitHub organization.
> Update link to download ODO since the repo is moved

- plugins/factory-plugin/src/ephemeral-workspace-checker.ts
Adds support in `EphemeralWorkspaceChecker` for devfile format of the _ephemeral workspace_ flag.
**Fixes** https://github.com/eclipse/che/issues/13577
> Adapt EphemeralWorkspaceChecker to devfile format

- plugins/task-plugin/resources/preview-urls-view.css
- plugins/task-plugin/src/preview/preview-url-open-service.ts
- plugins/task-plugin/src/preview/previews-widget.ts
- plugins/task-plugin/src/preview/task-events-handler.ts
- plugins/task-plugin/src/preview/tasks-preview-manager.ts
Currently, Preview URL panel's view is a bit confusing because it doesn't show any URL at all. This PR modifies it in the way to replace a server name with a resolved URL. In same way it updates a task preview notification which appears on top of Theia's page once a task is started.
fix https://github.com/eclipse/che/issues/13357
> Fix preview URL panel to show the resolved URL instead of a server name.

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia/Dockerfile
* Downloads vscode git extension package to default plugins directory.
* Update `theia-generator` version to one without native theia git extension (https://github.com/ws-skeleton/che-theia-generator/pull/28)
https://github.com/eclipse/che-theia/blob/ffbef321470fff581c1fd78a45b1decf4124ecc5/dockerfiles/theia-dev/Dockerfile#L42
Is needed for https://github.com/eclipse/che/issues/11867
> Include vscode git extension to default plugins

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia/Dockerfile
* Downloads vscode git extension package to default plugins directory.
* Update `theia-generator` version to one without native theia git extension
Is needed for https://github.com/eclipse/che/issues/11867
> Include vscode git extension to default plugins (#328)

- plugins/containers-plugin/package.json
- plugins/factory-plugin/package.json
- plugins/ports-plugin/package.json
- plugins/ssh-plugin/package.json
- plugins/task-plugin/package.json
- plugins/welcome-plugin/package.json
Add "activationEvents" field, for all plugins
After this commits in Theia:
https://github.com/theia-ide/theia/commit/906c4febfe2f9bab4342ae323dd68c68af9b07ae
https://github.com/theia-ide/theia/commit/4466a72bd44a64576a40108659c81f3885bed1a2
https://github.com/theia-ide/theia/commit/b39a852192256e333ed6f4e0a13bd48d127123ae
Plugins wont start without `activationEvents` field in `package.json`, see [VSCode doc](https://code.visualstudio.com/api/references/activation-events)
https://github.com/eclipse/che/issues/13779
> Add "activationEvents" field, for all plugins

- plugins/factory-plugin/src/projects.ts
- plugins/factory-plugin/tests/projects.spec.ts
- yarn.lock
Add new tests for the project synchronization. Fix implementation.
https://github.com/eclipse/che/issues/13621
> Fix synchronization of the existing projects

- plugins/factory-plugin/src/projects.ts
- plugins/factory-plugin/tests/projects.spec.ts
* CHE-13621 fix synchronization of the existing projects
* fix project.clonePath only defined if different from project.name
Signed-off-by: Sun Tan <sutan@redhat.com>
Add new tests for the project synchronization. Fix implementation.
https://github.com/eclipse/che/issues/13621
> Fix synchronization of the existing projects (#334)

- plugins/containers-plugin/src/containers-service.ts
- plugins/containers-plugin/src/containers-tree-data-provider.ts
- plugins/task-plugin/src/che-task-backend-module.ts
- plugins/task-plugin/src/export/export-configs-manager.ts
- plugins/task-plugin/src/export/launch-configs-exporter.ts
- plugins/task-plugin/src/export/task-configs-exporter.ts
- plugins/task-plugin/src/extract/che-task-configs-extractor.ts
- plugins/task-plugin/src/extract/config-file-launch-configs-extractor.ts
- plugins/task-plugin/src/extract/config-file-task-configs-extractor.ts
- plugins/task-plugin/src/extract/vscode-launch-configs-extractor.ts
- plugins/task-plugin/src/extract/vscode-task-configs-extractor.ts
- plugins/task-plugin/src/task-plugin-backend.ts
- plugins/task-plugin/src/task/che-task-provider.ts
- plugins/task-plugin/src/task/converter.ts
Export configurations of `Che` tasks to config file
`commands` section of `devfile` can contain actions with `che` commands, for example:
```
commands:
- name: task-plugin:watch
actions:
- type: exec
component: che-dev
command: >
yarn watch
workdir: /projects/che-theia/plugins/task-plugin
- name: che-theia:build
actions:
- type: exec
component: che-dev
command: >
yarn
workdir: /projects/che-theia
```
The PR allows to convert them to theia tasks format and copy to config file of current workspace folder. After that they are available for running from UI: `Terminal` => `Run Task` menu or using `My Workspace` panel. So now we consider `tasks.json` file as one source where user can find all `che` tasks, edit them or add a new task. 
The current implementation allows to merge existed …
> Export configurations of Che tasks to config file

- plugins/ssh-plugin/package.json
- plugins/ssh-plugin/src/ssh-plugin-backend.ts
- yarn.lock
Store SSH private key file on the file system when key is generated from the SSH Plugin
fixes https://github.com/eclipse/che/issues/13866
> Store SSH private key on the file system from SSH plugin

- dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Set permissions for `/go` folder when all dependencies are installed.
https://github.com/eclipse/che/issues/13823
> Fix permissions on $GOPATH folder

- plugins/containers-plugin/package.json
- plugins/factory-plugin/package.json
- plugins/ssh-plugin/package.json
- plugins/task-plugin/package.json
Add missing publisher field and set it to 'Eclipse Che'
According to this commit
https://github.com/theia-ide/theia/commit/6021d795d61eafb214b234288f1568cae0cfa9f5
`publisher` field is mandatory.
should fix https://github.com/eclipse/che/issues/13944
> Add missing publisher field and set it to 'Eclipse Che'

- README.md
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>
Remove last part of README about building images and give a link to the duplicated instructions file.
> Update README docker image build section

- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
- Fix displaying theia tasks output;
- Don't use in the code concrete remote terminal implementation, use interface.
- Che-theia tasks - works;
- Che-theia terminal - works;
- Che-theia terminal plugin api - works;
- Theia tasks - works;
https://github.com/eclipse/che/issues/13876
> CHE-13876: Fix displaying theia tasks output.

- plugins/welcome-plugin/resources/welcome-page.css
Applies missing styles for webkit scrollbars for welcome page
As it was before
Issue https://github.com/eclipse/che/issues/13972
> Styles for webkit scrollbars

- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
- Fix displaying theia tasks output;
- Don't use in the code concrete remote terminal implementation, use interface.
- Che-theia tasks - works;
- Che-theia terminal - works;
- Che-theia terminal plugin api - works;
- Theia tasks - works;
https://github.com/eclipse/che/issues/13876
> CHE-13876: Fix displaying theia tasks output. (Cherry-pick to 7.0.0 branch)

- plugins/task-plugin/src/task/che-task-provider.ts
- plugins/task-plugin/src/task/che-task-runner.ts
- plugins/task-plugin/src/task/converter.ts
- plugins/task-plugin/src/task/task-protocol.ts
Use 'containerName' instead of 'machineName' for che tasks
https://github.com/eclipse/che/issues/13667
Use the component in your devfile
```
- 
reference: >-
https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom/meta.yaml
```
The image contains:
- che-7.0.0 theia branch
- current 7.0.0 branch of che-theia + changes from the PR
Use some command in your devfile, for example:
```
- name: che-theia:build
actions:
- type: exec
component: che-dev
command: >
yarn
workdir: /projects/che-theia
```
The `component` field defined for a command in a devfile should be converted into `containerName` (not `machineName`) field for a task configuration in a `tasks.json` file when a workspace has started. …
> Use 'containerName' instead of 'machineName' for che tasks

- docker_image_build.include
remove 'latest' tag from '7.0.0-next' images, we mark `latest` tag only release images i.e. `7.0.0-rc-4.0`
> remove 'latest' tag from '7.0.0-next' images

- plugins/task-plugin/README.md
In the task plugin machineName was changed to containerName, let's do the same for README.md file.
> Fix README.md for task-plugin.

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
This PR fixes ability for Che Plugin extension to reload the IDE in iframe when it's necessary, i.e. after a Che Plugin has been installed.
fix https://github.com/eclipse/che/issues/13912
> Fix reloading Che Theia within iframe

- generator/tests/init-sources/init-sources.spec.ts
Fix che-theia/generator tests inside container without git user.name and user.email
https://github.com/eclipse/che/issues/14056
> Fix che-theia/generator tests inside container without git user.name and user.email

- generator/src/templates/assembly-package.mst
Fix yarn 'watch' command for che-theia/examples/assembly
https://github.com/eclipse/che/issues/13124
> Fix yarn 'watch' command for che-theia/examples/assembly

- generator/README.md
We should have a note in Che Theia generator readme about building particularity for Che Theia: if a user builds something from non root directory it will mess up dependencies and end up in non operatable Che Theia or compiling errors.
> Add a note about building Che Theia into generator readme

- dockerfiles/theia-dev/.gitignore
- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia-dev/build.sh
- dockerfiles/theia/Dockerfile
- dockerfiles/theia/build.sh
- generator/.gitignore
It use current che-theia source tree to build che-theia docker image, instead of cloning che-theia repo.
So now to build your custom che-theia images(with your changes in che-theia sources) just use `build.sh` script in root directory. You don't even need to commit your changes or modify some other files, just build docker images, build script automatically pick up your changes.
> Note: this PR also use che-theia generator(`che:theia init`) from che-theia sources, so if you change generator, you can easy test it, just call `build.sh` script and it will use your version of generator.
Part of eclipse/che#13738
> Use current che-theia sources for docker image build

- plugins/task-plugin/src/task/che-task-provider.ts
- plugins/task-plugin/src/task/task-protocol.ts
Allows to resolve variables for che commands before execution.
For example you can define command in your devfile:
```
- name: copy content
actions:
- type: exec
component: che-dev
command: >
cp ${workspaceFolder}/.theia/tasks.json ${workspaceFolder}/cheCommands.json
workdir: /projects
```
and `${workspaceFolder}` will be replaced by `/projects` for example, or use `${file}` to get path to 
the file opened in the current editor
https://github.com/eclipse/che/issues/14031
Use the component in your devfile
```
- 
reference: >-
https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom/meta.yaml
```
The image contains:
- che-7.0.0 theia branch
- current 7.0.0 branch of che-theia + changes from the PR
Use …
> Fix resolving of variables for che commands

- plugins/ssh-plugin/src/ssh-plugin-backend.ts
Show's a warning message that SSH key will be available in all containers (not only in `theia-ide` container) only after restarting the workspace. Workspace restart will mount the new SSH keys to all containers.
https://github.com/eclipse/che/issues/14073
> Show warning message after generating an SSH key

- extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts
Add context to event when a che task is complete.
It allows to use task name for notification when task is complete 
https://github.com/eclipse/che/issues/14125
<details>
<summary>I used the following in my devfile for testing:</summary>
```
metadata:
name: wksp-tasks
projects:
- name: che-theia
source:
type: git
location: 'https://github.com/eclipse/che-theia.git'
- name: theia
source:
type: git
location: 'https://github.com/theia-ide/theia.git'
components:
- 
alias: che-dev
image: eclipse/che-theia-dev:next
mountSources: true
endpoints:
- name: "theia-dev"
port: 3130
attributes:
protocol: tcp
public: 'true'
memoryLimit: 4Gi
- 
reference: >-
https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclips …
```
> Add context to notification when a che task is complete

- README.md
Updates the badge displaying build status of https://ci.codenvycorp.com/job/che-theia-7.0.0-next/
After renaming CI job `che-theia-latest-ci` to `che-theia-7.0.0-next` the badge become not working.
Subtask of https://github.com/eclipse/che/issues/14053
The PR https://github.com/eclipse/che-theia/pull/381 has affected the badge
> Badge displaying build status for 7.0.0

- plugins/ssh-plugin/src/ssh-plugin-backend.ts
SSH plugin generates a new SSH key then it is written to the `/home/theia/.ssh` directory of the theia-ide container, so the key is invisible from other containers. The aim of the message is to tell the user that after restarting the workspace the key will be mounted to all containers of the workspace.
Show's a warning message that SSH key will be available in all containers (not only in `theia-ide` container) only after restarting the workspace. Workspace restart will mount the new SSH keys to all containers.
https://github.com/eclipse/che/issues/14073
The PR to the master is merged: https://github.com/eclipse/che-theia/pull/389
> Show warning message after generating an SSH key (#389)

- docker_image_build.include
- dockerfiles/remote-plugin-clang-8/Dockerfile
- dockerfiles/remote-plugin-clang-8/build.sh
It adds the docker file to build a clang image
https://github.com/eclipse/che/issues/13698
> Add docker file to build clang image

- plugins/task-plugin/src/task/che-task-provider.ts
- plugins/task-plugin/src/task/task-protocol.ts
The changes are the same as in the PR https://github.com/eclipse/che-theia/pull/373
Allows to resolve variables for che commands before execution.
For example you can define command in your devfile:
```
- name: copy content
actions:
- type: exec
component: che-dev
command: >
cp ${workspaceFolder}/.theia/tasks.json ${workspaceFolder}/cheCommands.json
workdir: ${workspaceFolder}
```
and `${workspaceFolder}` will be replaced by `/projects` for example, or use `${file}` to get path to 
the file opened in the current editor
https://github.com/eclipse/che/issues/14031
Use the component in your devfile
```
- 
reference: >-
https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
```
Use a command …
> Resolve variables for che commands

- dockerfiles/theia/e2e/src/package.json
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-terminal/package.json
- generator/package.json
- yarn.lock
Upgrade version of 'jquery', 'axios' and 'xterm' to fix CVE's
CQ:
- xterm https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20720
- axios  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20719
eclipse/che#14142
> Upgrade version of 'jquery', 'axios' and 'xterm'

- dockerfiles/remote-plugin-clang-8/Dockerfile
Fixes build for `eclipse/che-remote-plugin-clang-8` 
It replaces packages `clang-tools-8` -> `clangd-8`
> Fix building clang docker image

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-menu.ts
Fixes appearing two `View > Plugins` items in top menu
https://github.com/eclipse/che/issues/13670
> Fixup: Hide Plugins view from upstream

- plugins/ssh-plugin/src/ssh-plugin-backend.ts
When executing a `clone` command via SSH url from the git plugin, the `clone` process fails if there is no related host in the `known_hosts` file. In order to this attribute host will be added automatically to the `known_hosts` file. SSH clone ends successfuly in this case.
https://github.com/eclipse/che/issues/14403
> Add Host Key checking policy attribute to the ssh config

- dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
- dockerfiles/theia/e2e/Dockerfile
Calls `node-gyp install` before rebuilds.
It will reduce build failures in `node-gyp rebuild`.
This patch doesn't care packages built with `theia/package.json`. I expect such builds will fixed by theia-ide/theia#5592
fixes #283 (won't fix but will reduce.)
> Run `node-gyp install` before rebuilds.

- dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
Since `dotnet --version` doesn't populate local dotnet packages it was changed to `dotnet help` to do that. All local packages are located in `/usr/share/dotnet/sdk/NuGetFallbackFolder` directory 
https://github.com/eclipse/che/issues/14370
https://github.com/eclipse/che/issues/14365
> Change a command to populate local package cache for dotnet image

- dockerfiles/remote-plugin-java11/Dockerfile
- dockerfiles/remote-plugin-java11/etc/before-start.sh
- dockerfiles/remote-plugin-java8/Dockerfile
- dockerfiles/remote-plugin-java8/etc/before-start.sh
- dockerfiles/theia-endpoint-runtime/etc/entrypoint.sh
Generates  `/home/theia/.m2/settings.xml` if `MAVEN_MIRROR_URL` is set.
```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
https://maven.apache.org/xsd/settings-1.0.0.xsd">
<mirrors>
<mirror>
<url>${env.MAVEN_MIRROR_URL}</url>
<mirrorOf>external:*</mirrorOf>
</mirror>
</mirrors>
</settings>
```
https://github.com/eclipse/che/issues/14391
> Generate settings.xml if MAVEN_MIRROR_URL is set

- extensions/eclipse-che-theia-plugin-remote/src/node/hosted-plugin-remote.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-reader-extension.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
Adds PluginReaderExtension class which handles case when requested resource is not found locally and in such cases sends request to corresponding sidecar where plugin resources are actually stored.
This PR does not handle resources for remote plugin webview because they are handles in a different way than usual plugin resources. Created issue for that problem: https://github.com/eclipse/che/issues/14444
Added support for remote plugins resources on Che Theia frontend side.
Added support for remote plugins resources on Che Theia frontend side.
Two remote plugins are loaded: Kubernetes plugins and Git UI Tools plugin (last two items in left sidebar)
Fixes https://github.com/eclipse/che/issues/13750
Depends on: …
> Implement remote plugin resources retrieving

- dockerfiles/remote-plugin-python-3.7.3/Dockerfile
It uses Debian based image because Microsoft Python Language Server doesn't start at Alpine based.
https://github.com/eclipse/che/issues/14074
> Use python:3.7.4-slim as a base image for python

- dockerfiles/theia-dev/e2e/Dockerfile
- dockerfiles/theia-endpoint-runtime/Dockerfile
- dockerfiles/theia/Dockerfile
Fixes syntax error in bash script of Che Theia image build. Fixup for https://github.com/eclipse/che-theia/pull/434
> Fixup: Fix syntax error in Che Theia image build script

- che-theia-init-sources.yml
- extensions/eclipse-che-theia-git-provisioner/.gitignore
- extensions/eclipse-che-theia-git-provisioner/package.json
- extensions/eclipse-che-theia-git-provisioner/src/browser/git-frontend-module.ts
- extensions/eclipse-che-theia-git-provisioner/src/browser/git-preferences.ts
- extensions/eclipse-che-theia-git-provisioner/src/node/git-backend-module.ts
- extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-contribution.ts
- extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-controller.ts
- extensions/eclipse-che-theia-git-provisioner/tsconfig.json
- extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts
- extensions/eclipse-che-theia-user-preferences/tsconfig.json
This changes proposal is addition to https://github.com/eclipse/che/pull/14402 and adds ability to configure git user name and email through Theia preferences.
Demo for this PR: https://www.youtube.com/watch?v=Q_XsUWR_mJY&feature=youtu.be
Signed-off-by: Vlad Zhukovskyi <vzhukovs@redhat.com>
https://github.com/eclipse/che/issues/13959
Add ability to set up git user name and email in theia preferences
> Add ability to set up git user name and email in theia preferences

- README.md
- devfiles/che-theia-all.devfile.yaml
- dockerfiles/theia-dev/e2e/Dockerfile
- dockerfiles/theia-endpoint-runtime/Dockerfile
- dockerfiles/theia/Dockerfile
- extensions/eclipse-che-theia-plugin-remote/devfile.yaml
- generator/README.md
- generator/tests/init/root-folder/packages/core/package.json
- plugins/factory-plugin/tests/projects.spec.ts
Fixes https://github.com/eclipse/che/issues/14529
As theia upstream moved from github.com/theia-ide/theia to github.com/eclipse-theia/theia, I'm opening this PR to target that.
Also this caused failures like https://github.com/eclipse/che/issues/14529, because the second call in the redirect was not using the github token, thus we were hitting API rate limits. This PR should fix that.
Only required places to fix #14529 are the dockerfiles, but I thought it would be nice to change it everywhere.
https://github.com/eclipse/che/issues/14529
> Replace github.com/theia-ide/theia by github.com/eclipse-theia/theia.

- plugins/task-plugin/README.md
Simple string change in che task API format as `machineName` is no longer used.
> chore(README): update che task format

- dockerfiles/theia-dev/build.sh
Rebuild Che Theia generator when cache assembly is out of date.
Before we used previously built artifact if it existed on disk and with such approach we're loosing new changes in the generator.
Now the generator is built when there is a change in the generator source code or the last commit which has changed the generator is newer than built assembly.
Should provide fix for https://github.com/eclipse/che/issues/14555
https://github.com/eclipse/che/issues/14555
> Build Che Theia generator on image build if it was changed in any way

- plugins/factory-plugin/src/theia-commands.ts
Adds missed project type to factory plugin.
fix https://github.com/eclipse/che/issues/14668
> Add 'github' project type to factory-plugin

- .gitignore
- docker_image_build.include
- dockerfiles/theia/Dockerfile
- extensions/che-theia-hosted-plugin-manager-extension/package.json
- extensions/eclipse-che-theia-about/package.json
- extensions/eclipse-che-theia-activity-tracker/package.json
- extensions/eclipse-che-theia-dashboard/package.json
- extensions/eclipse-che-theia-git-provisioner/package.json
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-remote/package.json
- extensions/eclipse-che-theia-preferences-provider-extension/package.json
- extensions/eclipse-che-theia-terminal/package.json
- extensions/eclipse-che-theia-user-preferences/package.json
- plugins/containers-plugin/package.json
- plugins/factory-plugin/package.json
- plugins/ports-plugin/package.json
- plugins/ssh-plugin/package.json
- plugins/task-plugin/package.json
- plugins/welcome-plugin/package.json
- yarn.lock
Use theia 0.11.0 before fixing code due to upstream changes
https://github.com/eclipse-theia/theia/pull/6252
> Use 0.11.0 upstream theia before fixing breaking changes in upstream master

- plugins/containers-plugin/src/containers-plugin.ts
- plugins/containers-plugin/src/containers-tree-data-provider.ts
- yarn.lock
In some cases it is impossible to figure out container for a command defined in Che workspace devfile. Then such a command is displayed in each container of the workspace in Workspace panel. But when a user clicks on it, Che asks the user to select container in which this command should be run. But in case of clicking on specific node of specific container it is obvious in which container this command should be run this time.
This PR addresses such case and runs the clicked command in the right container.
Example of workspace which has ambiguous commands:
<details>
<summary>devfile</summary>
```yaml
metadata:
name: test-tasks
projects:
- name: NodeJS-Sample-App.git
source:
location: 'https://github.com/sleshchenko/NodeJS-Sample-App.git' …
```
> Run Che command in selected container

- docker_image_build.include
- dockerfiles/remote-plugin-dependency-analytics-0.0.13/Dockerfile
- dockerfiles/remote-plugin-dependency-analytics-0.0.13/build.sh
It adds python runtime to dependency analytics image which is needed for Dependency Analytics Plugin from [0.0.13](https://marketplace.visualstudio.com/items?itemName=redhat.fabric8-analytics) onwards.
> Add python 3.7.4 runtime to dependency analytics

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
If remote terminal fails to open, an error notification will be shown. A notification may contain possible fault reason. Also, an error's stack trace will be sent to Output channel.
- `Terminal failed to open. Possible reason is bad default login. See more in "Output".`
- `Terminal failed to open. Possible reason is workspace service account lacks some privileges. See more in "Output".`
- `Terminal failed to open. See more in "Output".`
fixes https://github.com/eclipse/che/issues/13980
> Show notification when terminal fails to open.

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
Fix the bug related to hanging of request for getting [processId](https://github.com/eclipse-theia/theia/blob/2a978748c6e51a1f31adb34ed4661528e4e98438/packages/plugin/src/theia.d.ts#L2550) for terminal.
The cause of the bug is: [deferredProcessId](https://github.com/eclipse-theia/theia/blob/02c5c1d4539efa8b19f9d0991be9827c88e184f6/packages/plugin-ext/src/plugin/terminal-ext.ts#L94) is never resolved/rejected for case when starting of a terminal is failed. The good example to reproduce it:
- run a task
- wait till the task is completed
- refresh page and try to get `processId` using terminal API
So for this case attempt to attach to corresponding terminal is failed (the task is completed), as result we have opened terminal widget, but info about `processId` for related terminal is absent. …
> Fix getting processId at using terminal API

- plugins/ssh-plugin/src/ssh-plugin-backend.ts
Validate SSH key list in the view / delete actions of the SSH Plugin
https://github.com/eclipse/che/issues/14218
> Validate SSH keys list before view/delete

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-api-provider.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts
Use theia-plugin-ext from node_modules. We need this because nexe tool doesn't resolve path with `__dirname`.
Needed for https://github.com/eclipse/che/issues/13387
> Use theia-plugin-ext from node_modules.

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Throws error instead of using hardcoded url for plugin registry
eclipse/che#14553
> Throw error instead of using  hardcoded url for plugin registry

- plugins/factory-plugin/src/exec.ts
- plugins/factory-plugin/src/git.ts
Add ability to handle error from `execGit()` method.
fixes https://github.com/eclipse/che/issues/14775
> Do not catch error while executing Git commands, factory plugin

- .gitignore
- dockerfiles/build.include
- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia-dev/build.sh
- dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile
- dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile
- dockerfiles/theia-dev/docker/alpine/setup-yarn.dockerfile
- dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile
- dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile
- dockerfiles/theia-dev/docker/ubi8/setup-yarn.dockerfile
- dockerfiles/theia-dev/e2e/Dockerfile
- dockerfiles/theia-dev/e2e/build.sh
- dockerfiles/theia-dev/e2e/docker/alpine/post-clone.dockerfile
- dockerfiles/theia-dev/e2e/docker/ubi8/post-clone.dockerfile
- dockerfiles/theia/.gitignore
- dockerfiles/theia/Dockerfile
- dockerfiles/theia/build.sh
- dockerfiles/theia/docker/alpine/builder-clone-theia.dockerfile
- dockerfiles/theia/docker/alpine/builder-from.dockerfile
- dockerfiles/theia/docker/alpine/runtime-adduser.sh
- dockerfiles/theia/docker/alpine/runtime-from.dockerfile
- dockerfiles/theia/docker/alpine/runtime-install-dependencies.dockerfile
- dockerfiles/theia/docker/alpine/runtime-setup-yarn.dockerfile
- dockerfiles/theia/docker/ubi8/builder-clone-theia.dockerfile
- dockerfiles/theia/docker/ubi8/builder-from.dockerfile
- dockerfiles/theia/docker/ubi8/builder-post-clone.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-adduser.sh
- dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-install-dependencies.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-setup-yarn.dockerfile
It provides a system of includes and overrides
Reduce the copy/paste between docker images
No more scripts, pure includes
example `#{INCLUDE:docker/${BUILD_IMAGE_TARGET}/runtime-install-dependencies.dockerfile}`
will include a file named `docker/ubi8/runtime-install-dependencies.dockerfile` for `ubi8` based image and `docker/alpine/runtime-install-dependencies.dockerfile` for Alpine image
something...
if `--build-arg:DO_REMOTE_CHECK=false` it will remove the lines between IF/ENDIF from the final Dockerfile
Adds also` --dry-run` mode to just generate the Dockerfile
https://github.com/eclipse/che/issues/13765
Change-Id: Ia29d9ecdc61b9d4e02c5b205d7591a5424fb7cc7
> feat(docker): Provides ubi8 based images for che-theia and che-theia-dev

- dockerfiles/remote-plugin-camelk-0.0.9/Dockerfile
- dockerfiles/remote-plugin-camelk-0.0.9/build.sh
- reuse Kubernetes image
- add kamel executable
provides the Dockerfile that will be used for VS Code Camel K extension to pu tin Che registry
eclipse/che#14806
> Provide Docker image for Camel K plugin eclipse/che#14806

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-client.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- plugins/task-plugin/src/task/che-task-runner.ts
Improves the way of storage runtime info for Che tasks.
We keep runtime info for Che tasks on plugin side. The problem is the plugin side is reloaded each time the browser refreshes and we lose runtime info at this step. For more details please see https://github.com/eclipse/che/issues/13722#issuecomment-520437999.
The changes suggest to store runtime info on node side of `eclipse-che/theia-plugin-ext`.
https://github.com/eclipse/che/issues/13722
The changes are related to che tasks, so please try to run any che task from `My Workspace` panel and from `Terminal` -> `Run Task` menu as well
> Change way of storage runtime info for che tasks

- dockerfiles/theia/build.sh
Fix command for building che-theia archive
Also it's was appending to the archive so you might had duplicates
brew system / @nickboldt reported that when using the archive, it was a tar archive, not gzipped archive as filename extension was reported.
Change-Id: I25a7a45b2af6ab20c961c1f34303722e4e9de13c
> chore(docker): Fix theia build: che theia archive was not a .gz archive

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
Modify 'configStorage' path for remote plugin, as `/home/theia/` may not present in remote plugin image
eclipse/che#14797
> Modify 'configStorage' path for remote plugin

- extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/hosted-plugin-remote.ts
Fix applying remote plugin contributions when deploy slower than frontend start. We call deploy method to sync plugin contributions in the frontend.
https://github.com/eclipse/che/issues/14833
> Fix applying remote plugin contributions when deploy slower than frontend start.

- build.include
- dockerfiles/remote-plugin-kubernetes-tooling-1.0.4/Dockerfile
- dockerfiles/remote-plugin-kubernetes-tooling-1.0.4/build.sh
Adds Dockerfile for building an image for Kubernetes Tooling Che Plugin 1.0.4 introduced by https://github.com/eclipse/che-plugin-registry/pull/256
https://github.com/eclipse/che/issues/13316
> Add Dockerfile for Kubernetes Che Plugin based on VS Code Kubernetes extension 1.0.4

- plugins/task-plugin/src/preview/task-events-handler.ts
Resolve preview URL for notification.
https://github.com/eclipse/che/issues/14820
Please use steps to reproduce from the issue description
or
1. start a workspace 
1. open `.theia/tasks.json` file and add the configuraion
```
{
"type": "che",
"label": "test task",
"command": "sleep 30 && echo task is completed",
"target": {
"workingDir": "/projects",
"containerName": "che-dev"
},
"previewUrl": "${server.theia}",
"problemMatcher": []
}
```  
1. save `.theia/tasks.json` and run the task
1. right-bottom notification with previewUrl should appear. URL to theia component is correct there
1. try to use `Preview` and `Go To` buttons in the right-bottom notification: opened URL should be properly evaluated.
> Resolve preview URL for notification

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
- plugins/task-plugin/src/task/che-task-runner.ts
Add ability to stop `che` task by sending `ctrl+c` to the corresponding terminal.
User can use `Terminal => Terminate Task` action or close the corresponding terminal tab.
See the video https://youtu.be/9u71j-Etg04
Please note there is the issue https://github.com/eclipse/che/issues/14887 related to terminal widgets when task is completed or interrupted.
https://github.com/eclipse/che/issues/13737
1. Start any workspace with `che` tasks, you can use the devfile as example:
<details>
```
metadata:
name: wksp-stop-tasks
projects:
- name: che-theia
source:
type: git
location: 'https://github.com/eclipse/che-theia.git'
- name: theia
source:
type: git
location: 'https://github.com/theia-ide/theia.git'
components:
- 
alias: che-dev …
```
> Add ability to stop running task

- plugins/containers-plugin/src/containers-tree-data-provider.ts
Before, in the containers plugin we had all the plugin containers unfolded. This PR makes plugin containers folded by default if there is no a command defined.
https://github.com/eclipse/che/issues/13587
> [Containers plugin] Unfold plugin container node only if it has a command

- plugins/task-plugin/src/che-task-backend-module.ts
- plugins/task-plugin/src/che-workspace-client.ts
- plugins/task-plugin/src/preview/previews-widget.ts
- plugins/task-plugin/src/preview/task-events-handler.ts
- plugins/task-plugin/src/task-plugin-backend.ts
- plugins/task-plugin/src/variable/preview-url-variable-resolver.ts
Register preview URL links as variables
https://github.com/eclipse/che/issues/14892
1. Server side changes are [under review](https://github.com/eclipse/che/pull/14713), so please start server using image:
`chectl server:start -i quay.io/mvala/che-server:previewurl`
2. I modified a little devfiles from [the PR description](https://github.com/eclipse/che/pull/14713)(@sparkoo thanks! ) and add the reference for `docker image: maxura/che-theia:503` related to the current PR, so you can use the following devfile:
<details>
```
apiVersion: 1.0.1-beta
metadata:
name: preview-url-support
projects:
- name: dummy-http-server
source:
type: git
location: "https://github.com/sparkoo/dummy-http-server.git"
components:
- 
alias: che-dev
image: …
```
> Register preview URL links as variables

- extensions/eclipse-che-theia-plugin-remote/src/node/hosted-plugin-remote.ts
In remote plugins mechanism we send some meta information between main Theia and remote plugin host. This PR provides the fix for the case when client has not connected yet, but we've got a message to send. It is safe to not to send the info, because when client is ready it queries the info itself.
https://github.com/eclipse/che/issues/14942
> [Remote plugins] Call OnDidDeploy only if client is set

- plugins/factory-plugin/src/theia-commands.ts
Changes message when a project is sparsely cloned to fit a sparse checkout template case. For example `/dir/*.java`.
https://github.com/eclipse/che/issues/13671
> Fix message of sparse checkout to fit template

- plugins/task-plugin/README.md
- plugins/task-plugin/src/che-task-backend-module.ts
- plugins/task-plugin/src/che-workspace-client.ts
- plugins/task-plugin/src/export/export-configs-manager.ts
- plugins/task-plugin/src/export/launch-configs-exporter.ts
- plugins/task-plugin/src/export/task-configs-exporter.ts
- plugins/task-plugin/src/machine/machines-picker.ts
- plugins/task-plugin/src/task/backward-compatibility.ts
- plugins/task-plugin/src/task/che-task-provider.ts
- plugins/task-plugin/src/task/converter.ts
- plugins/task-plugin/src/task/task-protocol.ts
- plugins/task-plugin/src/utils.ts
Use `component` field for task configuration instead of `containerName` one.
`containerName` is used to indicate which container should be used for running task configuration.
The problem is: some container names are dynamic and are changed at restarting workspace.
The PR changes  suggest to use `component` instead of `containerName` for this goal. So, the new behavior is:
- `devfile` and `tasks.json` files keep `component` field
- `component` is used to identify the target container at running a configuration 
- dropdown menu is displayed to provide ability to select target container if component contains few containers
Backward compatibility for `containerName` field of task configuration is provided for existing workspaces.
So, the following configuration:
```
{
"type": "che",
"label": …
```
> Use component for task configuration instead of container name

- extensions/eclipse-che-theia-plugin-remote/devfile.yaml
Adds commands to build `plugin-ext` (Theia plugin API impl) , `theia-remote` (remote plugin side mechanism) and Che-Theia assembly. The commands are useful when watchers cannot be used for some reason and a developer doesn't want to compile whole Theia to apply changes.
> Add build commands into Che Theia remote devfile

- dockerfiles/remote-plugin-dependency-analytics-0.0.13/rhel.Dockerfile
Fix analytics ubi image.
https://github.com/eclipse/che/issues/14797
P.S. I am not sure that @nickboldt used this image, but if we really need to store rhe.Dockerfiles they should be working.
> Fix analytics ubi image.

- build.include
- dockerfiles/theia-endpoint-runtime/README.md
Disable building and publishing of `eclipse/che-theia-endpoint-runtime` image
After https://github.com/eclipse/che-theia/pull/485 PR we use `eclipse/che-theia-endpoint-runtime-binary` image to provide remote plugin runtime.
> Disable building and publishing of 'eclipse/che-theia-endpoint-runtime' image

- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-mini-browser-open-handler.ts
- yarn.lock
Override `toolbar` property for mini browser to provide ability to edit URL in the preview panel.
**Note:** the PR does preview URL editable, but does not resolve security related problems, so user can run into a security exception due to CORS.
https://github.com/eclipse/che/issues/14829
1. Use the following devfile, which contains the reference for `docker image: maxura/che-theia:527` related to the current PR.
<details>
```
apiVersion: 1.0.1-beta
metadata:
name: test-editable-preview-url
projects:
- name: dummy-http-server
source:
type: git
location: "https://github.com/RomanNikitenko/dummy-http-server.git"
components:
- 
reference: >-
https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/cu …
```
> Provide ability to edit URL in the preview panel

- build.include
- dockerfiles/remote-plugin-openshift-connector-0.1.1/Dockerfile
- dockerfiles/remote-plugin-openshift-connector-0.1.1/build.sh
- dockerfiles/remote-plugin-openshift-connector-0.1.1/etc/entrypoint.sh
Adds Dockerfile to build an image for running OpenShift Connector Che Plugin based on the VS Code extension v0.1.1. The latest version contains an important [fix](https://github.com/redhat-developer/vscode-openshift-tools/pull/1254) for `Open URL` command.
Also, the Dockerfile updates odo from v1.0.0-beta5 to v1.0.0 as it's required by the VS Code extension.
https://github.com/eclipse/che/issues/13406
https://github.com/eclipse/che/issues/13410
> Add Dockerfile for OpenShift Connector plugin v0.1.1

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
It prevents 'resize' failed errors after creating a new terminal.
https://github.com/eclipse/che/issues/13830
> Fix resize failed errors in the browser console

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
Signed-off-by: Mykola.Morhun <mmorhun@redhat.com>
Fixes `terminal "1" does not exist ` error on terminal start.
Resolves: https://github.com/eclipse/che/issues/13630
> Fix terminal not found error on terminal start

- generator/src/init-sources.ts
- generator/src/repository.ts
- generator/tests/init-sources/init-sources.spec.ts
The main reason while tests are failing is timeout when cloning che-theia sources.
To make tests stable, it was decided to:
- increase timeout to 30 seconds for failing tests
- add an option to omit git history when cloning che-theia sources
We can add a command line option for the generator for omitting git history. This improvement we could use when building docker images.
https://github.com/eclipse/che/issues/14276
> Fixes failing unstable tests

- extensions/eclipse-che-theia-dashboard/package.json
- extensions/eclipse-che-theia-git-provisioner/package.json
- extensions/eclipse-che-theia-terminal/package.json
- extensions/eclipse-che-theia-terminal/src/browser/server-definition/remote-connection.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
- yarn.lock
Introduces changes to catch up with upstream changes.
After https://github.com/eclipse-theia/theia/commit/9ae37183cd777f803b1fe8ac2c94a7f7e405e007 we've got https://github.com/eclipse/che/issues/15153 (inability to create a new terminal widget).
In this PR ReconnectingWebSocket is used insted of pure WebSocket. Updated `yarn.lock`.
https://github.com/eclipse/che/issues/15153
> Fix cannot create a new terminal issue

- extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-command-filter.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-quick-open.ts
- plugins/task-plugin/src/che-workspace-client.ts
- plugins/task-plugin/src/machine/machines-picker.ts
This changes proposal align behavior to select target container when new terminal opens or new task starts. By the design the flow from the `Find command` action was taken. To separate developer and tooling containers:
When `Find command` is executed:
When new terminal opens:
When new task starts:
Devfile to test changes: https://gist.github.com/vzhukovskii/23b275d18af208629648430df251a78e/raw/6451e1d0589cb435bf58208d560fb8006e338cd8/che-dev-workspace.yaml
Steps to test changes manually:
* clone `[che-theia](https://github.com/eclipse/che-theia)` and `theia`
* checkout to `quick_pick_items_ext` in `che-theia` and `theia` repo
* build `che-theia`, then go to dockerfile/theia and build docker image: `./build.sh --build-args:GITHUB_TOKEN=${GITHUB_TOKEN},THEIA_VERSION=master --tag:next …
> Add ability to configure borders in quick pick items list on plugin side

- dockerfiles/theia/Dockerfile
- dockerfiles/theia/e2e/Dockerfile
- extensions/eclipse-che-theia-git-provisioner/src/browser/git-frontend-module.ts
- extensions/eclipse-che-theia-user-preferences/package.json
- generator/package.json
- generator/src/logger.ts
- package.json
- yarn.lock
Upgrade typescript to 3.5.3 to match with Theia.
After https://github.com/eclipse-theia/theia/commit/a2d89c83245cdb894d35135f23d51139e374a447 commit in Theia, Theia use typescript 3.5.3
CI cannot build che-theia images
> Upgrade typescript to 3.5.3 to match with theia

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx
- extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css
Asks the Dashboard to restart the workspace after plugin installation. 
https://github.com/eclipse/che/issues/15006
> Use dashboard to restart the workspace 7.3.2

- dockerfiles/remote-plugin-python-3.7.3/Dockerfile
- dockerfiles/remote-plugin-python-3.7.4/Dockerfile
add missing dependencies
```
00:50:02     creating build/temp.linux-x86_64-3.7/lib
00:50:02     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I./python -I./lib -I/usr/local/include/python3.7m -c ./python/ujson.c -o build/temp.linux-x86_64-3.7/./python/ujson.o -D_GNU_SOURCE
00:50:02     unable to execute 'gcc': No such file or directory
00:50:02     error: command 'gcc' failed with exit status 1
```
https://github.com/eclipse/che/issues/15230
Change-Id: Ie10d532813968140d4cfe5a6e8724f73837ab16a
> fix(build): Python dependencies are requiring gcc at build time

- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- plugins/task-plugin/src/schema/che-task-schema.ts
- plugins/task-plugin/src/task-plugin-backend.ts
- yarn.lock
Add schema for `che` tasks:
- `type`, `command` and `label` are required properties 
- `target` and `previewUrl` are optional fields
-  `target` contains optional `workingDir` and `component` properties
- additional properties are allowed
https://github.com/eclipse/che/issues/15179
https://github.com/eclipse/che/issues/13984
Unfortunately, content assistant for `tasks.json` is broken at the moment: https://github.com/eclipse-theia/theia/issues/6542, so we can not fully test it. But `che` tasks should be available for running from `Terminal => Run Task` menu.
1. Use the following devfile, which contains the reference for image with changes related to the current PR (you can check it using `Help=> About` dialog).
<details>
```
apiVersion: 1.0.1-beta
metadata: …
```
> Add schema for che tasks

- extensions/eclipse-che-theia-about/package.json
- extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts
In About dialog we used webview API implementation endpoint to retrieve product logo. Such approach is not good and current PR retrieves the logo via upstream mini-browser service.
https://github.com/eclipse/che/issues/14883
> Do not use webview service for product logo in about dialog

- dockerfiles/remote-plugin-camelk-0.0.10/Dockerfile
It is notably fixing an issue with using the container service account
instead of the kubeconfig when provided
> feat(core) Use newer Kamel executable 1.0.0-M4 eclipse/che#15086

- plugins/ports-plugin/src/ports-plugin.ts
- plugins/ports-plugin/src/workspace-handler.ts
- plugins/ports-plugin/src/workspace-port.ts
Removes functionality from port plugin which suggest to open link of already opened in workspace configuration port.
This is mainly done because of preview url suggestion when a task is started. In such case two popups are raised.
https://github.com/eclipse/che/issues/14802
> [Port plugin] Do not suggest to open link of exposed by workspace config port

- extensions/eclipse-che-theia-git-provisioner/src/browser/git-config-changes-tracker.ts
- extensions/eclipse-che-theia-git-provisioner/src/browser/git-frontend-module.ts
- extensions/eclipse-che-theia-git-provisioner/src/browser/status-bar-contribution.ts
- extensions/eclipse-che-theia-git-provisioner/src/common/git-protocol.ts
- extensions/eclipse-che-theia-git-provisioner/src/node/git-backend-module.ts
- extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-controller.ts
Check user name and email in the global Git config. If present do not show git user config message:
https://github.com/eclipse/che/issues/14616
N/A
N/A
> CHE-14616: Do not show git user config message if they set to global config

- extensions/eclipse-che-theia-plugin-remote/devfile.yaml
Remove che-machine-exec:next plugin from remote plugin devfile.
che-machine-exec is predefined plugin and next tag is depracated and removed.
none. Devfile support.
> Remove che-machine-exec:next plugin from remote plugin devfile.

- generator/src/templates/assembly-package.mst
Set default git clone directory to '/projects'. Do not ask project directory when running `Git clone`.
https://github.com/eclipse/che/issues/13894
> Set default git clone directory to '/projects'

- dockerfiles/theia/Dockerfile
- dockerfiles/theia/src/entrypoint.sh
- dockerfiles/theia/src/get-webview-route.js
Co-authored-by: Oleksandr Andriienko <oandriie@redhat.com>
Fixes webview after changes in upstream Eclipse Theia.
According to changes in upstream Eclipse Theia, each webview is run on its own domain by default. In this PR we reconfigure Theia to run all webviews on the same as Che Theia host (actually as it was before).
Also after upstream changes it is possible to run webviews only with secure connection (requires https protocol), the only exception is localhost for testing purposes.
https://github.com/eclipse/che/issues/15283
> Fix webview after changes in upstream.

- extensions/eclipse-che-theia-plugin-remote/src/node/execute-command-container-aware.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
Register ArgumentProcessor that is responsible to process only URI argument types. Argument processor checks for the path and if path is not starts with project root, then file scheme modifies with the container name to be looks like this: `file-sidecar-${machineName}`. This will allow che-theia to pass into executed commands correct file resources, taken from different containers.
https://github.com/eclipse/che/issues/13044
Intercept uri arguments and set container name into file scheme
N/A - internal modification.
> Intercept uri arguments and set container name into file scheme

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-view-list.tsx
Handles loading of plugin icon. Displays default icon when the plugin icon cannot be loaded.
https://github.com/eclipse/che/issues/15193
> Display default Plugin icon when error

- dockerfiles/theia-dev/Dockerfile
Installs `generator-code` package to theia-dev container. It allows to launch VS Code extension generator in theia-dev container using terminal.
Part of the issue https://github.com/eclipse/che/issues/14228
> Add VS Code extension generator to theia-dev container

- dockerfiles/theia/Dockerfile
Adds **SHELL** environment variable into theia-ide dockerfile. This env points to default shell.
https://github.com/eclipse/che/issues/15116
> Add SHELL environment variable into theia-ide dockerfile

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts
- plugins/task-plugin/src/export/export-configs-manager.ts
- plugins/task-plugin/src/task-plugin-backend.ts
The validation system for task configurations in `theia` project [was updated](https://github.com/eclipse-theia/theia/pull/6616/files#r350946933):
- **the previous behavior**: the logic is task valid or not was executed every time we took the configurations for running.
- **the current behavior**:  the validation is executed on events (for example, config file was changed).
I [added](https://github.com/eclipse-theia/theia/commit/f85acd6e78b29df856b6f3df268116e2cbf6601f) `onDidChangeTaskSchema` event in `theia` project to validate tasks configurations when task schema is changed. It allows to reorganize tasks at adding schema for tasks in general and for `che` tasks in particular.
The current PR changes regulates the order of this process for `che` tasks: 
- at first: adding schema for …
> Adapt che tasks to updated validation system

- cico_build_master.sh
- cico_build_nightly.sh
- cico_build_release.sh
- cico_common.sh
- dockerfiles/theia-dev/build.sh
Add scripts for Centos CI, for now it is only `master`, `nightly` and `release` scripts.
Note that [https://ci.centos.org/view/Devtools/](https://ci.centos.org/view/Devtools/) will publish docker images on [quay.io](https://quay.io):
- che-theia-dev - https://quay.io/repository/eclipse/che-theia-dev?tag=latest&tab=tags
- che-theia - https://quay.io/repository/eclipse/che-theia?tag=latest&tab=tags
- eclipse/che-theia-endpoint-runtime-binary - https://quay.io/repository/eclipse/che-theia-endpoint-runtime-binary?tab=tags
eclipse/che#14849
> Add scripts for Centos CI

- extensions/eclipse-che-theia-activity-tracker/src/browser/che-theia-activity-tracker-contribution.ts
Activity tracker extension sends message to User Dashboard which makes UD to refresh keycloak token so as to avoid User Dashboard reloading. 
fixes https://github.com/eclipse/che/issues/14933
> Post message to Dashboard in order to refresh keycloak token.

- README.md
- cico_build_pr.sh
- devfiles/che-theia-all.devfile.yaml
- dockerfiles/theia/README.md
Add script for PR build job, update links for new CI
>Note: there are no PR build job yet on centos CI
https://github.com/eclipse/che/issues/14849
> Add script for PR build job, update links for new CI

- plugins/task-plugin/src/variable/project-path-variable-resolver.ts
This changes proposal modifies behavior of resolving `${current.project.path}` by respecting current selection and presence of projects in project root. Besides if user didn't select any project, the warning message will be shown.
https://github.com/eclipse/che/issues/13636
N/A
N/A
> Correct resolving of current project path

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
This PR fixes bug in `@eclipse-che/theia-plugin-ext` extension which doesn't allow to send a message with `restart-workspace` action to parent window when Che runs in single-user mode.
fixes https://github.com/eclipse/che/issues/15367
> Fix restarting a workspace from Che Theia in single-user mode

- plugins/containers-plugin/package.json
- plugins/ports-plugin/package.json
- plugins/ssh-plugin/package.json
- plugins/task-plugin/package.json
- plugins/welcome-plugin/package.json
- plugins/workspace-plugin/package.json
This changes proposal fix build of che-theia after upgrade yarn to version 1.19.1
The problem was occurred when user upgrades yarn to version 1.19.1. Plugins are using `@theia/plugin-packager` as a dependency to pack themselves to zip container. On 1.19.0 there isn't any problem, because `@theia/plugin-packager` dependency provides `theia:plugin` and `theia-plugin` binaries. But on 1.19.1 there is only `theia-plugin` binary.
https://github.com/eclipse/che/issues/15552
N/A
N/A
> Use correct binary for packaging plugin into zip container

- plugins/containers-plugin/package.json
- plugins/ports-plugin/package.json
- plugins/ssh-plugin/package.json
- plugins/task-plugin/package.json
- plugins/telemetry-plugin/package.json
- plugins/welcome-plugin/package.json
- plugins/workspace-plugin/package.json
Uses `theia-plugin` instead of `theia:plugin` in each `compile` phase.
Will fix eclipse/che#14145 eclipse/che#15552.
> Use theia-plugin instead of theia:plugin.

- generator/src/templates/assembly-package.mst
This changes proposal adds missing library `async-limiter` to fix ci-build PR task. This is a temporary solution to have successful ci-build in each PR.
https://github.com/eclipse/che/issues/15695
N/A
N/A
> Add missing dependency for async-limiter to fix ci-build

- build.include
- cico_build_master.sh
- cico_build_release.sh
This PR adds 2 required environment variables to the CI builds in order to restore the CDN support in `che-theia` image.
This support had been broken when migrating the CI to centos-ci. 
https://github.com/eclipse/che/issues/15791
> Add the required env vars to restore CDN Support

- cico_common.sh
This PR allows fetching a new environment variable, in `cico` CI build, to retrieve the Akamai auth environment variable required to push che-theia artifacts to the CDN.
This is a followup of PR https://github.com/eclipse/che-theia/pull/607
> Also fetch the CDN Auth variable from Jenkins env

- cico_build_master.sh
Avoid outputing (through the use of `set -x`) the environment variables that are injected by Jenkins.
This is important if they contain secrets or tokens.
This is a followup of PR https://github.com/eclipse/che-theia/pull/607
> Do not expose Jenkins env vars in console output

- che-theia-init-sources.yml
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-github-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-github.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- plugins/github-auth-plugin/.gitignore
- plugins/github-auth-plugin/README.md
- plugins/github-auth-plugin/package.json
- plugins/github-auth-plugin/src/github-auth-plugin.ts
- plugins/github-auth-plugin/tsconfig.json
- plugins/github-auth-plugin/tsfmt.json
- yarn.lock
Add a plugin that authenticates [vscode GitHub PR plugin](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github) launched in Che-Theia
The plugin calls Che oAuth API service to get the GitHub token. Then it injects it to the user preferences. When the browser page is refreshed the vscode GitHub PR plugin fetches the token and cleans the token from the preferences file.
This works only in single user Che. When https://github.com/eclipse/che/issues/15672 is applied the token could be fetched in the multi-user.
**What can be improved:**
The login actions that provided by the native vscode GitHub plugin are still redirect to the vscode authentication service. To override them we need:
1.  Apply `Urihandler` plugin API method: …
> Apply GitHub authentication plugin

- dockerfiles/theia/push-cdn-files-to-akamai.sh
This PR restores the use of the `AKAMAI_CHE_AUTH` as being a multi-line env variable, instead of being a file that contains the information. 
Related to issue https://github.com/eclipse/che/issues/15791
> Restore use of Akamai auth as a variable

- cico_common.sh
This is required to allow pushing CDN files to the CDN store.
This PR is a follow up of PR #607
> Add `jq` as a build dependency

- cico_common.sh
This PR adds the `epel-release` repo in order to be able to install `jq` as a build dependency
This PR is a followup of PR https://github.com/eclipse/che-theia/pull/614
> Add the `epel-release` repo for `jq`

- extensions/eclipse-che-theia-user-preferences/package.json
- extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-service.ts
- plugins/welcome-plugin/src/welcome-page.ts
- plugins/welcome-plugin/src/welcome-plugin.ts
This changes proposal add several fixes to the welcome page plugin. The main problem was related to the restoring opened editors after page reloading. Welcome page represents as a _WebView_ panel, that should be restored after plugin starting phase. But at workspace opening phase the plugin tried to open _WebView_ that is not consistent with the main bootstrap flow. Here is some fixes that performed in this PR:
- Add ability to serialize welcome page _WebView_ to be able to restore it.
- Reduced delay **from 1 to 0.1 second** when welcome page should be opened after workspace is started.
- Changed mechanism of restoring welcome page. **Now it opens in case when there isn't any opened other editors and there is enabled option in Theia Preferences.** 
**_Note that application state is …
> Serialize webview in welcome plugin to be able to restore it after page reload

- cico_build_master.sh
- cico_common.sh
During transition to ci.centos.org publishing of npm modules was lost.
This PR restore publishing.
> Restore publishing npm modules on each master build

- dockerfiles/theia/build.sh
- generator/src/scripts/override-vs-loader.js
This PR finally fixes the remaining issues with the broken CDN support:
- During the build, the CDN process should rename the zip of the monaco vs loader. This is required to also fix the CDN support of static artifacts that are related to the Monaco editor 
- Fix an inconsistency between the docker image label and the content of the `cdn.json` file inside the image. This fix also avoids building the `che-theia` twice, which will reduce the build time. 
eclipse/che#15791
> Fully fix the CDN support

- cico_build_master.sh
- cico_common.sh
Reverts the commit https://github.com/eclipse/che-theia/commit/67f85f761cccf47d555a2cf1b82fd121f3530894 that breaks the build of Che Theia.
> Revert 67f85f761cccf47d555a2cf1b82fd121f3530894 to fix a build

- generator/src/init.ts
- generator/src/yargs.ts
This changes proposal updates `prepare:build` section in `theia/package.json` after `che:theia init` command call from:
```
"prepare:build": "yarn build && run lint && run build \"@theia/example-*\" --stream --parallel",
```
to:
```
"prepare:build": "yarn build && run lint && lerna run build",
```
https://github.com/eclipse/che/issues/15932
N/A
N/A
> Update preview:build script section after call che:theia init

- dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile
- dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile
Rsync tool is needed to synchronize sources between /projects and /tmp directories to be able to build them in /tmp directory on che.openshift.io
> Add rsync tool to che-theia-dev container

- dockerfiles/theia/src/entrypoint.sh
This makes Theia listen on configurable hostname. This is taken advantage of in https://github.com/eclipse/che-plugin-registry/pull/378 which makes the Theia endpoint listen on localhost only to enable truly secure deployment.
eclipse/che#15651, eclipse/che#15890, https://github.com/eclipse/che-plugin-registry/pull/378
> Make theia hostname configurable

- RELEASE.md
This is the follow-up issue for the comment https://github.com/eclipse/che-theia/pull/599#discussion_r365720111
It updates the `RELEASE.md` file with the correct names for the release branch/tag. To match the other Che repositories.
> Update RELEASE.md to reflect the current branch/tags naming

- generator/src/templates/assembly-package.mst
Configure property `application.confirmExit` to `always` by default.
https://github.com/eclipse/che/issues/13580
N/A
N/A
> Configure application.confirmExit to always as default

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
- yarn.lock
Align 'configStorage' object to theia changes
https://github.com/eclipse/che/issues/16149
> Align 'configStorage' object to theia changes

- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
Add `terminal scroll` commands:
- scroll line up by shortcut: `Ctrl + Shift + ArrowUp`
- scroll line down by shortcut: `Ctrl + Shift + ArrowDown`
- scroll to top of the terminal(beginning line) by shortcut: `Home`
- scroll page up by shortcut `PageUp`
- scroll page down by shortcut `PageDown`
https://github.com/eclipse/che/issues/16151
> Add terminal scroll commands

- generator/src/templates/theiaPlugins.json
This PR adds in the vscode-builtin-php. I believe the reason we didn't originally add this was because of https://github.com/eclipse-theia/theia/issues/6672 but from playing around with and investigating the Theia code I don't think it's really an issue. Also, cpp and yaml (when you have vscode-yaml activated) both show these errors as well. This builtin is needed otherwise PHP highlighting and language features won't work in any of the PHP stacks.
To test use the PHP symphony devfile and add in:
```
- type: chePlugin
reference: >-
https://gist.githubusercontent.com/JPinkney/5cad64651e4f609f019be617d2098129/raw/ac7ad2ccc95ae743a57f4e9f285b1f69c287ec4f/meta.yaml
```
Then open up a PHP file and you should have highlighting, outline, etc working.
Signed-off-by: Josh Pinkney …
> Add in vscode-builtin-php

- extensions/eclipse-che-theia-terminal/package.json
- extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
- generator/tests/init-sources/assembly-example/configs/root-compilation.tsconfig.json
- yarn.lock
none.
https://github.com/eclipse/che/issues/16212
Fix terminal compilation after upstream changes: https://github.com/eclipse-theia/theia/pull/7121
> Adaptate terminal to the upstream

- extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.tsx
- extensions/eclipse-che-theia-about/src/browser/style/che-theia-about.css
Reworks About dialog with React according to the upstream changes
closes https://github.com/eclipse/che/issues/15962
> Rework About dialog with React according to the upstream changes

- generator/src/templates/theiaPlugins.json
Adds VS Code built-in themes.
It's a follow-up PR for the PR https://github.com/eclipse/che-theia/pull/656 which adapts Che Theia  styling to respect the VS Code theming approach.
Below is an example of Che Theia Plugins view with the different VS Code themes applied.
> Add VS Code built-in themes

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-oauth-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/oauth-utils.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-oauth.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- yarn.lock
Add `getProviders()` and `isAuthenticated()` oAuth methods to plugin API.
https://github.com/eclipse/che/issues/15261
> Add oAuth plugin API methods

- dockerfiles/theia/Dockerfile
- dockerfiles/theia/build.sh
Includes the latest version of `@theia/yeoman-plugin` to Che-Theia build.
https://github.com/eclipse/che/issues/16354
> Use the latest version of yeoman-plugin

- dockerfiles/theia/e2e/src/package.json
Fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-7598 reported by GitHub:
> Bump minimist from 1.2.0 to 1.2.5 to fix the vulnerability reported by GitHub

- extensions/eclipse-che-theia-plugin-ext/src/node/che-product-service.ts
- yarn.lock
Adds a mime-type autodetection of a product logo image when it's returned by [che-product-service](https://github.com/eclipse/che-theia/blob/master/extensions/eclipse-che-theia-plugin-ext/src/node/che-product-service.ts). A mime-type is set within base64 data url.
closes https://github.com/eclipse/che/issues/16392
> Autodetect a MIME-type of the logo for branding

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
- plugins/github-auth-plugin/package.json
- plugins/telemetry-plugin/package.json
- yarn.lock
Add unimplemented method
Fix https://github.com/eclipse/che/issues/16393
Change-Id: I22e1a15dae39153f1d3b5cf55b6a6f6d31711c17
> fix(deployment): Fix the plugin-remote init which is missing now a method

- yarn.lock
Update the `yarn.lock` to fetch the latest version of the `@eclipse-che/workspace-client` package from the npm registry.
https://github.com/eclipse/che/issues/16356
> Update the latest verion of the workspace-client package

- CONTRIBUTING.md
- devfiles/hosted-che-dogfooding.devfile.yaml
Devfile to develop che-theia on che.openshift.io
Considering to the disk space limitation for /projects directory, it's only possible to build che-theia inside /tmp directory, which has 3GB.
Sources are persisted in /projects directory, but copied and then built in /tmp/theia. 
The devfile has commands to
- copy (rsync) sources to /tmp/theia
- initialize che-theia
- build
- launch
No issue
> Devfile for che-theia dogfooding on che.openshift.io

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
upstream theia introduce a new required dependency in plugin-ext to EnvVariablesServer
Fix https://github.com/eclipse/che/issues/16412
Change-Id: Ia6f06ec4591b78e08263330b8c47457d04e3c2ab
> fix(plugin-remote): upstream theia is now requiring EnvVariables

- plugins/workspace-plugin/src/theia-commands.ts
Fixes import of zip project when it is hosted in the same cluster as Che and the cluster uses self-signed certificate.
> Fix import of zip project in case the archive is hosted on the same cluster which uses self-signed certificate

- set_theia_version.sh
When executing release script, we don't need to set version of `@eclipse-che/workspace-telemetry-client` as a releasing Che Theia version but leave it `latest` instead, since it's not a part of Che Theia repo.
closes https://github.com/eclipse/che/issues/16301
> Don't update @eclipse-che/workspace-telemetry-client version for release

- dockerfiles/theia-endpoint-runtime-binary/Dockerfile
- extensions/eclipse-che-theia-plugin-remote/package.json
- extensions/eclipse-che-theia-plugin-remote/src/browser/browser-remote-hosted-plugin-support.ts
- extensions/eclipse-che-theia-plugin-remote/src/browser/plugin-remote-frontend-module.ts
- extensions/eclipse-che-theia-plugin-remote/src/common/plugin-remote-rpc.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-host-custom.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-browser-impl.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-node-impl.ts
- yarn.lock
See plug-ins across containers
Also it handles:
- disallow automatic dependencies download from extension referencing other extensions
- proxify exports from one container to other containers
- make exports calls synchronous by using deasync library
- Handle function() parameters on root exported objects. In that case it's handled as callbacks. So the function will be called remotely when needed.
- make deasync module a nodejs module (by reusing a custom pre-assembly of nodejs so that the theia endpoint runtime can be statically compiled
- change plugin's host process to be able to customize the plug-in manager to handle remote containers
Can be tested with https://che.openshift.io/f/?url=https://gist.githubusercontent.com/benoitf/618ba31e7812a35f8f6569b94e1672e4/raw/f002e493bb5a465119aeee …
> feat(plugin-remote): Allow to see plug-ins running in other containers

- dockerfiles/theia/Dockerfile
Alternate fix of https://github.com/eclipse/che-theia/pull/669
fix permissions on *.sh scripts
bump as well vscode-git extension
Fix https://github.com/eclipse/che/issues/16084
Can be tried with http://che.openshift.io/f/?url=https://gist.githubusercontent.com/benoitf/b6f95a9c89e5083c7a30a8dd258fd1cb/raw/73e57a7ae648120d16346c3ae364d835641d86e9/git-devfile.yaml
Change-Id: Icfb72fab088cce07c3b0b55a16a25d8cb6e2cf8e
> fix(git): Add correct permissions for shell scripts like git

- generator/src/conf/.yarnclean
- generator/src/init.ts
- generator/src/production.ts
After upgrade `monaco` version in upstream `monaco-editor-core` comes from `theia`, not from `typefox`.
So, I think, we should update it for `che-theia`.
> Update monaco-editor-core dependency

- extensions/eclipse-che-theia-activity-tracker/src/node/activity-tracker-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- yarn.lock
Reworks activity-tracker extension to work with Che Server over TLS.
Instead of requesting Che API directly, activity-tracker extension will use [che-workspace-client](https://github.com/eclipse/che-workspace-client) which is already [configured in a proper way](https://github.com/eclipse/che-workspace-client/blob/7dfadc9105f9accd6917f5027f8ab81d01a7a072/src/index.ts#L55-L105).
closes https://github.com/eclipse/che/issues/15991
> Rework activity-tracker extension to work with Che Server over TLS

- generator/src/cdn/base.ts
This PR catches exceptions on synchronous HEAD requests used for CDN availability tests, and disable CDN in this case.
This is important to avoid breaking the editor when CDN URLs
fail with either timeout or browser-side errors
(DNS, CORS, etc ...)
This PR fixes issue https://github.com/eclipse/che/issues/15382
This would be important to include this fix in CRW 2.1, since we just enabled CDN support on CRW for the 2.1 release.
> Add robustness in CDN support,when CDN URLs trigger client-side errors (#15382 Fix)

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-view.tsx
Recently we found that `Plugins` view doesn't display any plugins: https://github.com/eclipse/che/issues/16452
As it turned out, we have two `Plugins` widgets:
- one comes from `Theia`
- we provide another one to display `Che` plugins
At the moment it's still possible to open both widgets, `View`-> `Open View` displays two `Plugins` items with the same label.
Please see the current behavior for `master` branch:
There is an issue to remove `Theia` `Plugins` widget and display `Che` `Plugins` view only: https://github.com/eclipse/che/issues/13670
I can see two approaches to resolve the issue:
- `che` widget extends `theia` widget and we can apply `rebind` (`PluginFrontendViewContribution` of `theia` by `ChePluginViewContribution`)
This …
> Do not display Plugins widget of Theia 

- extensions/eclipse-che-theia-plugin-remote/src/browser/plugin-remote-frontend-module.ts
I noticed that `BrowserRemoteHostedPluginSupport` is created a few times.
But it should be a singleton.
> Apply singleton scope for BrowserRemoteHostedPluginSupport

- dockerfiles/theia/README.md
- set_theia_version.sh
Fixes incorrect usage of `THEIA_GIT_REFS` env. variable.
`THEIA_GIT_REFS` env. variable is used for invalidating docker cache when upstream Theia has been changed.
But there're some places when the variable is used as if it relates to `eclipse/che-theia` repo.
> Fix incorrect usage of THEIA_GIT_REFS env. variable

- dockerfiles/theia/Dockerfile
disable linters when building theia image
linter has already been applied on yarn install step from the root level
Change-Id: I00f230202773ab7e01c1439046c60235dab93bb9
> feat(perf): disable linters of theia+che-theia when doing build of theia image

- .github/workflows/pr.yml
Introduce as experimental usage of github action for PR-build-check
It should be much more faster than ci.centos to perform the build check as we can use matrix jobs (and then build in parallel) and we don't need to setup the image/install software to run docker builds, etc.
if it works well, then we could switch to this check
N/A
Change-Id: I19f9db266294cd68e99a7d7c5b0e57ceaafae17a
> chore(github): Add GH action that allow to use parallel builds

- dockerfiles/theia/e2e/Dockerfile
- dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
- dockerfiles/theia/e2e/src/package.json
Enable `explorer/files` view
https://github.com/eclipse/che/issues/16611
Change-Id: I59459ce8dd933d8c2dc0c474a2d8d63d9a33ae31
> fix(e2e): Enable files view in the test

- dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile
- dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/runtime-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile
- dockerfiles/theia/docker/alpine/runtime-from.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
bump nodejs and alpine/ubi8 versions
Fix https://github.com/eclipse/che/issues/16599
Change-Id: Ic2499fe22dae84a7ce855f7a6cc8ab81005a2892
> fix(nodejs): bump nodejs and alpine/ubi8 versions

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Fixes running of plugin manager when the workspace is created from devfile like this
```
components: []
projects: []
metadata:
name: wksp-custom-m8zf
```
Solves issue https://github.com/eclipse/che/issues/16519
> Reanimates the plugin manager for workspace created from minimal devfile

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Cleanups the code, removes extra console output when Plugins view is reading the list ofplugins
no issue, just cleanup the code
> Remove unnecessary console output when loading a list of plugins

- .github/workflows/pr.yml
Cleanup github action node before running the build of theia
previous github actions are failing with 'no space left on device'
Change-Id: I1b5549dfe46ffca88f67595da1e6f22b84aa6e45
> chore(cleanup): Clean docker images before running the build

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/task-config-service.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- yarn.lock
Output for `vs code`/`theia` tasks is not displayed after changes in upstream.
The cause of the problem: a mechanism of creating terminal for a task was changed on `theia` side.
The current PR fixes the issue and allows to manage what kind of terminal widget is created for a task (theia terminal widget vs remote terminal widget)
https://github.com/eclipse/che/issues/16331
You can use the following devfile to test the changes 
<details>
```
metadata:
name: test-theia-tasks
projects:
- name: che-theia
source:
type: git
location: 'https://github.com/eclipse/che-theia.git'
- name: theia
source:
type: git
location: 'https://github.com/eclipse-theia/theia.git'
components:
- alias: che-dev
image: 'quay.io/eclipse/che-theia-dev:next' …
```
> Fix displaying output for vs code tasks

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia-dev/build.sh
tgz was containing timestamp + owner + group properties which was different at each run on different platform
thus tgz never got the same checksum and then it's always invalidate
with this change using --cache-from could help
https://github.com/eclipse/che/issues/16463
Change-Id: Ia3edc92cfeb932227dc603cd22e6dca89ec8ddc4
> feat(docker): Optimize the build to be able to reuse cache layering

- .github/workflows/pr.yml
- build.include
- build.sh
allow to provide yarn root options on build.sh: it's allowing us to skip lot of post-scripts from the first `yarn` call
When building the images we don't need to build all modules and to grab and build all native dependencies.
Then, add a new job to perform this check separately
one job to check full nodejs build of che-theia
two parallel jobs: one for alpine, one for ubi8
> allow to provide yarn root options on build.sh + new job in github action

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia/Dockerfile
When playing with multi-arch and theia I faced an issue with electron not being available on all platforms.
But as we don't need electron, let's remove all dependency from that.
https://github.com/eclipse/che/issues/16742
> feat(multi-arch): Avoid the usage of electron in our builds as electron is not available on all arch/platforms

- .github/workflows/pr.yml
- dockerfiles/build.include
Use --cache-from by default when building images
basically, theia-dev image shouldn't be rebuilt if there is no change in generator or in Dockerfile of theia-dev
https://github.com/eclipse/che/issues/16463
Change-Id: Iad02615369764934460406d978879bff863195f9
> chore(docker): Use --cache-from by default

- dockerfiles/theia/Dockerfile
When playing with multi-arch and Theia I faced a new issue on electron being still accessed.
Get rid of it.
https://github.com/eclipse/che/issues/16742
https://github.com/eclipse/che-theia/pull/726
Change-Id: I8610a31ba58ae2b9a3e8afc49e0c542f5b286c66
> fix(electron): really get rid of any electron dependency

- generator/tests/init-sources/init-sources.spec.ts
Fix test: on some environments, got not the full message error
On some env, the test is failing.
Change-Id: I80f6f06f46c1f25ae275ecdcf4b56b340ef41e79
> fix(generator): Fix test: on some environments, got not the full message error

- dockerfiles/theia/Dockerfile
- dockerfiles/theia/docker/alpine/build-result-from.dockerfile
- dockerfiles/theia/docker/ubi8/build-result-from.dockerfile
Use intermediate layer in the build so we can keep result of the build easily with `--target=build-result`
Change-Id: I0dc16416774553b724c3550d1c17e444ec4110ed
> feat(docker-image): Add intermediate layer with result of the che-theia build

- generator/tests/init-sources/init-sources.spec.ts
- generator/tests/init/init.spec.ts
- generator/tests/production/production.spec.ts
- plugins/workspace-plugin/tests/git.spec.ts
Increases timeout for some unit tests.
On some poor environments (like Core i5/8GB RAM), it is too short the default value (5000ms) 
None.
> Increase the value of timeout on unit tests.

- devfiles/che-theia-all.devfile.yaml
- devfiles/hosted-che-dogfooding.devfile.yaml
- devfiles/vscode-extensions.devfile.yaml
This changes proposal configures `cheEditor` component to ignore warnings when self-signed certificates are used.
When `cheEditor` component is used, it needs to be modified by adding additional environment variable:
```
- id: eclipse/che-theia/next
env:
- name: NODE_TLS_REJECT_UNAUTHORIZED
value: "0"
```
https://github.com/eclipse/che/issues/16604
N/A
N/A
> Ignore warnings when self-signed certificates are used

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
Fix stop working terminal widgets when user clicks on the exited task widget.
https://github.com/eclipse/che/issues/16601
> Fix stop working terminal widgets when user clicks on the exited task widget.

- dockerfiles/theia-endpoint-runtime-binary/Dockerfile
bump from 10.19.0 to 10.21.0
N/A
Change-Id: I4e5de0128752adff0bdd19b6789f463179b63fc6
> feat(endpoint): Bump endpoint to the same version of nodejs than the current theia image

- generator/package.json
- package.json
- plugins/ports-plugin/package.json
- plugins/ssh-plugin/package.json
- plugins/ssh-plugin/src/ssh-plugin-backend.ts
- yarn.lock
ssh plugin was using a nodejs 12.x api.
Remove it, ensure that node API is stuck to 10.x and switch from fs to fs-extra to avoid to use sync methods
Change-Id: Ia2a63363e532566e612c0ab3e6c9064f8c655163
> fix(requirements): stick to nodejs 10.0 api in plugin

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
Adds `get processInfo(): Promise<TerminalProcessInfo>` method to make it possible to run debug commands in internalTerminal.
Upstream changes: https://github.com/eclipse-theia/theia/commit/5e45d2b8ad4b27832c976aa406db03c561da9588#diff-29ae8bb3747051f34ef7d32716b705e6 
https://github.com/eclipse/che/issues/16805
> Adapt terminal widget to the upstream

- dockerfiles/theia/Dockerfile
Fix remaining electron file not removed so it tries to be compiled and failed
This is because new files have been introduced upstream
N/A
Change-Id: I9d1087e4e4288f31d7e367d36088084ff1486a9d
> fix(build): Due to new electron module, fix removal

- make-release.sh
1. Makes Che Theia release script working on macOS.
To verify, run the similar command but with your Che Theia fork:
`./make-release.sh --repo git@github.com:azatsarynnyy/che-theia --version 7.99.0 -t`
2. Makes Che Theia release script passing ShellCheck. Except for SC2086 as after applying it the script doesn't work right.
closes https://github.com/eclipse/che/issues/16653
closes https://github.com/eclipse/che/issues/16652
> Make Che Theia release script working on macOS

- dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
Temporary, disable one of the cypress tests which is not stable.
Sometimes, it requires to just rerun the CI job several times for passing the test.
For example:
https://ci.centos.org/job/devtools-che-theia-che-release/ - jobs 156, 157
https://ci.centos.org/job/devtools-che-theia-che-release/ - jobs 24, 25
As HappyPath tests are passing successfully, I propose to skip this test temporarily while investigating how to make it more stable.
> Temporary skip one of the cypress tests which is not stable

- generator/package.json
- package.json
- plugins/workspace-plugin/src/askpass-main.ts
- plugins/workspace-plugin/src/askpass.ts
- yarn.lock
Aligns TS version with upstream Theia.
Thanks @benoitf for the help in investigating the incompatibilities.
> Align TS version with upstream Theia

- make-release.sh
Fixes release script to set the latest Theia version when doing x.y.0 releases only.
But when doing other bugfix releases (e.g. x.y.1), Theia version must be the same as for corresponding y-release.
https://github.com/eclipse/che/issues/17188
> Fix release script to keep the same Theia versions for bugfix releases

- plugins/containers-plugin/src/containers-tree-data-provider.ts
- plugins/task-plugin/src/export/export-configs-manager.ts
- plugins/task-plugin/src/export/launch-configs-exporter.ts
- plugins/task-plugin/src/export/task-configs-exporter.ts
- plugins/workspace-plugin/src/theia-commands.ts
This PR fixes:
* Support Che tasks for multi-root workspaces https://github.com/eclipse/che/issues/15540
* Task: Changing a command in the devfile of an existing workspace is not taken in account https://github.com/eclipse/che/issues/13994
The approach is to not replicate tasks to tasks.json but instead contributing them to the "tasks" key of the user preferences.
Update: switched to replicating the tasks, but to the user level.
> 15540 user level tasks

- make-release.sh
Adds better detection when registry.npmjs.org doesn't return Theia version.
closes https://github.com/eclipse/che/issues/17181
> Better detection when registry.npmjs.org doesn't return Theia version

- make-release.sh
Fixes release script to prevent expanding `HOME` env. variable
closes https://github.com/eclipse/che/issues/17235
> Fix release script: don't expand HOME env. variable

- devfiles/che-theia-all.devfile.yaml
Removes linking `che-theia` to the existing `/projects/che-theia` while doing `che-theia init`, as yarn requires to pre-build whole `che-theia` sources before doing Theia sources build. Otherwise, we've got:
```
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run lint
lerna ERR! 
lerna ERR! Oops! Something went wrong! :(
lerna ERR! 
lerna ERR! ESLint: 6.8.0.
lerna ERR! 
lerna ERR! ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin".
```
fixes https://github.com/eclipse/che/issues/16413
> Don't use 'alias' for 'che-theia init' as it breaks the build

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-user-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-user.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
Add `getCurrentUser()` function for Plugin API. It is needed to get OpenShift cluster URL in hosted Che, see: https://www.eclipse.org/che/docs/che-7/hosted-che/#finding-the-cluster-where-the-hosted-che-workspace-is-running_hosted-che
https://github.com/eclipse/che/issues/16890
> Add getCurrentUser function for Plugin API

- .github/workflows/pr.yml
Allows GitHub Workflow to respect the build parameters provided in a PR's branch.
fixes https://github.com/eclipse/che/issues/17305
> GitHub Workflow should respect the build parameters provided in a PR's branch

- extensions/che-theia-hosted-plugin-manager-extension/package.json
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-terminal/package.json
- yarn.lock
This changes proposal freezes version for workspace-client from `latest` to latest tagged `0.0.1-1585913592`. To have smooth incoming changes that won't try to break anything after merge https://github.com/eclipse/che-workspace-client/pull/31, because https://github.com/eclipse/che-workspace-client/pull/31 is going to be merged among with upcoming changes in che-theia.
Needed for https://github.com/eclipse/che/issues/17246
N/A
N/A
> Freeze version of workspace-client library

- build.include
- generator/src/templates/assembly-package.mst
- generator/src/templates/theiaPlugins.json
Switches Che Theia to using VS Code built-in JSON extensions instead of JSON Theia Extension.
closes https://github.com/eclipse/che/issues/17319
> Adapt to upstream changes: @theia/json has gone

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
- plugins/task-plugin/src/machine/machine-exec-client.ts
- plugins/task-plugin/src/machine/websocket.ts
Fix issues related to losing connection to `machine exec`, for example, at running `che` tasks
(can be recognized by error message: `Request runTask failed with message: Failed to execute Che command: Connection is disposed.`)
image for testing goals: `rnikitenko/che-theia:keepExecConnectionMaster`
> Keep machine exec connection

- dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
Makes `Check Invalid Syntax` test stable.
closes https://github.com/eclipse/che/issues/17095
> Revert back disabled Cypress test

- dockerfiles/theia/src/entrypoint.sh
Use env variable that defines the root project to open in the right folder
Fixes https://github.com/eclipse/che/issues/17347
need to edit config map so can't be tested against che.openshift.io
edited with
```
CHE_WORKSPACE_PROJECTS_STORAGE: /home/florent
```
and here is the result with the devfile https://gist.githubusercontent.com/benoitf/6f2c761690646c930ea728e85054e43c/raw/620e0fca2911f62534007ca21769eee966ca9649/devfile-projects.yaml
Change-Id: I22d9567604de0cdac90df9ba5fc514ff833a2884
> fix(projects): Use correct default folder if set for root projects

- extensions/eclipse-che-theia-plugin-remote/src/common/plugin-remote-rpc.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-browser-impl.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-node-impl.ts
Handle more properties from the exports
also handle constants directly (as some plugin's are checking if the returned value is a string and not a function that might return a string)
Checked with https://che.openshift.io/f?url=https://gist.githubusercontent.com/benoitf/1fcff181b08448a96ee186bec3b5222f/raw/f4bbe2febfbd89a32dcfdf6eff470f674be7010c/devfile-16589.yaml
Part of https://github.com/eclipse/che/issues/16589
Change-Id: Icbb026f65577422168f1acab486e598c6146c170
> Handle more exported properties from remote plugins

- dockerfiles/theia/e2e/test.sh
- extensions/che-theia-hosted-plugin-manager-extension/package.json
- extensions/che-theia-hosted-plugin-manager-extension/src/node/che-workspace-hosted-plugin-uri-post-processor.ts
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-devfile-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-resolver.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-terminal/package.json
- extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts
- yarn.lock
This changes proposal adds an ability to call workspace service methods using user access token. Some of methods due to restriction, requires keycloak token, not machine's one.
https://github.com/eclipse/che/issues/17246
N/A
N/A
> Provide ability to call filtered workspace service methods using user token

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-node-impl.ts
Always send exports to all VS Code extensions/plug-ins even to those that are not depending on it.
To try
https://che.openshift.io/f/?url=https://gist.githubusercontent.com/benoitf/1fcff181b08448a96ee186bec3b5222f/raw/dab24da194d8b03b4a0491421ad6a86fd7ca7a8e/devfile-16589.yaml
In this case I used a non-modified vsix of sonarsource (https://gist.githubusercontent.com/benoitf/cd064f61e95be361cbb2274c9a30fb44/raw/33709849aa6512d02f364cc9b0e20da7d13f3866/sonarlint-1.16-meta.yaml)
Fixes https://github.com/eclipse/che/issues/17355
Change-Id: I512c81da4ff4a13d9a374415415c4b413e8c3e3c
> feat(plugin-remote): Automatically send the plugin's exports remotely even if extension is not depending on it

- che-theia-init-sources.yml
- dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
- extensions/eclipse-che-theia-workspace/.gitignore
- extensions/eclipse-che-theia-workspace/package.json
- extensions/eclipse-che-theia-workspace/src/browser/che-quick-open-workspace.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-contribution.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-module.ts
- extensions/eclipse-che-theia-workspace/tsconfig.json
This feature request provides an ability to switch to another Che workspace directly from Theia editor.
Go to `File` menu and choose `Open Recent Workspace...`
It will open workspace list, sorted by modification time:
Then developer will be notified if current workspace should be stopped:
https://github.com/eclipse/che/issues/17034
Show recent Che workspaces in Theia editor.
> Show recent Che workspaces in Theia editor

- extensions/eclipse-che-theia-messaging/src/node/messaging/che-messaging-contribution.ts
fix ws connection for single-host. It was failing on checking endpoint with origin uri paths. Reverse check works ok.
I still need to test it with default/multi-host.
https://github.com/eclipse/che/issues/17396
> Fix ws connection on single-host

- extensions/eclipse-che-theia-plugin-ext/src/browser/oauth-utils.ts
If the `getUserToken()` function works longer then 10 sec. warning notification about blocked oauth popup appears.
https://github.com/eclipse/che/issues/16930
> Add a warning about blocked oauth popup

- dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-quick-open-workspace.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-contribution.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-controller.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-module.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-utils.ts
This changes proposal adds an ability to stop current workspace directly from Che Theia.
_Existed command is going to be renamed in featured PR for the following issue: https://github.com/eclipse/che/issues/17106_
Use the following devfile:
```
metadata:
name: workspace
components:
- 
reference: >-
https://raw.githubusercontent.com/vzhukovskii/devfiles/master/meta.yaml
```
1. Go to File - Close Workspace:
2. Click Ok on popup dialog:
3. Workspace will be stopped and user will be redirected to Dashboard
https://github.com/eclipse/che/issues/17238
Stop workspace from Che Theia
> Stop workspace from Che Theia

- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
[waitForRemoteConnection](https://github.com/eclipse/che-theia/blob/2142853188913cf14bb8ee00beac767c2329c0ca/extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L46) is `defferred` object for `ReconnectingWebSocket`.
It's resolved when `websocket` [is open](https://github.com/eclipse/che-theia/blob/2142853188913cf14bb8ee00beac767c2329c0ca/extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts#L222).
But it should be resolved when `websocket` is reconnected as well.
Otherwise `websocket` can not be got from `defferred` object and leads to bugs.
The changes should fix issues related to remote terminal widget, for example when we send signal to terminate a process.
We have such issue for Code Ready Workspaces …
> Resolve remote connection for a terminal at reconnection

- extensions/eclipse-che-theia-workspace/src/browser/che-quick-open-workspace.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-contribution.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-controller.ts
This changes proposal adds ability to open Che workspace directly from Che-Theia. Also it modifies behavior of Open Recent Workspace command, so the last one simply displays the last five workspaces sorted by modification time and Open Workspace command displays all workspaces in user account.
_Existed command is going to be renamed in featured PR for the following issue: eclipse/che#17106_
All workspaces:
Recent workspaces:
Simply create a workspace from the following devfile:
```
metadata:
name: workspace
components:
- 
reference: >-
https://raw.githubusercontent.com/vzhukovskii/devfiles/master/meta.yaml
```
https://github.com/eclipse/che/issues/17237
> Open workspace from Che Theia

- CONTRIBUTING.md
Describes workflows for working with plugins in sidecar containers in detail.
https://github.com/eclipse/che/issues/13249
> Describe running and debugging plugins in sidecars

- yarn.lock
Signed-off-by: Kirk Crane <krcrane@ca.ibm.com>
bump vscode-ripgrep version to 1.8.0.  no s390x build of ripgrep-prebuilt for version 1.7.0
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error /home/theia-dev/theia-source-code/che-theia/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments:
Directory: /home/theia-dev/theia-source-code/che-theia/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-6
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-6
Deleting invalid download cache
Downloading ripgrep failed: Error: Asset not found with name: ripgrep-v11.0.1-6-s390x-unknown-linux-gnu.tar.gz
at getAssetFromGithubApi …
> bump vscode-ripgrep version.  no s390x build for version 1.7.0

- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-quick-open.ts
Open by default terminal in workspace root.
In case of multiple workspace roots, prompt user.
Fix https://github.com/eclipse/che/issues/17548
Change-Id: I8ad33cd6d85c5582c347bcc5390c25daacf825ef
> feat(terminal): Use workspace root as default path in containers

- make-release.sh
Pins npm libs versions when releasing.
fixes https://github.com/eclipse/che/issues/17612
> Pin npm libs versions when releasing

- package.json
- yarn.lock
Fixes [high severity CVE](https://github.com/advisories/GHSA-hxcc-f52p-wc94) in `serialize-javascript` reported by Dependabot.
> Fix serialize-javascript CVE

- make-release.sh
- updates release script to avoid upgrading npmjs dependencies' version when doing z-stream releases other than x.y.0.
- updates dependencies versions only when it's next/latest in master branch
closes https://github.com/eclipse/che/issues/17635
> Keep npmjs deps versions untouched when doing z-stream releases with z>0

- generator/src/cdn/html-template.ts
- generator/tests/cdn/html-template.spec.ts
Remove links to monaco html/css 
These links were removed by https://github.com/eclipse/che-theia/pull/793
but it's still in CDN configuration
Fixes https://github.com/eclipse/che/issues/17643
Change-Id: I69ad1eba4e428c4f9b59c504d77ece0fd8d665d4
> fix(generator): Remove links to monaco html/css 

- dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-contribution.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-controller.ts
This changes proposal reorganizes workspace related commands according to issue: https://github.com/eclipse/che/issues/17106
Signed-off-by: Vladyslav Zhukovskyi vzhukovs@redhat.com
https://github.com/eclipse/che/issues/17106
> Reorganize workspace related commands

- extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts
Uses CHE_API_INTERNAL instead of CHE_API_EXTERNAL.
As che-theia backend is behind of Ingress, it can be connected to the Che API server with the K8s DNS name.
None.
> Use CHE_API_INTERNAL instead of CHE_API_EXTERNAL.

- extensions/eclipse-che-theia-workspace/package.json
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-contribution.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-controller.ts
- extensions/eclipse-che-theia-workspace/tsconfig.json
This changes proposal adds an ability to export workspace's devfile from Theia editor to file system. 
Default Theia's command has moved from `Save Workspace...` to `Save Workspace Roots As...`. And `Save Workspace As...` now exports devfile from workspace configuration.
https://github.com/eclipse/che/issues/17239
> Add an ability to export devfile to file system

- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-https.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
- extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts
- plugins/task-plugin/src/machine/websocket.ts
- yarn.lock
This changes proposal adds an ability to provide custom certificates.
Custom certificates should be located in `/public-certs/*.crt`
https://github.com/eclipse/che/issues/17440
> Support custom public certificates

- extensions/che-theia-hosted-plugin-manager-extension/package.json
- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-https.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
- extensions/eclipse-che-theia-terminal/package.json
- extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts
- plugins/task-plugin/src/machine/websocket.ts
- yarn.lock
Back port of https://github.com/eclipse/che-theia/pull/824 for CRW 2.4
https://github.com/eclipse/che/issues/17440
> Add an ability to use custom public certificates

- generator/src/templates/assembly-package.mst
Disable `Enable Trash` property by default.
https://issues.redhat.com/browse/CRW-1129
N/A
N/A
> Disable using trash directory by default

- dockerfiles/theia/docker/alpine/runtime-install-dependencies.dockerfile
Installs `lsblk`.
It is required by getDrives() in Theia.
eclipse/che#17845
> Install `lsblk`.

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Signed-off-by: admin <admin@admin.com>
Disables using authority certificates when getting plugin list from custom plugin registry.
How to test:
- build and launch Che-Theia with changes from this PR
- open Plugins view, add registry (it could be https://raw.githubusercontent.com/vitaliy-guliy/che-theia-plugin-registry/master/plugins/plugins.json)
- after refreshing the view, scroll to bottom
Without this fix, new plugins will not appear in the list and Theia will trace the following
```
2020-07-30 13:01:29.028 root INFO Cannot access the registry Params: Error: unable to get local issuer certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
at TLSSocket.emit (events.js:315:20)
at TLSSocket._finishInit (_tls_wrap.js:936:8)
at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) …
```
> Do not use authority certificate for requests outside Che container

- plugins/welcome-plugin/src/welcome-plugin.ts
Disables saving the state of Welcome page.
Why do we need to do this:
- the plugin doesn't take into account that after reload the page, Theia restores all the views, including the previously opened Welcome page
- after restoring the state, links in the webview become not working
Depends on https://github.com/eclipse-theia/theia/pull/8473
- https://github.com/eclipse/che/issues/16352
- https://issues.redhat.com/browse/CRW-1029
> Do not store state of Welcome page

- che-theia-init-sources.yml
- extensions/eclipse-che-theia-filesystem/.gitignore
- extensions/eclipse-che-theia-filesystem/package.json
- extensions/eclipse-che-theia-filesystem/src/browser/che-filesystem-module.ts
- extensions/eclipse-che-theia-filesystem/tsconfig.json
- yarn.lock
This changes proposal rebinds default file overwrite dialog by adding an additional check for modification time bias.
The problem which this changes proposal fixes described in [followed comment](https://github.com/eclipse/che/issues/16751#issuecomment-692768138).
https://github.com/eclipse/che/issues/16751
N/A
N/A
> Rebind overwrite dialog by adding check for modification time bias

- plugins/welcome-plugin/src/welcome-plugin.ts
See eclipse/che#16563
Signed-off-by: Eric Williams <ericwill@redhat.com>
> Revert "Do not store state of Welcome page (#848)"

- dockerfiles/theia/e2e/test.sh
Mounts the directory `screenshots` to e2e testing container. 
Cypress generates screenshots when tests are failed. They are useful for trouble shooting.
None.
> [e2e] Mount the directory `screenshots`.

- extensions/eclipse-che-theia-preferences-provider-extension/src/browser/prefs-provider.ts
Interprets Theia preference values from devfiles as JSON values instead of strings.
Since I cannot build against a commit hash, I had to make this PR based on @RomanNikitenko 's PR that fixes build against Theia master. Please only look at the last commit when reviewing. 🤷 
Support object array preferences in a devfile https://github.com/eclipse/che/issues/17481
> 17481 general preference objects

- generator/src/templates/theiaPlugins.json
Update the vscode Git extension from 1.44.2 to 1.49.3
> Update the vscode Git extension from 1.44.2 to 1.49.3

- generator/src/templates/theiaPlugins.json
- plugins/github-auth-plugin/src/github-auth-plugin.ts
* Add vscode github built-in plugin as a default plugin.
* Always register the github authentication provider (removed the condition of the GitHub Pull Request plugin presence).
fixes https://github.com/eclipse/che/issues/18101
> Add vscode github built-in plugin as a default plugin

- extensions/eclipse-che-theia-remote-api/package.json
Fixes publishing the modules to npmjs.org
> Fix publishing to npmjs

- extensions/eclipse-che-theia-cli-endpoint/src/node/default-cli-endpoint.ts
Fix expected behaviour of the interface which is about URI, not a file path
N/A
Change-Id: Ia3f0305ab262619f0d602e810aea14cf6d7bc586
> fix(cli-endpoint): Make the implementation compliant with interface

- generator/src/templates/theiaPlugins.json
Updates Java builtin plugin to 1.50.1 version
https://github.com/eclipse/che/issues/18170
> Update java builtin plugin to 1.50.1 version

- .github/PULL_REQUEST_TEMPLATE.md
Include new PR template
https://github.com/eclipse/che/issues/17486
Change-Id: I5ec2b81a99197719822ee88e4dca6d176bf45d37
> chore(github): Add new PR template

- extensions/eclipse-che-theia-plugin-remote/src/node/languages-container-aware.ts
Fixes a wrong override of a method in `LanguagesContainerAware`.
https://github.com/eclipse/che/issues/18175
n/a
n/a
> Fix "goto definition"

- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-module.ts
- extensions/eclipse-che-theia-workspace/src/browser/explorer-contribution.ts
- plugins/welcome-plugin/package.json
- plugins/welcome-plugin/src/welcome-plugin.ts
- plugins/workspace-plugin/src/workspace-plugin.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
This PR adds a couple of UX enhancements to a new user flow:
- each time when a new Workspace started, Project Explorer is opened automatically
- fixed opening `README.md` file - Che Theia starts looking for a file only after finishing cloning the project's sources
- project folder that contains a `README.md` file is auto-expanded
closes https://github.com/eclipse/che/issues/17969
> Open Explorer on start

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Adds missing initialization of `certificateService`.
Looks like it was missed after one of the latest refactorings https://github.com/eclipse/che-theia/pull/867
fixes https://github.com/eclipse/che/issues/18211
1. Go to View -> Plugins
2. Make sure the Plug-ins list contains Che Plug-ins from the Plug-in Registry.
> Add missing initialization of certificateService

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-workspace-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-workspace.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
Allow to restart a workspace from plugin API
```typescript
che.workspace.restartWorkspace(RestartWorkspaceOptions)
```
```typescript
interface RestartWorkspaceOptions: {
prompt?: boolean;
promptMessage? : string;
}
```
N/A
I'm providing a custom plug-in:
https://github.com/benoitf/restart-workspace-plugin
and a custom devfile with plug-in included + custom theia available:
http://che.openshift.io/f?url=https://gist.githubusercontent.com/benoitf/f211270d3b5dbfcfb8c18e0709b13f31/raw/bf4568f393d36c1ccee50fcfe9e2519c9c7bbdec/devfile-restart-workspace.yaml
Bring the command palette and search for `restart`
Reviewers, please comment how you …
> feat(plugin-api): Allow to restart a workspace using @eclipse-che/plugin

- generator/src/init-sources.ts
After building your che-theia, you may notify that `generator/tests/init-sources/assembly-example/configs/root-compilation.tsconfig.json` file does not have new line character at the end.
It's because the file is being overwritten by https://github.com/eclipse/che-theia/blob/master/generator/src/init-sources.ts#L120, without adding new-line character at the end.
The solution is to add `'\n'` at the end of the file content.
- clone che-theia
- run `yarn` to build
- run `git status`
> Add new-line character at the end of JSON

- generator/src/templates/theiaPlugins.json
The PR proposes to exclude EditorConfig VS Code extension from Che Theia's built-in list by two main reasons:
- it is not a built-in VS Code extension, see the [README.md](https://github.com/microsoft/vscode-editorconfig#editor-config-for-visual-studio-code) in the archived repo
- the default behavior is confusing in some cases, see https://github.com/eclipse/che/issues/18096 and https://github.com/eclipse/che/issues/16194
fixes https://github.com/eclipse/che/issues/18096
fixes https://github.com/eclipse/che/issues/16194
1. Create a Workspace from `Java Spring Boot` stack.
2. Open `PetClinicApplication.java` file.
3. Set cursor to position Ln 32, Col 65 and hit Enter.
4. Cursor should go to position Ln 33, Col 9.
5. When the changes …
> Exclude EditorConfig VS Code extension from Che Theia's built-in list

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-resolver.ts
The changes allow to resolve input variables for `che` tasks
https://github.com/eclipse/che/issues/16264
You can use the following devfile for testing:
<details>
```
metadata:
name: java-maven-bfvoz
projects:
- name: console-java-simple
source:
location: 'https://github.com/che-samples/console-java-simple.git'
type: git
branch: java1.11
components:
- id: redhat/java/latest
preferences:
java.server.launchMode: Standard
reference: 'https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml'
- mountSources: true
memoryLimit: 512Mi
volumes:
- name: m2
containerPath: /home/user/.m2 …
```
> Support 'inputs' for che tasks

- plugins/ssh-plugin/src/ssh-plugin-backend.ts
Add exact match to SSH key name validation regexp.
fixes https://github.com/eclipse/che/issues/18229
1. Run `SSH create key pair for particular host...` command.
2. Enter `https://github.com` to the quick input.
3. See: Invalid input alert:
4. Enter `github.com` to the quick input.
5. See: key pair successfully created.
> Add exact match to SSH key name validation regexp

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-github-main.ts
Use GitHub Authorisation header in GitHub HTTP requests instead of token in query parameter. 
https://github.com/eclipse/che/issues/16425
1. Setup [GitHub Identity provider](https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-github-oauth/)
2. Start a workspace with GitHub Pull Requests plugin and a project cloned from GitHub by `https` url.
You can use this devfile to start a workspace:
```
metadata:
name: wksp-custom-dwdiu
projects:
- name: che-theia
source:
location: 'https://github.com/eclipse/che-theia.git'
type: git
branch: master
components:
- type: chePlugin
reference: 'https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/ms-vscode/vscode-github-pullrequest/0.20.0/meta.yaml'
reference: …
```
> Authorize GitHub requests with header instead of query parameter

- .github/workflows/pr.yml
- .github/workflows/publish-built-in-extension-report.yaml
use a fixed version for ubuntu instead of an alias
Github PR checks should be green as it's only related to github action checks
> chore(github-action): stick ubuntu to a specific version instead of latest

- dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile
- dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/Dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-nexe-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/runtime-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-nexe-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile
- dockerfiles/theia/docker/alpine/build-result-from.dockerfile
- dockerfiles/theia/docker/alpine/runtime-from.dockerfile
- dockerfiles/theia/docker/ubi8/build-result-from.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Latest version that we can build/use with nexe
It also includes enableNodeCli compilation option in prebuilt binary allowing to pass fork options (used in typescript VS Code extension)
updates ubi8 images as well to 12.18.4
```
$ docker run --rm -it --entrypoint=sh registry.access.redhat.com/ubi8/nodejs-12:1-64
$ node --version
v12.18.4
```
https://github.com/eclipse/che/issues/16186
Use remote sidecar containers with plug-ins running in sidecars
> feat(nodejs): Update to nodejs 12.8.4

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-webview-environment.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-server-common.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts
Adapts WebView to Che in single-host mode. See more details in https://github.com/eclipse/che/issues/17694
It binds Express middleware handler for serving `/webview` endpoint
to the exposed by Che webview-endpoint's hostname
instead of webview-endpoint's url.
WebView is loaded correctly in single-host mode.
Closes upstream https://github.com/eclipse/che/issues/17694 + downstream https://issues.redhat.com/browse/CRW-1336
1. Deploy Che in single host mode
`chectl server:deploy --platform=minikube --installer=operator --che-operator-cr-patch-yaml=patch.yaml`
where `patch.yaml` content is
```yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
name: eclipse-che
spec:
server:
serverExposureStrategy: 'single-host'
k8s: …
```
> Adapt WebView to Che in single-host mode

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-webview-environment.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts
It contains only required changes from https://github.com/eclipse/che-theia/pull/932 in order to fix WebView loading in Che 7.20.x
It's needed for downstream release https://issues.redhat.com/browse/CRW-1393
> Adapt WebView to Che in single-host mode (for 7.20.x)

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Use internal network url for plugin registry.
https://github.com/eclipse/che/issues/17644
Yes:
https://github.com/eclipse/che-operator/pull/468 and also: https://github.com/eclipse/che/pull/17945
none yet...
> Use internal network url for plugin registry.

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-webview-environment.ts
It fixes an incorrect pathname in a WebView endpoint URL.
When Theia/WebView Che endpoint URL contains pathname,
e.g. `https://192.168.99.237.nip.io/server9u2gtltn-jwtproxy/webviews`
Che Theia forms an incorrect URL for fetching WebView content,
like `https://192.168.99.237.nip.io/server9u2gtltn-jwtproxy/server-4402/webview/`.
The last one is actually an URL for Theia endpoint but not for WebView endpoint.
It works well as both URLs are forward to the same internal container and port, but it may cause problems in the future.
The problem comes from the upstream [`WebviewEnvironment`](https://github.com/eclipse-theia/theia/blob/055175566b279cded090f634c6672d17e067f904/packages/plugin-ext/src/main/browser/webview/webview-environment.ts#L5 …
> Fix an incorrect pathname in a WebView endpoint URL

- CONTRIBUTING.md
- README.md
- RELEASE.md
- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia-dev/build.sh
- dockerfiles/theia/README.md
- dockerfiles/theia/src/entrypoint.sh
- extensions/eclipse-che-theia-about/scripts/generate-about-details.js
- extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts
- extensions/eclipse-che-theia-plugin-remote/devfile.yaml
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts
- generator/README.md
- make-release.sh
- plugins/workspace-plugin/README.md
Makes Che-Theia spelling consistent with the rest of the docs. By request of the docs team.
Thanks @MichalMaler for noticing that.
> Make Che-Theia spelling consistent with the docs

- extensions/eclipse-che-theia-plugin-remote/src/node/hosted-plugin-process-log.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote.ts
The PR does two things:
1. Instead of statically requiring `che-plugin-api-provider.js`, which is the code that contributes the back-end ext-api provider, it requires the file that needs to be loaded in the plugin host process: `che-api-node-provider`. Also, since this is only to make nexe include the file in the executable, it does not really matter whether it's required in a container module or not. So just moved it to the main process file
2. Stdout/stderr from the plugin host process is now mirrored to the console of the process that starts it (either the theia plugin host or the remote plugin host process running in the sidecars). This allows us to detect errors more simply and also in cases where we can't properly start the "output" view in Theia.
Plugin host throws exception at …
> Directly reference che api setup module

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-telemetry-main.ts
- plugins/telemetry-plugin/src/telemetry-plugin.ts
1. Fixes `/client-ip` service URL for a single-host mode.
2. When sending the telemetry events about an editor usage, filters out the messages that come from the output channels, like `hosted-instance-log`. As such messages are recognized as `vscode.TextDocumentChangeEvent`s.
See the details in https://github.com/eclipse/che/issues/18598
closes https://github.com/eclipse/che/issues/18503
closes https://github.com/eclipse/che/issues/18489
1. Deploy Che in single host mode
`chectl server:deploy --platform=minikube --installer=operator --che-operator-cr-patch-yaml=patch.yaml`
where `patch.yaml` content is
```yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
name: eclipse-che
spec:
server:
serverExposureStrategy: …
```
> Adapt Telemetry Plug-in API to a single-host mode

- extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts
This changes proposal adapts Che-Theia to upstream changes.
Upstream commit https://github.com/eclipse-theia/theia/commit/143f589a2183adb469301612775773f2ad776723 brings changes that prevent normal workspace start. In upstream, PluginApiContribution now doesn't have usage of connect library, and as far as we extend this class and rebind it on Che-Theia side [PluginApiContributionIntercepted](https://github.com/eclipse/che-theia/blob/8f0d22e7b141b696af70b924dd48c85117daf052/extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts#L28) needs to be aligned to upstream class.
N/A
https://github.com/eclipse/che/issues/18618
N/A
[As the author of this Pull Request I made sure …
> Use express library instead redundant connect

- extensions/eclipse-che-theia-remote-api/src/browser/oauth-utils.ts
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
Use CHE_API_EXTERNAL for OauthUtils
PullRequest plugin doesn't work
> Use CHE_API_EXTERNAL for OauthUtils

- extensions/eclipse-che-theia-mini-browser/package.json
Add SKIP_ parameters on new modules since https://github.com/eclipse/che-theia/pull/944 was issued
I merged the PR but not all modules had the SKIP_ flags
https://github.com/eclipse/che-theia/pull/944
Use SKIP_* set to true and it should do formatter or tests or linter on mini-browser module
Change-Id: Ic065dda880d0768114fb2a62f9f243c7bee31373
> chore(skip): This module was not there when PR was made so it was not handling SKIP_* parameters

- extensions/eclipse-che-theia-plugin-ext/package.json
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-file-system-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-file-system.ts
- yarn.lock
This changes proposal adds a registration for sidecar file scheme: `file-sidecar-${machineName}`. As the first iteration across [dependent issue #16870](https://github.com/eclipse/che/issues/16870) only two methods from file system have been implemented: `stat` and `readFile`.
This changes doesn't provide any UI feedback. Just internal feature.
https://github.com/eclipse/che/issues/18405
Here is the devfile for the workspace, based on this PR:
```yaml
metadata:
name: che-18405
components:
- memoryLimit: 256Mi
reference: 'https://gist.githubusercontent.com/vzhukovs/29fccda72fbbd63e0c8aa8f751c9745a/raw/713d0b9ab47576ddb25c5a1a423346dd8f645268/meta.yaml'
- memoryLimit: 1024Mi …
```
> Implement simple side car file system which fetches file content

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/webviews-content-aware.ts
This changes proposal adds an ability to run extension that provides webviews in dedicate container. The problem was in resource loading mechanism, that didn't support resource loading by file service from remote containers. This changes proposal modifies webview creation step by providing custom scheme: `file-sidecar-${machineName}` instead of default `file` for `vscode-resource` or `theia-resource` resources.
Depends on: 
- https://github.com/eclipse/che-theia/pull/946 
- https://github.com/eclipse-theia/theia/pull/8832
- https://github.com/eclipse-theia/theia/pull/8833
Provided steps to test.
https://github.com/eclipse/che/issues/16870
1. Create workspace from [workspace.yaml](https://gist.githubusercontent.com/vzhukovs/7eba298a5 …
> Support webview in dedicate container

- plugins/workspace-plugin/src/ca-bundle.ts
- plugins/workspace-plugin/src/ca-cert.ts
- plugins/workspace-plugin/src/theia-commands.ts
- creates ca-bundle in `/tmp` containing '/tmp/che/secret/ca.crt' and all available certificates from '/public-certs'
- uses that bundle when downloading ZIP projects with `curl`
https://github.com/eclipse/che/issues/18654
1. generate new public and private certificates, setup somewhere https server
if you want to test this PR on local minikube deployment, you can setup https server on your local machine
2. add public certificate to Che
```
kubectl create configmap custom-certs --from-file=/home/vitaliy/tmp/ca-bundle.crt -n=che
kubectl label configmap custom-certs app.kubernetes.io/part-of=che.eclipse.org app.kubernetes.io/component=ca-bundle -n che
```
3. Take the devfile for this PR
- remove all commands and components, but leave …
> Use CA bundle when cloning ZIP projects

- .github/workflows/check-theia-branch.yml
While learning GitHub Workflows, I came up with the idea of adding a simple workflow for testing Che-Theia image build against a Theia branch.
Usually, we do it by running a build locally or opening a draft PR in Che-Theia. With the proposed workflow, it will be much quicker and easier.
> Add a GitHub Workflow for testing Che-Theia build against a Theia branch

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote.ts
Fixes error handling in the plugin host process
https://github.com/eclipse/che/issues/17601
> Handle case where err is not defined

- generator/src/templates/theiaPlugins.json
Downgrades `vscode-builtin-markdown-language-features` built-in plug-in to 1.39.1.
As 1.45.1 requires not implemented yet CustomEditor Plug-in API.
fixes https://github.com/eclipse/che/issues/18954
> Downgrade `vscode-builtin-markdown-language-features` built-in plug-in to 1.39.1

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-github-main.ts
- extensions/eclipse-che-theia-remote-api/src/browser/oauth-utils.ts
- plugins/github-auth-plugin/src/github-auth-plugin.ts
* If GitHub oauth is not set-up, show a notification with a link to a guide how to set-up GitHub identity provider in keycloak in Che docs page.
* Fix authentication mechanism (if Che user token is expired, retrieve it again), little refactoring.
fixes https://github.com/eclipse/che/issues/18237
1. Run Che with `quay.io/eclipse/che-server:nightly` image. It contains the [authentication fix](https://github.com/eclipse/che/pull/18815)
2. Create and open a workspace from dev-file:
```
metadata:
name: testnjz3q
components:
reference: 'https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-969/che_theia_meta.yaml'
- id: github/vscode-pull-request-github/latest
projects:
- name: environment-variable
source:
location: …
```
> Add docs notification if GitHub oAuth is not setup

- generator/src/templates/theiaPlugins.json
Removeі 'vscode-builtin-markdown-language-features' until [open-vsx issue](https://github.com/eclipse-theia/vscode-builtin-extensions/issues/41) is fixed.
> Remove vscode-builtin-markdown-language-features until open-vsx issue is fixed

- build.include
Specifies `REGISTRY` when pushing `SHORT_SHA`-image.
As by default it's - `The push refers to repository [docker.io/eclipse/che-theia-dev]`
https://github.com/eclipse/che/issues/18407
> Specify REGISTRY when pushing SHORT_SHA-image

- cico_common.sh
Adds publishing a `sha`-based image from the centos CI.
It was added by https://github.com/eclipse/che-theia/pull/978, but the other script is used on centos CI .
https://github.com/eclipse/che/issues/18931
> Publish the sha-based images from the centos CI

- .github/workflows/build-publish-next.yml
Use branch name instead of alias in the workflow.
With the placeholder `$default-branch` the workflow isn't triggered for some reason.
> Use branch name instead of alias in the Workflow

- .github/workflows/build-publish-next.yml
Updates the build-next-image workflow to build only the alpine-based image as the ubi-based build is already checking within the PR check.
https://github.com/eclipse/che/issues/18407
> Build only alpine image within the build-next workflow

- .github/workflows/check-theia-branch.yml
- build.include
- dockerfiles/theia/Dockerfile
Adds a command-line argument for passing an upstream Theia repository for building a Che-Theia image.
It would allow checking Che-Theia build against some Theia patch without changing Che-Theia sources.
> Make it possible to provide an upstream Theia repository through a command-line argument for building Che-Theia image

- .github/workflows/happy-path-tests.yaml
Allow to differentiate jobs executed as part of matrix jobs
Without that extra info, all artifacts have the same name (as there is no clue on how to upload artifacts with different name)
just look at happy path github action artifacts (it should be suffixed by extra information now) 
instead of having last job win
Change-Id: Ifdf8f74eb401ef124b4a73a99e1fd325818e187d
> chore(happypath): Add extra information to jobs so it can append suffix when uploading artifacts

- generator/src/templates/assembly-package.mst
Fix syntax highlighting when semantic highlighting is available. Will reconsider re-enabling it once we fix this: https://github.com/eclipse-theia/theia/issues/9058
PR alternative#2 for https://github.com/eclipse/che/issues/18448
1. Start a workspace with Java/maven devfile provided https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-993/simple/che-theia-maven-devfile.yaml
2. Open a java file
3. Wait for language server to be activated
4. The syntax highlighting is OK
> fix(java-highlighting): disabling semantic highlighting

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
- extensions/eclipse-che-theia-preferences-provider-extension/package.json
- extensions/eclipse-che-theia-remote-impl-che-server/package.json
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-endpoint-service-impl.spec.ts
Ensure type assertion is valid in code or we can skip it in tests
Issue reported by a comment in PR https://github.com/eclipse/che-theia/pull/989#issuecomment-780460831
update che-theia-init-sources.yaml to use checkout to `enable-tests`
clone theia and run theia init inside, launch build
Change-Id: I295b8dfcb3c8f483b8fb6b1ed205ecf133494824
> fix(tests): Ensure no-unnecessary-type-assertion

- extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
It was not possible to display plugins icons after reworking the plugin registry and keeping the icons inside the registry.
This PR provides fixes when forming icons URIs.
https://github.com/eclipse/che/issues/18908
- Use devfile, built for Happy Path tests
- Use devfile with prebuilt Che-Theia
```
---
metadata:
generateName: plugin-icons-
projects:
-
name: greeting-extension
source:
type: git
location: "https://github.com/vitaliy-guliy/greeting-extension.git"
components:
reference: https://gist.githubusercontent.com/vitaliy-guliy/c4bba3c297dd60c95f082d483742c27e/raw/4f3efad2b6626f67191ae68a3fde8f462ac07a15/meta.yaml
memoryLimit: 2G
```
[As the author of this Pull Request I made sure …
> Use plugin registry public URI for icons

- .github/workflows/pr.yml
- README.md
Provides an ability to generate test coverage report and upload it to https://codecov.io/gh
fixes https://github.com/eclipse/che/issues/18844
There should be two new Github Actions that perform test coverage report generation.
> Add Github action for test coverage

- che-theia-init-sources.yml
- plugins/ext-plugin/.gitignore
- plugins/ext-plugin/README.md
- plugins/ext-plugin/__mocks__/@eclipse-che/plugin.ts
- plugins/ext-plugin/package.json
- plugins/ext-plugin/src/ext-plugin.ts
- plugins/ext-plugin/tests/ext-plugin.spec.ts
- plugins/ext-plugin/tsconfig.json
Export `@eclipse-che/plugin` namespace through export of VS Code extension export API
clients could lookup getExtension('@eclipse-che.ext-plugin') to grab this namespace
https://user-images.githubusercontent.com/436777/108041370-b6145080-703e-11eb-812c-80e6db56441b.mp4
https://github.com/eclipse/che/issues/18837
Write an example using getExtension('@eclipse-che/ext-plugin') and then for example grab workspace details.
I've created a vscode extension doing this job
```typescript
const eclipseCheExtPlugin = vscode.extensions.getExtension('@eclipse-che.ext-plugin');
if (eclipseCheExtPlugin) {
// grab user
const user = await eclipseCheExtPlugin.exports.user.getCurrentUser();
vscode.window.showInformationMessage(`Eclipse Che user information: id ${user.id} with name ${user.name}`);
} else { …
```
> feat(namespace): Export @eclipse-che/plugin namespace using VS Code extension mechanism

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-service-client.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Refresh the plugins view when a new plugin registry is added in the settings.json.
If the new plugin registry is not valid, show a notification about it.
* Refresh the `plugins` view when a new plugin registry is added in the `settings.json`.
* If the new plugin registry is not valid, show a notification about it.
https://issues.redhat.com/browse/CRW-1449
fixes https://github.com/eclipse/che/issues/17263
1. Open a workspace from devfile:
```
metadata:
name: testnjz3q
components:
reference: 'https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1002/che_theia_meta.yaml'
- id: github/vscode-pull-request-github/latest
```
2. Open `Plugins` view.
3. Open `settings.json` file in the `.theia` directory in the user …
> Validate plugin registry in settings.json (#1002)

- extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Backport of https://github.com/eclipse/che-theia/pull/997 to 7.26.x
Changes the URIs of icoins to be able to be properly displayed in Plugins panel.
For details see https://github.com/eclipse/che-theia/pull/997
https://github.com/eclipse/che/issues/18908
> Backport: Use plugin registry public URI for icons

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-debug-configuration-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
- extensions/eclipse-che-theia-workspace/package.json
- extensions/eclipse-che-theia-workspace/src/browser/che-navigator-widget.tsx
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-module.ts
- extensions/eclipse-che-theia-workspace/src/node/che-workspace-server.ts
- extensions/eclipse-che-theia-workspace/src/node/index.ts
- extensions/eclipse-che-theia-workspace/src/node/workspace-backend-module.ts
- plugins/task-plugin/package.json
- plugins/task-plugin/src/che-task-backend-module.ts
- plugins/task-plugin/src/export/export-configs-manager.ts
- plugins/task-plugin/src/export/launch-configs-exporter.ts
- plugins/task-plugin/src/export/task-configs-exporter.ts
- plugins/task-plugin/src/extract/config-file-launch-configs-extractor.ts
- plugins/task-plugin/src/extract/config-file-task-configs-extractor.ts
- plugins/task-plugin/src/task-plugin-backend.ts
- plugins/task-plugin/src/utils.ts
- plugins/welcome-plugin/src/welcome-plugin.ts
- plugins/workspace-plugin/src/theia-commands.ts
- plugins/workspace-plugin/src/workspace-folder-updater.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
Handle multiple workspace roots
Checks if there is a che.theia-workspace file.
if there is one, returns that file as being a workspace root
if none, generate the file by getting all clonedPath/path of the devfile projects
enhancements:
I think we could resolve those items ^^ in a separate issue: by default a workspace starts in `OFF` multi-root mode - so no breaking changes for the `master` branch
The current state of the PR - a workspace starts in `OFF` multi-root mode - so the behavior should be exactly as for `master` branch.
A user should add the following section to a `devfile` to turn on multi-root mode:
```
attributes:
multiRoot: 'on'
```
Please let me know if you have a better idea for the attribute and value as marker for multi-root mode - it's easy to change on the current step. …
> Open Che workspace with multiple workspace root

- plugins/workspace-plugin/src/theia-commands.ts
Removes redundant delay in workspace plugin.
No issue, just code cleanup.
Devfile to test
```
---
metadata:
generateName: clone-ssh-
projects:
-
name: greeting-extension
source:
type: git
location: "git@github.com:vitaliy-guliy/greeting-extension.git"
-
name: atlascode
source:
type: git
location: "git@bitbucket.org:atlassianlabs/atlascode.git"
components:
reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1006/che_theia_meta.yaml
memoryLimit: 2G
```
Reviewers, please comment how you tested the PR …
> Remove unnecessary delay in workspace plugin

- plugins/ports-plugin/package.json
package @eclipse-che/plugin is inside the current yarn workspace, then it's this version that should be used instead of the remote one.
May lead to not having the correct API when building the plug-in.
Modify .d.ts of `@eclipse-che/plugin` and try to use that in ports-plugin: it will fail without this fix.
Change-Id: I8b0d5b30a2f11f891faa613488459bbe5fcb1576
> fix(package.json): Should use the yarn workspace version of @eclipse-che/plugin

- codecov.yml
Disable codecov github annotations
https://github.com/eclipse/che/issues/19176
Should not see any github codecov annotations in diff
Change-Id: I046c41c5d32758d49835d98d44381c657cf9a2d1
> feat(codecov): Disable annotations by default in github pull request

- plugins/workspace-plugin/src/workspace-folder-updater.ts
- plugins/workspace-plugin/tests/workspace-folder-updater.spec.ts
Add tests for 'WorkspaceFolderUpdater'
It's related to multi-root workspaces support logic https://github.com/eclipse/che/issues/17212
The tests should be happy.
> Add tests for 'WorkspaceFolderUpdater'

- plugins/resource-monitor-plugin/__mocks__/@eclipse-che/plugin.ts
- plugins/resource-monitor-plugin/src/resource-monitor-plugin.ts
- plugins/resource-monitor-plugin/tests/resource-monitor.spec.ts
Switch API call to get devfile attributes.
https://github.com/eclipse/che/issues/19188
Should work as before for the resource monitor plug-in
Change-Id: Ia532b973e081ae9801cd28008521bd07db9411fa
> feat(resource-monitor-plugin): Update to latest devfile 2 API

- plugins/workspace-plugin/src/ca-cert.ts
Fixes downloading of zipped projects when creating a workspace.
Now the default system certificate is used when downloading zip with curl.
https://github.com/eclipse/che/issues/19120
Devfile
```
---
metadata:
name: test-import-zip
projects:
-
name: theia-master
source:
type: zip
location: "https://github.com/eclipse-theia/theia/archive/master.zip"
components:
reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1014/che_theia_meta.yaml
memoryLimit: 1G
```
Reviewers, please comment how you tested …
> Apply default certificate when downloading ZIP projects

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-endpoint-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-endpoint.ts
- extensions/eclipse-che-theia-plugin-ext/tests/plugin/che-api.spec.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
Endpoint service was available to extensions but not to plug-ins
Add support for plug-ins
https://github.com/eclipse/che/issues/18874
Add a plug-in using this extension 
FYI I have an example in this PR: https://github.com/eclipse/che-theia/pull/1024
> feat(endpoints): Expose endpoint service for plug-ins

- plugins/task-plugin/.gitignore
- plugins/task-plugin/__mocks__/@eclipse-che/plugin.ts
- plugins/task-plugin/__mocks__/@theia/plugin.ts
- plugins/task-plugin/src/che-workspace-client.ts
- plugins/task-plugin/src/export/export-configs-manager.ts
- plugins/task-plugin/src/export/launch-configs-exporter.ts
- plugins/task-plugin/src/export/task-configs-exporter.ts
- plugins/task-plugin/src/extract/che-task-configs-extractor.ts
- plugins/task-plugin/src/extract/vscode-launch-configs-extractor.ts
- plugins/task-plugin/src/extract/vscode-task-configs-extractor.ts
- plugins/task-plugin/src/machine/machines-picker.ts
- plugins/task-plugin/src/task/backward-compatibility.ts
- plugins/task-plugin/src/task/che-task-provider.ts
- plugins/task-plugin/src/task/converter.ts
- plugins/task-plugin/src/task/task-protocol.ts
- plugins/task-plugin/src/variable/server-variable-resolver.ts
- plugins/task-plugin/tests/che-workspace-client.spec.ts
Switch to devfile 2.0 API instead of using old workspace attributes
https://github.com/eclipse/che/issues/19188
Check tasks are working as expected
Change-Id: Ib64a9a1b8e4f15ffba869e79bfe7aa1aa0a87b00
> feat(task-plugin): bump to devfile 2.0 API

- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/get-workspaceroutings-for-a-workspace-id-body.json
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/workspace-routing-object.json
Use new DevWorkspaceRouting objects
https://github.com/devfile/devworkspace-operator/issues/161
Use this image `quay.io/crw_pr/che-theia:1034` with current DevWorkspaceOperator
Change-Id: Id032a090c93ada7244e1738725e3482a239c29b4
> feat(devworkspace): Use new name for workspaceRouting: DevWorkspaceRouting

- RELEASE.md
Adds a doc on how to include an upstream Theia patch into the Che-Theia release.
closes https://github.com/eclipse/che/issues/19141, https://issues.redhat.com/browse/RHDEVDOCS-2741
> Add a doc on how to include an upstream Theia patch into the Che-Theia release

- extensions/eclipse-che-theia-plugin-ext/tests/plugin/che-api.spec.ts
- extensions/eclipse-che-theia-remote-impl-k8s/package.json
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/get-devworkspace-response-body.json
- extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-devfile-service-impl.spec.ts
- extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-endpoint-service-impl.spec.ts
- extensions/eclipse-che-theia-terminal/src/browser/server-definition/remote-terminal-protocol.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts
- plugins/task-plugin/src/che-workspace-client.ts
- plugins/task-plugin/tests/che-workspace-client.spec.ts
Use the collocated-terminal definition (machine-exec component provided in che-theia component definition) instead of terminal that is currently provided by default by che-server property
on a side note, I noticed that the tests were not executed on this module, so I turn it on in package.json.
https://github.com/eclipse/che/issues/19215
Check terminal and tasks are working as before
in che it's more difficult to remove default terminal to see what is happening when default machine-exec is not there
in devworkspace mode, update flattened-theia-next.yaml (or see it doesn't work in that mode)
Reviewers, please comment how you tested the …
> feat(terminal): Use collocated terminal instead of terminal

- extensions/eclipse-che-theia-terminal/src/browser/server-definition/terminal-proxy-creator.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
Don't use cached url in the local storage to connect to the terminal server
https://github.com/eclipse/che/issues/16593
https://github.com/eclipse/che/issues/19201
On the minikube:
- start any workspace
- open new terminal
- stop workspace
- start workspace again
Expected result: che-theia should restore previously opened terminal.
Fixed bug: che-theia opened empty terminal and refresh browser page doesn't help. Helps only clean up local storage of the browser page...
> Don't use cached url in the local storage to connect to the terminal server

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-certificate-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-certificate-service-impl.ts
- plugins/workspace-plugin/src/ca-cert.ts
Imports all CA certificates bundles from `/public-certs` directory in Che-Theia IDE container.
It is commonly that the bundle might have `pem` file extension. Other extensions are possible too, but used not so often. To not to add an additional constraint to the certificates bundle for Che, just import it regardless the bundle file extension.
N/A
https://github.com/eclipse/che/issues/17938
1. Add a tusted bundle into Che using `pem` file extension
2. Start a workspace
3. Check that Che-Theia imported the certificates from the bundle.
Reviewers, please comment how you tested the PR when …
> Add CA certificates from all bundles from /public-certs directory

- extensions/eclipse-che-theia-workspace/src/node/che-workspace-server.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
Enable multi-root by default for Dev Workspaces
https://github.com/eclipse/che/issues/19191
> Multi-root by default for Dev Workspaces

- plugins/workspace-plugin/src/ca-cert.ts
When workspace plugin reads items from `/public-certs` directory, it gets not only files, but directories as well.
It was working before, because names of items checked for `.crt` suffix. The verification was removed by https://github.com/eclipse/che-theia/pull/1038 to operate with certificates, that have any extension (not only `.crt`, `.pem`, ...).
This PR adds a check to take into account only files.
- https://github.com/eclipse/che/issues/19377
- https://github.com/eclipse/che/issues/19309
1. On `Get Started Page` switch to `Custom Workspace`, select a devfile template (e.g. Go)
2. Add following editor to the components to replace the default one
```
reference: …
```
> Filter items when reading /public-certs directory

- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- extensions/eclipse-che-theia-preferences-provider-extension/src/browser/prefs-provider.ts
- extensions/eclipse-che-theia-preferences-provider-extension/tests/prefs-provider-extension.spec.ts
- extensions/eclipse-che-theia-remote-api/src/common/devfile-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-k8s-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/workspace-pod-list.json
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/workspace-status-runtime.json
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-devfile-service-impl.spec.ts
Allow to define extra preferences from environment variables in sidecars (that could come from meta.yaml files)
env variable name is `CHE_THEIA_SIDECAR_PREFERENCES`
env variable value is `stringified value of a JSON content`
https://user-images.githubusercontent.com/436777/112611244-de515500-8e1d-11eb-9dd5-0814636bc3ee.mp4
https://github.com/eclipse/che/issues/17975
https://github.com/eclipse/che/issues/19199
Add CHE_THEIA_SIDECAR_PREFERENCES in a meta.yaml env section and look if the preferences is added
here is a devfile example:
```yaml
metadata:
name: custom-env
attributes:
multiRoot: 'on'
components:
- memoryLimit: 512Mi
reference: 'https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1047/che_theia_meta.yaml'
alias: …
```
> feat(preferences): Allow to define preferences through environment variables

- extensions/eclipse-che-theia-workspace/src/node/che-workspace-server.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
**Notice:** The changes should be merged together with https://github.com/eclipse/che/pull/19406
The changes turn on the Multi-root mode by default for all workspaces.
It's possible to turn off the Multi-root mode by providing the corresponding value for `multiRoot` attribute:
```
attributes:
multiRoot: 'off'
```
Multi-root is `off`:
Multi-root is `on`:
https://github.com/eclipse/che/issues/19389
1. Start a workspace and check that the workspace has started in `Multi-root` mode by default.
2. Add the following to your devfile:
```
attributes:
multiRoot: 'off'
```
3. Start the workspace and check that the `Multi-root` mode is off.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTIN …
> Enable Che-Theia multi-root mode by default for all workspaces

- extensions/eclipse-che-theia-workspace/src/node/che-workspace-server.ts
Replace `WorkspaceService` by `DevfileService` to have multi-root related logic working for `DevWorkspace` engine.
Also please see the comments
-  https://github.com/eclipse-che/che-theia/pull/1053#discussion_r602186469
- https://github.com/eclipse-che/che-theia/pull/1055#issuecomment-808462041
Related to:
- https://github.com/eclipse/che/issues/19191 
- https://github.com/eclipse/che/issues/19389
devfile_V2 use case  -`DevWorkspace`: a workspace should start in `Multi-root` mode by default.
devfile_V1 use case:
1. Start a workspace and check that the workspace has started in `Multi-root` mode by default.
2. Add the following to your devfile:
```
attributes:
multiRoot: 'off'
```
3. Start the workspace and check that the `Multi-root` …
> Replace WorkspaceService by DevfileService

- .github/workflows/release.yml
- build.include
- dockerfiles/theia-vsix-installer/Dockerfile
- dockerfiles/theia-vsix-installer/build.sh
- dockerfiles/theia-vsix-installer/docker/alpine/from.dockerfile
- dockerfiles/theia-vsix-installer/docker/alpine/setup.dockerfile
- dockerfiles/theia-vsix-installer/docker/ubi8/from.dockerfile
- dockerfiles/theia-vsix-installer/docker/ubi8/setup.dockerfile
- dockerfiles/theia-vsix-installer/src/entrypoint.sh
Provides basic vsix-installer for downloading vsix files for theia or sidecars.
Definition is coming from https://github.com/devfile/devworkspace-operator/blob/95cb199a135518aa9909c8868b1342b85c509523/samples/flattened_theia-nodejs.yaml#L101-L130
https://github.com/eclipse/che/issues/18668
1. Build the vsix-installer image and publish it on a OCI registry (or use `quay.io/fbenoit/che-theia-vsix-installer:20210402`)
2. In https://github.com/devfile/devworkspace-operator/blob/95cb199a135518aa9909c8868b1342b85c509523/samples/flattened_theia-nodejs.yaml#L101-L130
remove all args, and use image `quay.io/fbenoit/che-theia-vsix-installer:20210402` (or the one you built)
3. deploy this workspace: `kubectl apply -f flattened_theia-nodejs.yaml -n <your-favorite-namespace>`
4. Check that sidecar is …
> feat(docker): Provide a new vsix-installer image for devfile v2 plug-ins handling

- plugins/workspace-plugin/__mocks__/@eclipse-che/plugin.ts
- plugins/workspace-plugin/__mocks__/@theia/plugin.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
- plugins/workspace-plugin/tests/workspace-projects-manager.spec.ts
- Provide tests for `WorkspaceProjectsManager` logic.
- Remove unused method from `WorkspaceProjectsManager`
No issue.
The tests for `WorkspaceProjectsManager` should be happy.
> Add tests for WorkspaceProjectsManager

- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/flattened-devfile.yaml
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/get-pod-response-body.json
This PR adapts to workspace to devworkspace renaming on DWO side.
It's done in the scope of https://github.com/devfile/devworkspace-operator/issues/321.
It depends on https://github.com/devfile/devworkspace-operator/pull/322
Test that Che Theia inside devworkspace works.
I haven't tested it since it depends on many other component changes, but changes are very simple.
> Adapt to workspace to devworkspace renaming on DWO side

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-certificate-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-certificate-service-impl.ts
Fixes a bug when the plugins view shows an empty list.
https://issues.redhat.com/browse/CRW-1710
1. Start a workspace from devfile:
```
metadata:
name: wksp-custom-tki1v
components:
reference: '<link to the generated meta.yaml, will be available when the PR is opened>'
```
2. Open the `Plugins` view: `View => Plugins`
3. See: plugins list must be loaded.
> Check path to be a file when reading certificates

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-certificate-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-certificate-service-impl.ts
Fixes a bug when the plugins view shows an empty list.
https://issues.redhat.com/browse/CRW-1710
1. Start a workspace
2. Open the Plugins view: View => Plugins
3. See: plugins list must be loaded.
> Check path to be a file when reading certificates (#1072)

- plugins/workspace-plugin/src/workspace-folder-updater.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
Provide backward compatibility for workspaces which were created before switching multi-root mode to ON by default.
https://github.com/eclipse/che/issues/19551
Please see steps defined in https://github.com/eclipse/che/issues/19445#issuecomment-816156790
> Add backward compatibility related to switching to multi root mode

- plugins/workspace-plugin/tests/workspace-projects-manager.spec.ts
Add tests related to backward compatibility for single-root workspaces
related to https://github.com/eclipse/che/issues/19551
the tests should pass successfully
> Add tests related to backward compatibility for single-root workspaces

- .github/workflows/happy-path-tests.yaml
Use latest image of e2e image and not nightly when using chectl/stable channel
Fixes https://github.com/eclipse/che/issues/19568
Look at report and check the image used
Change-Id: I02e9b02d06072ff55303da76a65f36500102b7bc
> chore(happy-path): use stable e2e tests when using chectl stable as well

- dockerfiles/theia/src/entrypoint.sh
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-terminal-widget-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/task-config-service.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-content-reader.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-file-system.ts
- extensions/eclipse-che-theia-plugin-ext/tests/plugin/che-sidecar-file-system.spec.node.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/che-content-aware-utils.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/terminal-container-aware.ts
- extensions/eclipse-che-theia-plugin-remote/src/node/webviews-content-aware.ts
- extensions/eclipse-che-theia-remote-api/src/common/workspace-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-workspace-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devworkspace-env-variables.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-workspace-service-impl.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- extensions/eclipse-che-theia-workspace/src/node/che-workspace-server.ts
- plugins/task-plugin/src/variable/project-path-variable-resolver.ts
- plugins/workspace-plugin/src/workspace-plugin.ts
DevWorkspace is dropping old CHE_* env variables
So CheTheia needs to work in both mode
https://github.com/devfile/devworkspace-operator/issues/344
Change-Id: Ifb177150471a4f8a818b65e6eb413fcc61a3eae2
> feat(env-var): Allow to use both che-server env variables and DevWorkspace env variables

- .github/workflows/happy-path-tests.yaml
happy path are not working with minikube 1.19.0 which is installed by default on github actions runner
here it changes the default
https://github.com/eclipse/che/issues/19602
look if there is a green happy path test with github action (next)
Change-Id: I7ab8fb497b77f3d31c231be8d4f2e8491f1b6394
> chore(happy-path): stick minikube to a working version

- plugins/recommendations-plugin/src/plugin/recommendations-plugin.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
await all promises before returning from clone operation
Fixes https://github.com/eclipse/che/issues/19610
Use a factory link like `#https://github.com/spring-projects/spring-petclinic` with this image but not on workspaces.openshift.com as this instance does not have yet the plug-in registry featured list
You should see some plugins recommandations
Change-Id: I3488f01c3e31bb65a41e5e28a0778f81aac367ca
> fix(workspace-plugin): multiroot promise is not finished when returning from the method

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-custom-editor.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts
Fixes the problem with installing plugins from Plugins view
This PR extends Florent's PR https://github.com/eclipse-che/che-theia/pull/1081
https://github.com/eclipse/che/issues/19623
try to add this component into your devfile:
```yaml
reference: 'https://gist.githubusercontent.com/svor/966bff2009ceaad7d64d8d14fd040155/raw/f28318b9a4f308012171bce1590ec725ca913306/che-theia-editor.yaml'
```
> Handle cheEditor component in addition to chePlugin

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-custom-editor.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-kubernetes-component.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-kubernetes-components.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-openshift-component.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts
Converts Devfile V1 `kubernetes` and `openshift` components into appropriate objects in Devfile V2.
Extends
- https://github.com/eclipse-che/che-theia/pull/1081
- https://github.com/eclipse-che/che-theia/pull/1084
https://github.com/eclipse/che/issues/19634
https://github.com/eclipse/che/issues/19623
Is needed for https://github.com/eclipse-che/che-theia/pull/1076
See
- https://github.com/eclipse/che/issues/19634
- https://github.com/eclipse-che/che-theia/pull/1076
> Inlive Devfile V1 kubernetes component when converting to Devfile V2

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-custom-editor.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts
Cherry-picks https://github.com/eclipse-che/che-theia/commit/a761110eebacac56558f045fc166f0681ccfb40e
Related PR in the master branch is: https://github.com/eclipse-che/che-theia/pull/1084
https://github.com/eclipse/che/issues/19623
> Handle cheEditor component in addition to chePlugin (#1084)

- extensions/eclipse-che-theia-remote-api/src/common/devfile-service.ts
- plugins/recommendations-plugin/__mocks__/@theia/plugin.ts
- plugins/recommendations-plugin/tests/plugin/recommendations-plugin.spec.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
After latest refactoring of https://github.com/eclipse-che/che-theia/pull/1079, the push of promises was gone, fixing it
https://github.com/eclipse/che/issues/19610
Open a workspace without plug-ins (but this customized editor) you should see some recommendation popup
(but do not use workspaces.openshift.com that don't have any featured plug-in on its plug-in registry)
Change-Id: I74fd1c366f6ba0fa583ce14935e60f5ae4efd5a4
> fix(recommendations): promise were not added anymore to the waiting list

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-attributes.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-devfile-service-impl.spec.ts
Preserves devfile attributes when changing the devfile from Che-Theia
is needed for
- https://issues.redhat.com/browse/CRW-1746
- https://github.com/eclipse/che/issues/19544
1. Create workspace from the devfile
```
---
attributes:
multiRoot: 'off'
metadata:
name: test
```
2. Go to Plugins view and install any plugin.
3. Open dashboard and check the devfile, it should contain `multiRoot` attribute.
> Devfile: preserve attributes

- plugins/recommendations-plugin/__mocks__/@theia/plugin.ts
- plugins/recommendations-plugin/src/fetch/featured-fetcher.ts
- plugins/recommendations-plugin/src/fetch/plugins-by-language-fetcher.ts
- plugins/recommendations-plugin/tests/fetch/featured-fetcher.spec.ts
- plugins/recommendations-plugin/tests/fetch/plugins-by-language-fetcher.spec.ts
plug-in was using information message instead of notifying through error message
Fixes https://issues.redhat.com/browse/CRW-1714
Look at unit tests or use https://issues.redhat.com/browse/CRW-1702 details to reproduce it ("spec.server.useInternalClusterSVCNames=false)
Change-Id: Id804f5605e5c686a43ad26d7de50fcfd7c7c8f6d
> fix(recommendations): Use Error message instead of Info message on errors

- extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
Modifies `storagePath` to use current home directory of a container where remote plugin is running.
https://issues.redhat.com/browse/CRW-1793
-  Run a workspce with a java plugin where HOME is not `/home/theia` as an example you can take this patched plugin https://gist.githubusercontent.com/svor/58490c28fd6a8a2acdb85492f824b7a0/raw/413908f2b8ec5f5bd55db66f28296f19c08af08f/test-meta.yaml 
-  Open any java file, as a result Java LS should be initialized. Also `/home/jboss/.theia/workspace-storage` folder in vscode-java container should contain a subfolder.
Reviewers, please comment how you tested …
> Fix plugin storage path after updating

- plugins/recommendations-plugin/src/plugin/recommendations-plugin.ts
- plugins/recommendations-plugin/tests/plugin/recommendations-plugin.spec.ts
Backport https://github.com/eclipse-che/che-theia/pull/1098 to 7.30.x
#1098 
> fix(recommendations): Do not try to suggest a different version of an existing plug-in

- plugins/task-plugin/src/export/launch-configs-exporter.ts
- plugins/task-plugin/src/utils.ts
I'm working on CRW-1758.
Within CRW-1758 I tested these changes based on 7.30.x for power related infrastructure.
- There was an issue related to file watchers: the watcher only reported the first directory when creating recursively directories.
We had to use a workaround to avoid the issue.
The issue was fixed in the upstream: https://community.theia-ide.org/t/eclipse-theia-v1-12-1-patch-release/1588
Now we can remove the workaround.
- I have removed the check from `ensureDirExists(filePath: string)` method:
```
if (await fs.pathExists(dirName))
``` 
as it looks like the check is redundant: `fs.mkdirp(dirName)` should not throw an error if a directory already exists.
https://github.com/eclipse/che/issues/19457
1. Start a workspace from …
> Remove file watcher related workaround

- dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile
- dockerfiles/theia-vsix-installer/docker/ubi8/from.dockerfile
- dockerfiles/theia/docker/ubi8/build-result-from.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
This simple PR updates a bunch of base images used for building on RHEL.
Related to https://issues.redhat.com/browse/CRW-1844
> Update ubi8 images to the latest nodejs and minimal base images from RHEL8.4

- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- extensions/eclipse-che-theia-remote-api/src/common/endpoint-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-endpoint-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-endpoint-service-impl.ts
- plugins/task-plugin/src/che-workspace-client.ts
- plugins/task-plugin/tests/che-workspace-client.spec.ts
Fix port evaluation for machine exec.
**Before**:
**After**:
it's for https://github.com/eclipse/che/issues/19810
1. Create devworkspace like https://github.com/sleshchenko/NodeJS-Sample-App/blob/main/devfile.yaml
2. Try to execute the command
> Fix port evaluation for machine exec

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-telemetry-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-server-common.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/node/che-server-endpoint-service-impl.spec.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/flattened-devfile.yaml
- extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-endpoint-service-impl.spec.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
This PR makes Che Theia rely on the main endpoint type instead of deprecated ide.
Ide is still respected since Che Server uses it.
it's one piece of many for https://github.com/devfile/devworkspace-operator/issues/399
It should be merged in sync with https://github.com/devfile/devworkspace-operator/issues/399 and https://github.com/eclipse-che/che-plugin-registry/pull/963
1. deploy Che with DevWorkspace enabled.
Note that custom plugin registry and DWO should be deployed from the referenced PRs.
2. Make sure that Theia works without issues, like from master branch. …
> Make Che Theia to rely on main endpoint type

- dockerfiles/theia-vsix-installer/src/entrypoint.sh
theia-vsix installer component is reading attributes of kubernetes container but it may fail on some configurations (like lot of attributes)
N/A
use the container field
```json
{"attributes":{"app.kubernetes.io/component":"vscode-extension","app.kubernetes.io/name":"maven","app.kubernetes.io/part-of–":"che-theia.eclipse.org","che-theia.eclipse.org/vscode-extensions":["https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.75.0-60.vsix","https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix","https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix"],"che-theia.eclipse.org/vscode-preferences":{"java.server.launchMode":"Standard"}},"container":{"env":[{"name":"PLUGIN_REMOTE_ENDPOINT_EXECUTABL …
```
> fix(regexp): vsix-extensions is not the only attribute, so we may have extra attributes to handle

- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-devfile-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-go-v1.yaml
Devfile v1 is converted internally to devfile V2 to expose new API to plug-ins/extensions but `registryUrl` field was not handled.
Thus, if the editor needs to write the file at some point, this information is removed
Fixes https://github.com/eclipse/che/issues/19829
Look at the unit test (now the field is preserved)
Another manual way : Add a custom component using `registryUrl` field, then starts the workspace, install another plug-in and now look at the updated devfile. New plug-in should be there but also the `registryUrl` should be still there …
> fix(convert): When converting devfile v1 to v2, registryUrl attribute is forgotten

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Takes into account, that icon path is relative to repository root.
With this fixup plugin icons must properly appear in Plugins panel in single host Che deployment.
Corresponding PR to che-plugin-registry https://github.com/eclipse-che/che-plugin-registry/pull/968
https://github.com/eclipse/che/issues/19771
https://issues.redhat.com/browse/CRW-1840
- deploy Che with this patch. Plugin registry refers on registry with this changes https://github.com/eclipse-che/che-plugin-registry/pull/968
```
spec:
k8s:
singleHostExposureType: 'gateway'
server:
serverExposureStrategy: single-host
pluginRegistryImage: quay.io/vgulyy/che-plugin-registry:test-plugin-icons
```
- create a workspace from Happy Path tests devfile from this PR
[As the author of …
> Icon path must be relative to plugin registry root

- generator/src/generate-assembly.ts
- generator/src/yargs.ts
Fixes erroneous use of install dir instead of target che-theia dir for finding extensions in che-theia.
che-theia generate is broken in theia-dev image https://github.com/eclipse/che/issues/19943
Follow the instructions in linkless-build.md
> chore(linkless): Use correct base dir for che-theia extensions

- generator/tests/link.spec.ts
If CPU is overloaded, following test is failing due to timeout.
This PR adds an additional timeout in 30 seconds.
```
@eclipse-che/theia-generator: FAIL tests/link.spec.ts (7.606 s)
@eclipse-che/theia-generator:   ● Test link command › test link
@eclipse-che/theia-generator:     : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
@eclipse-che/theia-generator:       36 |     });
@eclipse-che/theia-generator:       37 |
@eclipse-che/theia-generator:     > 38 |     test('test link', async () => {
@eclipse-che/theia-generator:          |     ^
@eclipse-che/theia-generator:       39 | …
```
> fix(generator): Increase jest timeout to give the test extra time when CPU is overloaded

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Applies https://github.com/eclipse-che/che-theia/pull/1118 to 7.30.x branch
https://github.com/eclipse/che/issues/19771
See original PR https://github.com/eclipse-che/che-theia/pull/1118
> fix: Icon path must be relative to plugin registry root (#1118)

- dockerfiles/theia-dev/Dockerfile
- dockerfiles/theia/Dockerfile
Includes new version of `@theia/generator-plugin` in `che-theia` and in `che-theia-dev` images.
https://github.com/eclipse/che/issues/19889
- create workspace
- run yeoman wizard
- create frontend or backend plugin
> fix(yeoman): Update Theia plugin yeoman generator

- plugins/ports-plugin/__mocks__/@eclipse-che/plugin.ts
- plugins/ports-plugin/src/devfile-handler-devworkspace-impl.ts
- plugins/ports-plugin/src/ports-plugin.ts
- plugins/ports-plugin/tests/devfile-handler/devfile-handler-devworkspace-impl.spec.ts
- plugins/ports-plugin/tests/devfile-handler/devworkspace-flattened.yaml
Add support for devworkspaces in ports-plugin
For now when starting a devWorkspace we have a failure saying that extension can't read machines field (which is only che-server implementation)
https://github.com/eclipse/che/issues/19188
Start devWorkspace with che-theia and see that ports-plugin display endpoints
Change-Id: I67d3d67dd52d9ec6a0b12b7aeeb65f7bdf34d801
> feat(ports-plugin): Handle devworkspaces

- plugins/ssh-plugin/src/ssh-plugin.ts
There is no ssh service yet with DevWorkspace. Disable it when running with devWorkspace instead of showing error messages about not finding SSH service
https://github.com/eclipse/che/issues/19188
Start with DevWorkspace mode and check ssh-plugin is disabled (no warning notification about failure on ssh keys)
Change-Id: I9fe4d0bf637c6fdba805fb1374dd67fbe807e083
> fix(ssh-plugin): Disable the plug-in on DevWorkspace as there is no REST API (including ssh)

- plugins/containers-plugin/src/containers-tree-data-provider.ts
Fix tasks not being revealed.
This is temporary as it is not possible to provide fix to theia right now. Bug will be fixed for the user.
Note that if the task is available for multiple containers, it would ask in which container to execute even if the user expects it to be executed in the container where the action is located. It shouldn't happen at the moment anyway: 
- not possible to have multiple component attached to the same command in the devfile
- kubernetes type components seem to be buggy. I tried the devfile from https://github.com/sleshchenko/NodeJS-Sample-App/tree/348e76c900527ccc77202c9bcf401df2c89121ed but had no tasks available in the myworkspace
N/A
https://github.com/eclipse/che/issues/19805
- with this build of che-theia, 
- open any devfile with task
- from my …
> fix(task): Temporary fix to reveal tasks executed from the myworkspace view

- .github/workflows/build-publish-next.yml
- .github/workflows/publish-built-in-extension-report.yaml
- CONTRIBUTING.md
- README.md
- RELEASE.md
- che-theia-init-sources.yml
- devfiles/hosted-che-dogfooding.devfile.yaml
- dockerfiles/theia/README.md
- generator/README.md
- generator/src/init-sources.ts
- generator/tests/init-sources/init-sources.spec.ts
- make-release.sh
- plugins/ext-plugin/README.md
- plugins/workspace-plugin/.travis.yml
- plugins/workspace-plugin/tests/devfile-service.spec.ts
- tools/automation/README.md
- tools/automation/package.json
- tools/devworkspace-handler/package.json
Updates the unit tests, CI jobs and other mentions of `master` branch to `main`.
https://github.com/eclipse/che/issues/20000
Build jobs should pass. At least one job for HappyPath tests should pass.
> refactor: Update `master` branch mentioning to `main`

- generator/src/init-sources.ts
Update link after switching from `master` to `main`.
https://github.com/eclipse/che/issues/20000
`docker-build` jobs should pass.
> Update link after switching from `master` to `main`

- generator/tests/init-sources/init-sources.spec.ts
Adapts unit tests to git 1.8 used for HappyPath tests. As `git init -b main` requires git > 2.28.
See https://github.com/eclipse-che/che-theia/pull/1149#issuecomment-864456342
When building the images for HappyPath tests there shouldn't be an error like https://github.com/eclipse-che/che-theia/pull/1149#issuecomment-864456342
> Adapt unit tests to git 1.8 used for HappyPath tests

- plugins/recommendations-plugin/src/strategy/featured-plugin-strategy.ts
- plugins/recommendations-plugin/tests/strategy/featured-plugin-strategy.spec.ts
Avoid duplicated plug-ins in recommendations
Fixes https://github.com/eclipse/che/issues/19883
please follow `Steps to reproduce` of the linked issue
Change-Id: I3c0ef5d37a855e5212d08f051f943fb5888b7a86
> fix(recommendations-plugin): avoid duplicated plug-ins

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
When Che is deployed in single-host mode, the plugin registry does not respect index.json file, where all the plugins are described.
For that case, it's better to read plugins.json file directly.
https://github.com/eclipse/che/issues/19955
> fix(plugins): Change path to plugins index.json file

- extensions/eclipse-che-theia-workspace/src/browser/che-navigator-widget.tsx
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-module.ts
- extensions/eclipse-che-theia-workspace/src/browser/style/index.css
- yarn.lock
Displays `Welcome` panel for the `Explorer` view when there are no projects in a devfile
https://user-images.githubusercontent.com/5676062/123442491-989f5680-d5dd-11eb-8e3a-f31ba8d3f3e3.mp4
https://github.com/eclipse/che/issues/19645
1. Start a workspace from a devfile without projects - you should see the `Welcome` panel with `Clone Repository` and `New Folder` buttons in the `Explorer` view.
2. Try to use the buttons.
3. Start a workspace with projects - you shouldn't see the`Welcome` panel.  …
> feat(explorer): Display Welcome panel when there are no projects in a devfile

- generator/src/conf/.yarnclean
- generator/src/yarn.ts
- fixed excluded packages which directly defined on package.json.
- add `react` to `generator/conf/.yarnclean`
fixed https://github.com/eclipse/che/issues/20056
1. `che-theia init`
2. `yarn`
2. `cd example/assembly`
3. `yarn add react`
4. `cd ../.. && che-theia production`
5. `find production/node_modules -name 'react'`
6. `find production/node_modules/@theia -name 'monaco' `
> fix(generator): fix excluded packages in production command

- dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile
- dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile
adding libsecret and tig for theia-dev container to be used in theia and che-theia dogfooding devfiles
- libsecret is required now by Theia. And it is impossible to run yarn start without it.
- tig is a nice cli tool for git to be used by developers.
N/A
N/A
build theia-dev container, push it to quay.io, and use it with theia devfile instead the default theia-dev image https://github.com/eclipse-theia/theia/blob/master/devfile.yaml#L15
running theia after having built it should work.
> chore(theia-dev container): adding libsecret and tig to theia dev container

- extensions/eclipse-che-theia-mini-browser/src/browser/che-mini-browser-environment.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-webview-environment.ts
Override `hostPatternPromise` field for `CheWebviewEnvironment` and `CheMiniBrowserEnvironment` classes as they are used by upstream theia.
fixes https://github.com/eclipse/che/issues/20077
1. Start a workspace from dev file:
```
metadata:
name: wksp-ff9w4
components:
reference: 'https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1168/che_theia_meta.yaml'
```
See: no warning notifications appear.
> fix: Fix hostpattern changed warning notification

- dockerfiles/theia-vsix-installer/src/entrypoint.sh
Use registry URL as prefix for relative URLS
https://github.com/eclipse/che/issues/20198
Try with offline registry or try to use in the script an url with relative format
> fix(vsix-installer): Should handle relative URLs

- dockerfiles/theia-vsix-installer/src/entrypoint.sh
It avoids CrashLoopBackedOff if for some reason it's not set
Due to a bug, the env var may not be set, so just avoid to download the plug-in instead of breaking workspace startup
https://github.com/eclipse/che/issues/20198
https://github.com/eclipse/che/issues/20201
Can be tested on nightly CRW (which has the bug with empty URL + relative URLs)
Change-Id: Ibee32589402fd327d8c6af590499aaf8d1b0898f
> fix: ensure registry URL is defined and not exit on error

- plugins/workspace-plugin/src/workspace-projects-manager.ts
- plugins/workspace-plugin/tests/workspace-projects-manager.spec.ts
fixed https://github.com/eclipse/che/issues/20196
Fix the bug that all of projects would be added to custom workspace
- create a che workspace
- create folder `a` and `b`
- create a custom theia workspace config file `custom.theia-workspace`
```json
{
"folders": [
{
"path": "a"
},
{
"path": "b"
},
]
}
```
- press `F1` and select `Open Workspace Root`
- select `custom.theia-workspace`
Only the folder which defined on workspace config would be added to workspace
> fix(workspace-plugins): fix custom workspace folders

- dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile
- dockerfiles/theia/Dockerfile
Add libsecret-dev to allow to build keytar
https://github.com/eclipse/che/issues/20237
Look at PR check
Change-Id: I8678670827a5c2914f733675b7d5941409dc9feb
> chore(keytar): Adds library to build keytar and also upgrade keytar

- dockerfiles/build.sh
Fix theia images build for systems with bash 5
On the bash 4 behavior is expected:
```bash
ls
theia  theia-dev  theia-endpoint-runtime-binary  theia-vsix-installer
[root@c3bcd6e82f45 test]#  for dir in */ ; do echo $dir; done
theia/
theia-dev/
theia-endpoint-runtime-binary/
theia-vsix-installer/
[root@c3bcd6e82f45 test]# bash --version
GNU bash, version 4.4.23(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
But with newer bash 5:
```bash
[root@8e4788b010b4 test]# ls
ls
theia  theia-dev  theia-endpoint-runtime-binary  theia-vsix-installer
printf …
```
> chore(build): fix theia images build for systems with bash 5

- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-api-provider.ts
Fixing loading of sidecar filesystem provider by resolving local js files.
Was broken after https://github.com/eclipse-che/che-theia/commit/732da858f5572eb51fc1397005a6d625c7eca351#diff-589b5b8947b39aa1b6053732321110a0df085189ef25b28df77623958d4bacf3
Fix https://github.com/eclipse/che/issues/20057 (Cannot open jupyter notebooks)
With the devfile:
```yaml
metadata:
generateName: python-jupyter-
projects:
- name: jupyter-hello-world1
source:
startPoint: master
location: 'https://github.com/chasbecker/TextAnalysis.git'
type: git
components:
- id: ms-python/python/latest
- mountSources: true
memoryLimit: 512Mi
volumes:
- name: venv
containerPath: /home/user/.venv
image: 'quay.io/eclipse/che-python-3.8:nightly'
alias: python …
```
> fix(loading-sidecar-fs): Fixing loading of sidecar filesystem provider by resolving local js files

- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/devfile-attributes.yaml
- extensions/eclipse-che-theia-remote-impl-che-server/tests/_data/workspace-status-runtime.json
- extensions/eclipse-che-theia-workspace/src/node/che-workspace-server.ts
- plugins/workspace-plugin/src/workspace-projects-manager.ts
- plugins/workspace-plugin/tests/workspace-projects-manager.spec.ts
Removes the `Multi-root` feature toggle support from `Che-Theia`.
It was possible to turn on single root mode in a devfile, like:
```
attributes:
multiRoot: 'off'
```
So, with current PR changes the corresponding attribute in a devfile has no effect.
https://github.com/eclipse/che/issues/19594
- All functionality should work correctly as before these changes.
- I tested with the following section in my devfile:
```
attributes:
multiRoot: 'off'
```
The result: it creates a workspace in `multi-root` (not `single` root) mode
- I tested backward compatibility:
first, I created a workspace from a devfile with default editor in the `single` root mode
<details>
<summary>example of devfile for single root mode</summary>
``` …
```
> feat(multi-root): Multi-root is the only mode in Che-Theia, no feature toggle anymore

- make-release.sh
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
If build include contains THEIA_COMMIT_SHA value, then use it as theia version, otherwise use next version
closes https://github.com/eclipse/che/issues/20221
> fix: Use build.include sha commit version of theia during release

- .github/workflows/next-build.yml
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
Rename CI build job to next-build.yaml (To make it similar with other next build jobs in Eclipse Che projects)
Add notification that will be sent to Eclipse MM channel
> chore: Rename next build job. Send notification of its failure to mattermost

- .github/workflows/next-build.yml
- .github/workflows/release.yml
Fix the notifications not being send in the case of failure for Next and Release workflows (docker image removal in the build job requires to put notification action in a separate job)
A special condition is needed in order to ensure that the notification job always is run, but only at success or failed state of the previous build job.
>  fix: fix GH Actions workflows sending notification on failure

- plugins/recommendations-plugin/src/devfile/devfile-handler.ts
- plugins/recommendations-plugin/src/registry/che-plugin-registry.ts
- plugins/recommendations-plugin/tests/find/find-file-extensions.spec.ts
- plugins/recommendations-plugin/tests/strategy/recommend-plugin-open-file-strategy.spec.ts
- plugins/recommendations-plugin/tsconfig.json
recommendations plug-in was using a custom (one that is added by the yeoman generator) while it should use upper configuration like the other plug-ins
N/A
Recommendations plug-in should work as before
> chore(recommendations-plugin): Use upper tsconfig file

- tools/devworkspace-handler/src/api/devfile-context.ts
- tools/devworkspace-handler/src/devfile/che-theia-plugins-devfile-resolver.ts
- tools/devworkspace-handler/tests/devfile/che-theia-plugins-devfile-resolver.spec.ts
Handle empty sidecar policy
In that case:
- look at a devfile attribute
- or take a default policy (use dev container)
https://github.com/eclipse/che/issues/20588 for che-theia side
Look at unit tests
or/and link in dashboard development mode this library
Change-Id: I01a0c5238ebdd6d2c521a03ad135a148b74c361d
> feat(dw-handler): Handle empty sidecar policy

- dockerfiles/theia-endpoint-runtime-binary/src/entrypoint.sh
Avoid to download again vsix files on restarting a workspace
https://github.com/eclipse/che/issues/20592
Start a devWorkspace like spring petclinic devfile v2 getting started sample
look at endpoint-runtime logs: you can see curl commands fetching vsix and then java extensions are running in the workspace
And if you restart this workspace, look at init container endpoint runtime: you won't see curl command but a line saying it's already there and when workspace is loaded, you can see that the java extensions are still there as well
Change-Id: …
> feat: DevWorkspace: Do not download vsix if already fetched in volume

- make-release.sh
Reworks fetching the `THEIA_COMMIT_SHA` as an npm package name doesn't contain it anymore.
See the details in the discussion on the issue https://github.com/eclipse-theia/theia/issues/10233
Run the following instructions "by hand" to make sure they return what is expected by the script:
```shell
THEIA_VERSION=$(curl -sSL http://registry.npmjs.org/-/package/@theia/core/dist-tags | jq -r '.next')
BUILD_INCLUDE_THEIA_COMMIT_SHA=$(curl -sSL https://registry.npmjs.org/@theia/core/"${THEIA_VERSION}" | jq -r '.gitHead')
echo $BUILD_INCLUDE_THEIA_COMMIT_SHA
```
Reviewers, please comment how …
> fix: Rework fetching THEIA_COMMIT_SHA as an npm package name doesn't contain it anymore

- extensions/eclipse-che-theia-remote-api/src/common/http-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-http-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-http-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-workspace-service-impl.ts
Implement activity tracking mechanism for DevWorkspace environment.
Screenshot provided in How to test section.
fixes https://github.com/eclipse/che/issues/20460
Create the workspace from the following repository: https://github.com/vzhukovs/che-editor-test2
Open minikube dashboard and go to machine-exec logs, there should be tick events:
> Implement activity tracking for k8s

- dockerfiles/theia-dev/Dockerfile
Stick vsce to v1.* versions that are compliant with nodejs 12
https://github.com/microsoft/vscode-vsce/commit/302d33d65be4a0b773178cd0a0dd806884b0cba0
https://github.com/eclipse/che/issues/20729
look at ci job, it should work
Change-Id: Ie4579c9c297e6235c417dbfcd27cf0bbb3edff9d
> fix: theia-dev image was not building

- dockerfiles/theia-endpoint-runtime-binary/build.sh
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/runtime-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/src/entrypoint.sh
- dockerfiles/theia-endpoint-runtime-binary/test.Dockerfile
- dockerfiles/theia-endpoint-runtime-binary/tests/_data/flattened_devfile.yaml
- dockerfiles/theia-endpoint-runtime-binary/tests/test_entrypoint.sh
At the beginning, theia component was part of the devWorkspace and then we
had access to the atttributes from the DevWorkspace object
Now, it's part of the devWorkspaceTemplate object
Switch to the flattened devfile instead so nothing to query externally
Also, in order to reduce sed usage, use jq/yq instead as there was also a bug
on empty list
Added some unit tests as well
https://github.com/eclipse/che/issues/20718
Start the workspace from the issue
Eslint should not be there (check output widget inside theia or command palette)
if you check the logs of the init container you might as well see tons of errors
Open a terminal and drop anything located inside /plugins folder
Edit the DevWorkspaceTemplate object
Search for the `remote-runtime` component
```yaml
app.kubernetes.io/component: …
```
> fix: Plugins without sidecars were not injected

- tools/devworkspace-handler/package.json
- tools/devworkspace-handler/src/devfile/dev-container-component-finder.ts
- tools/devworkspace-handler/tests/devfile/dev-container-component-finder.spec.ts
Enhance pattern to find the devcontainer from a devfile:
- Allow to set 'che-theia.eclipse.org/dev-container': true attribute to specify the container
- Skip all mountSources:false containers
- Take first container if more than one container is found
https://github.com/eclipse/che/issues/20725
Look at the tests
Also you can check DevWorkspace generated by the command
```bash
$ cd tools/devworkspace-handler
$ node lib/entrypoint.js --devfile-url:https://github.com/svor/console-java-simple/tree/devfile2 --output-file:/tmp/all-ione.yaml
No plug-in registry url. Setting to https://eclipse-che.github.io/che-plugin-registry/main/v3
No editor. Setting to eclipse/che-theia/next
No sidecar policy. Setting to useDevContainer
More than one dev container component has been potentially found, taking …
```
> fix: handle multiple containers in one devfile.yaml

- dockerfiles/theia-endpoint-runtime-binary/src/entrypoint.sh
Always download vsix files as expected
Fixes https://github.com/eclipse/che/issues/20786
Click on a link like https://che-host/#https://github.com/svor/scala-sbt/tree/44377a575ff436dd17903d123048b7c03e112a25?che-editor=https://gist.githubusercontent.com/benoitf/2253b07833857f1f1a5a5d50c42b7be2/raw/295a9941a9fbf0da7357511dedbc0aa0dbed126e/theia-next
with DevWorkspace engine being enabled
Change-Id: I789b2f6ce4ef8e733b3a3633e7523fd416d977e3
> fix: make sure we don't loop if there are spaces in the fields

- dockerfiles/theia-endpoint-runtime-binary/src/entrypoint.sh
Multiple URLs were not analyzed as the for loop separator was set to newline
Fixes the fix of https://github.com/eclipse/che/issues/20786
it was adding a new separator on for loop using only newlines and then we need here to reset it to be space separated again
You may test with quay.io/fbenoit/che-theia-endpoint-runtime-binary:20211119 image
```
https://<che-host>#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=https://gist.githubusercontent.com/benoitf/2253b07833857f1f1a5a5d50c42b7be2/raw/32ef83517a5e961a01ab633e332250305412fcfe/theia-next
```
Reviewers, please comment how you tested the PR when …
> chore: ensure the loop is done on a space separated variable

- tools/devworkspace-handler/src/devfile/che-theia-plugins-analyzer.ts
- tools/devworkspace-handler/src/plugin-registry/plugin-registry-resolver.ts
- tools/devworkspace-handler/tests/_data/che-theia/che-theia-plugins-id.yaml
- tools/devworkspace-handler/tests/_data/che-theia/che-theia-plugins.yaml
- tools/devworkspace-handler/tests/devfile/che-theia-plugins-analyzer.spec.ts
- tools/devworkspace-handler/tests/plugin-registry/plugin-registry-resolver.spec.ts
- yarn.lock
Makes it possible to overwrite default values of preferences and resources limits of a sidecar which come from the plugin registry. 
New values are taken from the `.che/che-theia-plugins.yaml` which is located in the sample repository.
https://github.com/eclipse/che/issues/20596
To check that preferences were applied:
- Go into che-theia/tools/devworkspace-handler
- Execute `node lib/entrypoint.js --devfile-url:https://github.com/svor/java-spring-petclinic/tree/sv-che-preferences --output-file:/tmp/all-in-one.yaml`
- Check the content `/tmp/all-in-one.yaml`. 
Tools component should contain:
```yaml
che-theia.eclipse.org/vscode-preferences:
java.server.launchMode: LightWeight
``` 
This preference comes from [che-theia-plguins.yaml](https://github.com/svor/java-spring-petclinic/blob/sv-che-p …
> chore: apply preferences and sidecar's updates form che-theia-plugins.yaml 

- tools/devworkspace-handler/src/devfile/dev-container-component-updater.ts
- tools/devworkspace-handler/tests/devfile/dev-container-component-updater.spec.ts
A volume component should be added if a VSCode extension / che-theia plug-in requires a volumeMount that is not specified.
https://github.com/eclipse/che/issues/20805
Look at the test or try out
node lib/entrypoint.js --devfile-url:https://github.com/benoitf/spring-petclinic/tree/testmario --output-file:/tmp/all-ione.yaml
Change-Id: If31e8c63d259e80566aac743869668e6fac4ee9f
> fix: Add volume component if plug-in declares a volumeMount

- extensions/eclipse-che-theia-dashboard/package.json
- extensions/eclipse-che-theia-dashboard/src/browser/che-theia-dashboard-module.ts
- extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts
- extensions/eclipse-che-theia-remote-api/src/browser/che-remote-api-frontend-module.ts
- extensions/eclipse-che-theia-remote-api/src/common/dashboard-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-dashboard-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-remote-impl-che-server-backend-module.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-backend-module.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-dashboard-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devworkspace-env-variables.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-workspace-service-impl.ts
- extensions/eclipse-che-theia-workspace/src/browser/che-workspace-controller.ts
- Add a link to dashboard in command palette for DevWorkspace mode
- Implement the stopWorkspace method (instead of current throwing 'not implemented' error) of a DevWorkspace
- Redirect to the dashboard page when closing the Workspace in DevWorkspace mode (today it's doing nothing. workspace is not stopped and we stay in the IDE page)
Fixes https://github.com/eclipse/che/issues/20808
In DevWorkspace mode:
open a getting started, check there is a link in command palette to open dashboard and you can open dashboard
close the workspace and check we're redirected to dashboard
you can try with:
`https://<che-host-with-devworkspace>#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=https://gist.githubusercontent.com/benoitf/8603992a73e902792b8961c645395897/raw/619f4 …
> feat: devWorkspaces: Add link to dashboard, implement stop

- .github/workflows/try-in-web-ide.yaml
Add [`Try in Web IDE`](https://github.com/marketplace/actions/try-in-web-ide) workflow.
https://github.com/eclipse/che/issues/20664
> Add 'Try in Web IDE' workflow

- tools/devworkspace-handler/src/generate.ts
- tools/devworkspace-handler/src/github/github-url.ts
- tools/devworkspace-handler/src/main.ts
- tools/devworkspace-handler/tests/generate.spec.ts
- tools/devworkspace-handler/tests/github/github-resolver.spec.ts
- tools/devworkspace-handler/tests/main.spec.ts
Add an optional parameter `--project.<project name>=<project location>`
If defined, project section in a zip format is added to the devfile template:
```yaml
projects:
- name: project-name
zip:
location: '{{DEVFILE_REGISTRY_URL}}/project-name.zip'
```
If not defined, project section in a git format is added to the devfile template:
```yaml
projects:
- name: java-spring-petclinic
git:
remotes:
origin: https://github.com/che-samples/java-spring-petclinic.git
checkoutFrom:
revision: devfilev2
```
https://github.com/eclipse/che/issues/20877
1. Build the `devworkspace-handler` package
2. Run `node lib/entrypoint.js --devfile-url:https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 …
> chore: [theia-devworkspace handler] store projects section when generating templates

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-workspace-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
- extensions/eclipse-che-theia-plugin-ext/src/plugin/che-workspace.ts
- extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
- extensions/eclipse-che-theia-remote-api/src/common/workspace-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-workspace-service-impl.ts
- plugins/resource-monitor-plugin/__mocks__/@eclipse-che/plugin.ts
- plugins/resource-monitor-plugin/src/plugin.ts
- plugins/resource-monitor-plugin/tests/plugin.spec.ts
Reads namespace's name form the environment variable
depends on devworkspace-operator 0.12.0 https://github.com/devfile/devworkspace-operator/pull/695
https://github.com/eclipse/che/issues/20800
> fix(resource-monitor): get DW Namespace name from ENV variable

- tools/devworkspace-handler/src/generate.ts
- tools/devworkspace-handler/tests/generate.spec.ts
Move the generated `projects` section from the editor devfile to the user devfile.
eclipse/che#20877
1. Build the `devworkspace-handler` package
2. Run `node lib/entrypoint.js --devfile-url:https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 --output-file:/Users/ivinokur/projects/che-theia/tools/devworkspace-handler/a.yaml` in the package root and see the default projects section exists in the user devfile of thegenerated template.
3. Run `node lib/entrypoint.js --devfile-url:https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 --output-file:/Users/ivinokur/projects/che-theia/tools/devworkspace-handler/a.yaml --project.name={{DEVFILE_REGISTRY_URL}}/project.zip` and see the projects section with the specified …
> fix: [devworkpsce-handler] Move project section from editor devfile to user devfile

- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-command-contribution.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-service-client.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Renames some fields in ChePluginRegistry interface.
This PR contains some decoupled changes, introduced by https://github.com/eclipse-che/che-theia/pull/1267
Merging of this PR will simplify the reviewing of https://github.com/eclipse-che/che-theia/pull/1267
None
No issue
> chore(refactor): rename fields for ChePluginRegistry

- dockerfiles/theia/Dockerfile
Sets `vscode-ripgrep` to `1.12.0`.
See the details in [the downstream issue](https://issues.redhat.com/browse/CRW-2600?focusedCommentId=19535799&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19535799).
https://issues.redhat.com/browse/CRW-2600
> Stick vscode-ripgrep to 1.12.0

- dockerfiles/theia/Dockerfile
Removes `/home/theia/plugins` folder from Che-Theia runtime image. It contains the built-in VS Code extensions. It's redundant as we copy all the plug-ins to `/default-theia-plugins` folder.
fixes https://github.com/eclipse/che/issues/20678
0. Run a container with these changes:
`docker run -it --entrypoint bash quay.io/azatsary/che-theia:plug-ins`
1. Check that there's no `/home/theia/plugins` folder anymore:
`ls -la ~`
2. Check that `/default-theia-plugins` folder still present:
`ls -la /default-theia-plugins/`
3. Check that at least one Happy Path PR check is passed which means that Che-Theia is started with the running plugins.
[As the author of this Pull Request I made sure …
> Remove the redundant plugins folder

- tools/devworkspace-handler/src/devfile/devworkspace-updater.ts
- tools/devworkspace-handler/src/devfile/sidecar-components-creator.ts
- tools/devworkspace-handler/tests/devfile/sidecar-components-creator.spec.ts
Make sure generated names are not greater than 63 characters
https://github.com/eclipse/che/issues/21040
https://issues.redhat.com/browse/CRW-2651
1. Launch CRW registry 
docker run --rm -it -p 8080:8080 quay.io/crw/pluginregistry-rhel8:2.14
2. Launch the command
```
$ npx @eclipse-che/che-theia-devworkspace-handler --devfile-url:https://github.com/crw-samples/nodejs-configmap/tree/devfilev2 --editor:eclipse/che-theia/latest --plugin-registry-url:http://localhost:8080/v3 --output-file:/tmp/foo.yaml --sidecar-policy:mergeImage
```
3. now, create a devWorkspace from the /tmp/foo.yam file
oc apply -f /tmp/foo.yaml
and it's failing with 
```
The DevWorkspace "nodejs-configmap" is invalid: spec.template.components.name: Invalid value: …
```
> fix: ensure names are not > 63 characters

- extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/browser/che-github-main.ts
- extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-backend-module.ts
- extensions/eclipse-che-theia-plugin-ext/src/node/che-github-service.ts
- plugins/github-auth-plugin/src/github-auth-plugin.ts
Exclude che-server requests from the GitHub authentication flow, instead read credentials file, mounted from the `github-credentials-secret` and extract the GitHub token.
fixes https://github.com/eclipse/che/issues/20995
fixes https://github.com/eclipse/che/issues/20788
1. Make sure that the GitHub is configured: https://www.eclipse.org/che/docs/next/administration-guide/configuring-authorization/#enabling-authentication-with-social-accounts-and-brokering_che
2. Create a factory with a private repo e.g. `<che-url>/#https://github.com/vinokurig/test-extension/tree/devfile2` to authenticate GitHub for the user namespace.
3. Run `Git: Clone` and input a git url to a private repo e.g. `https://github.com/vinokurig/test-extension.git`:
4. …
> chore: Rework GitHub authentication flow

- generator/tests/init-sources/templates/theia-core-package.json
- package.json
- yarn.lock
fix: CRW-2656 - include BOTH node-addon-api 1.7.2 and 3.1.0; remove refs to keytar 7.2.0 since we include 7.6.0
Change-Id: I833f9afc910c6ff986b8dd50775eec97d03542e1
N/A
https://issues.redhat.com/browse/CRW-2656?focusedCommentId=19630563&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19630563
According to https://medium.com/weekly-webtips/how-to-install-multiple-versions-of-the-same-package-in-npm-71c29b12e253 this is a reasonable way to hard-include two versions of a js package dependency.
See https://github.com/eclipse-che/che-theia/pull/1303
Reviewers, please …
> fix: CRW-2656 - include BOTH node-addon-api 1.7.2 and 3.1.0; remove refs to keytar 7.2.0 since we include 7.6.0

- dockerfiles/theia/Dockerfile
- package.json
- yarn.lock
- as far as I understand
`node-addon-api` and `node-addon-api-latest`are transitive dependencies. They were added to `devDependencies`section. I believe the dependencies should be removed from the `devDependencies` section.
- some time ago there were some problems in `theia` related to `keytar` version. They had to downgrade the dependency to 7.2.0 version. I think it makes sense to use the same version in `che-theia`.
> Use upstream version of keytar

- dockerfiles/build.include
- dockerfiles/theia/Dockerfile
- dockerfiles/theia/README.md
- generator/src/foreach_yarn
- generator/src/init.ts
- generator/src/unpack_che-theia_plugins
At the moment `Che-Theia` plugins are unpacked at starting IDE step. As result - we have a delay at that step. Please see https://github.com/eclipse/che/issues/20861#issuecomment-1018632823.
The PR allows:
- unpack `Che-Theia` plugins at building images step by default
- reduce the delay at starting IDE step
- ability to turn On and turn Off unpacking `Che-Theia` plugins at building images step
The side effect is - enlarged docker image.
Please see videos [here](https://github.com/eclipse/che/issues/20861#issuecomment-1018632823)
https://user-images.githubusercontent.com/5676062/151932025-b20be7d8-b9c3-444a-a792-00b630f1c559.mp4
https://github.com/eclipse/che/issues/20861
1. Try to build `eclipse/che-theia:next`image as usual, like `./build.sh --dockerfile:Dockerfile.alpine` from the …
> fix: Unpack Che-Theia plugins at building image step

- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-workspace-service-impl.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-command-filter.ts
- extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-quick-open.ts
- extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts
- add attributes of a component to `Container` object
- rename `Open Terminal in specific container` menu item to `New Terminal` - it should display **only** `Developer` containers at a terminal creation. The command creates a terminal in the editor container if there is no a `Developer` container.
- add a new command `New Terminal in specific container` - it should display **all** containers at a terminal creation.
- add a hotkey for the `New Terminal in specific container` command
- add `Show All Containers` item at displaying list of `Developer` containers. 
There are few ways to create a terminal in a `Developer` container:
- go to `Terminal` `=>` `New Terminal` menu item
- using a hotkey ``` ctrl+shift+` ```
- using the corresponding command `F1` `=>` `New Terminal` 
There are few …
> feat(terminal): Filter the containers list at a terminal creation

- make-release.sh
Change-Id:...
fix: typo in make-release.sh
Change-Id: Ida33c8ffff001568095d242ee2da0481f82c3494
N/A
N/A
> fix: typo in make-release.sh

- .github/workflows/check-theia-branch.yml
- .github/workflows/happy-path-tests.yaml
- .github/workflows/next-build.yml
- .github/workflows/pr-build.yml
- .github/workflows/publish-built-in-extension-report.yaml
- .github/workflows/release.yml
- dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile
- dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/Dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-setup.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-from.dockerfile
- dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-setup.dockerfile
- dockerfiles/theia/docker/alpine/build-result-from.dockerfile
- dockerfiles/theia/docker/alpine/runtime-from.dockerfile
- dockerfiles/theia/docker/ubi8/build-result-from.dockerfile
- dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
- generator/src/init.ts
- package.json
Che should use nodejs 14 as 12 is not maintained anymore
Also VS Code default node version is now v14
Fixes https://github.com/eclipse/che/issues/21150
Try to run a plug-in and theia
Like checking with a sample
example:
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=https://gist.githubusercontent.com/benoitf/e67f1be6ebad92ce7c7ae0c7a37cc5fe/raw/d43052559db5252571bf316bd674ef86d7f6a910/theia-editor.yaml
Change-Id: …
> feat: Use of nodejs 14 for the runtime

- plugins/workspace-plugin/src/workspace-projects-manager.ts
- plugins/workspace-plugin/tests/workspace-projects-manager.spec.ts
It's a backport of https://github.com/eclipse-che/che-theia/pull/1346 from 7.48.x to 7.46.x
> Prevent overwriting the DevWorkspace in-cluster object by a flattened Devfile

- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-certificate-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-server-https.ts
Signed-off-by: Fake Name <fake@example.com>
Adds `/etc/ssl/certs/ca-certificates.crt` certificate to the list of certificates of authority. 
It solves a problem with making requests to  the public resources like https://github.com/golang/vscode-go/releases/download/v0.23.0/go-0.23.0.vsix
https://user-images.githubusercontent.com/1271546/168074941-c7ee0409-48a0-41ae-b159-c6fea5491791.mp4
https://github.com/eclipse/che/issues/21381
- The test platform minikube
- Installation method: chectl
- Start the workspace via https://github.com/che-samples/bash/tree/devfilev2?che-editor=https://gist.githubusercontent.com/svor/afbea8fc7bad0d318f23c9491a5b2bde/raw/778e95e4b3ae2b7759a0da5589f05001f088b63c/che-theia.yaml
- Try to install plugins from the Plugin view
[As the author of this Pull Request I …
> chore: Add public root crt to the list to use it in Axios  

- plugins/containers-plugin/src/containers-service.ts
- plugins/containers-plugin/tests/containers-service.spec.ts
In the Workspace panel, hides the containers that are internals of the Che-Theia editor (with the `app.kubernetes.io/part-of: che-theia.eclipse.org` attribute).
closes https://github.com/eclipse/che/issues/21324 (https://issues.redhat.com/browse/CRW-3169)
Run
https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/azatsarynnyy/java-spring-petclinic/tree/theia-test
Make sure that there're no containers with the `app.kubernetes.io/part-of: che-theia.eclipse.org` attribute. E.g.: `machine-exec`, `telemetry-plugin`, etc.
**Note,** the Che-Theia build is failing ATM due to the OpenVSX outage https://github.com/eclipse/openvsx/issues/497
I was able to prepare the test image by disabling the built-in extensions …
> Filter the containers list in the Workspace panel

- extensions/eclipse-che-theia-remote-api/src/common/plugin-service-impl.ts
- extensions/eclipse-che-theia-remote-api/src/common/plugin-service.ts
- extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-plugin-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-plugin-service-impl.ts
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/devworkspace-template-with-inlined-che-theia-plugins.yaml
- extensions/eclipse-che-theia-remote-impl-k8s/tests/_data/devworkspace-template-with-inlined-extensions-json.yaml
- extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-plugin-service-impl.spec.ts
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com.com>
- If `.che/che-theia-plugins.yaml` file is inlined in the devfile, all the plugins will be marked as installed. Does the same when the devfile contains `.vscode/extensions.json`.
- For devworkspaces, switches to using `che-theia-plugin.yaml` instead of `meta.yaml`.
https://github.com/eclipse/che/issues/21423
To test the behavior with inlined `che-theia-plugins.yaml` create workspace with a factory
`che-url#https://github.com/vitaliy-guliy/web-nodejs-sample/tree/inlined-che-theia-plugins-yaml?che-editor=https://gist.githubusercontent.com/vitaliy-guliy/bc6ff64a716a30bfc7492cec9314f3cf/raw/abcfeff8ccc9a1992fa9a6d4fe7a7a558dc7b7df/editor.meta.yaml`
To test the behavior with inlined `extensions.json` use …
> chore: should be able to uninstall plugins if che-theia-plugins.yaml is inlined in the devfile
