eclipse-che/che-theia

extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-variables-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-variables-impl.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/plugin-api-impl.ts, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
Add CHE variables API
fixes https://github.com/eclipse/che/issues/11953
=> CHE-11953: Add variables API

extensions/eclipse-che-theia-plugin-ext/package.json
=> Update Theia version

extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-factory-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-workspace-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-factory.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-variables.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-workspace.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/node/che-api-node-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/webworker/che-api-worker-provider.ts, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
Adds implementation for
- get workspace by ID
- update workspace
Decouples Workspace and Factory APIs
=> Update Workspace plugin API

extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/src/browser/che-factory-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-variables-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-workspace-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-factory.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-variables.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-workspace.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/webworker/che-api-worker-provider.ts, extensions/eclipse-che-theia-plugin/package.json, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, extensions/eclipse-che-theia-plugin/src/che.d.ts, yarn.lock
Use interfaces from eclipse-che/api.
=> Use generated interfaces from eclipse-che/api

plugins/containers-plugin/package.json, plugins/containers-plugin/src/containers-tree-data-provider.ts
Rename servers to endpoints
fixes https://github.com/eclipse/che-theia/pull/13  'replace servers with endpoints'
=> Rename servers to endpoints

extensions/eclipse-che-theia-terminal/package.json
=> Improve terminal extension name and fix file attribute.

extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
is needed for https://github.com/eclipse/che-theia/pull/30
=> Adapt TaskConfiguration interface to master version

extensions/extensions.yml
Need for https://github.com/ws-skeleton/che-theia-generator/pull/15
=> Move che:theia generator config to che-theia repo

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia/.gitignore, dockerfiles/theia/Dockerfile, dockerfiles/theia/build.sh
This pull use new version of `che:theia` generator and own `extensions.yml` for extensions
=> Use new che:theia generator

.gitignore, extensions/eclipse-che-theia-plugin-ext/src/browser/che-ssh-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-ssh.ts, extensions/eclipse-che-theia-plugin-ext/webpack.config.js, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>
=> Add ssh plugin: API part

.travis.yml, build_and_push_docker_images.sh, che-plugins/che-editor-theia/etc/che-plugin.yaml, dockerfiles/theia/build.sh
=> Push docker images on each master build

build_and_push_docker_images.sh, dockerfiles/remote-plugin-runner-java8/build.sh, dockerfiles/theia-endpoint-runtime/.gitignore, dockerfiles/theia-endpoint-runtime/Dockerfile, dockerfiles/theia-endpoint-runtime/package.json, extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, extensions/eclipse-che-theia-terminal/package.json, package.json, yarn.lock
=> build and publish remote-plugin-runner-java8 image

.travis.yml, dockerfiles/theia-endpoint-runtime/Dockerfile, dockerfiles/theia-endpoint-runtime/build.sh, plugins/factory-plugin/package.json
=> fix build theia-endpoint-runtime image

.travis.yml
=> fix ci again

dockerfiles/theia-endpoint-runtime/yarn.lock, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
Adds methods to use Che client preferences API
=> Add Che preferences API

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia/Dockerfile, dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
=> Use new version of che:theia generator, and remove jdk

build_and_push_docker_images.sh, dockerfiles/remote-plugin-go-1.10.7/Dockerfile, dockerfiles/remote-plugin-go-1.10.7/build.sh
=> Add Dockerfile to build image for go plugin

dockerfiles/theia/Dockerfile, plugins/containers-plugin/src/containers-service.ts, plugins/containers-plugin/src/containers-tree-data-provider.ts
Add improvements for the containers plugin
https://github.com/eclipse/che-theia/issues/21
https://youtu.be/wPU8_FCws6Y
=> add improvements for the containers plugin

dockerfiles/theia-endpoint-runtime/src/node/hosted-plugin-remote.ts, dockerfiles/theia-endpoint-runtime/src/node/websocket.ts
Add reconnect mechanism on websockets
=> Fix #62: handle connection refused error and reconnect on websockets

dockerfiles/remote-plugin-go-1.10.7/Dockerfile, dockerfiles/remote-plugin-runner-java8/Dockerfile
=> Fix build tag

build_and_push_docker_images.sh, dockerfiles/remote-plugin-python-3.7.2/Dockerfile, dockerfiles/remote-plugin-python-3.7.2/build.sh
VS Code python extension [1]
Is needed for [2] 
[1] https://marketplace.visualstudio.com/items?itemName=ms-python.python
[2] https://github.com/eclipse/che/issues/12771
=> Add Dockerfile for VS Code python extension

plugins/task-plugin/src/machine/attach-client.ts, plugins/task-plugin/src/machine/machine-exec-client.ts
=> Fix connection urls for Minikube.

dockerfiles/theia-endpoint-runtime/src/node/plugin-remote-init.ts, dockerfiles/theia-endpoint-runtime/src/node/terminal-container-aware.ts
https://github.com/eclipse/che/issues/12771
=> Override terminal creation options

plugins/task-plugin/package.json, plugins/task-plugin/tsconfig.json, yarn.lock
=> Add missing dependencies for task plugin

dockerfiles/theia-dev/e2e/Dockerfile, dockerfiles/theia/Dockerfile
=> Use new Theia release to build and validate images

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia/e2e/cypress/integration/theia/commands.spec.ts
List of versions:
https://www.npmjs.com/package/@eclipse-che/theia-generator
=> Use latest theia-generator version

plugins/task-plugin/package.json, yarn.lock
=> Fix dependencies for task plugin

dockerfiles/theia/Dockerfile
=> Invalidate docker cache during plugin code clone

extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
https://github.com/eclipse/che-theia/issues/111
=> Fix send text for plugin api.

dockerfiles/theia-endpoint-runtime/Dockerfile, dockerfiles/theia-endpoint-runtime/etc/entrypoint.sh
so we have a valid username on openshift platforms (like on main theia instance)
Change-Id: I0a8a3811efc80fc7381160b3b6c1e65e0540a57a
=> Add entrypoint that will add correct user/group for random userids on openshift

extensions/eclipse-che-theia-user-preferences/package.json, extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts, yarn.lock
https://github.com/theia-ide/theia/pull/4128
Change-Id: I9c4e0915211c72bbc47bd154bcaff8a060bd8e09
=> Now Theia is using nfsw directly

dockerfiles/theia-endpoint-runtime/src/node/terminal-container-aware.ts
Fix terminal creation for remote plugins.
https://github.com/eclipse/che-theia/issues/112
=> Fix terminal creation for remote plugins.

plugins/containers-plugin/src/containers-service.ts
Attaches commands from plug-ins which are defined in devfile to right container in the `Containers` panel.
https://github.com/eclipse/che-theia/issues/104
=> Use runtime configuration while attaching command to container

dockerfiles/remote-plugin-go-1.10.7/.gitignore, dockerfiles/theia-dev/Dockerfile, dockerfiles/theia-dev/e2e/Dockerfile, dockerfiles/theia-endpoint-runtime/Dockerfile, dockerfiles/theia/Dockerfile
As this https://github.com/theia-ide/theia/pull/4750 pull request are merged, I update Node.JS version in our images
=> Use node 10.2.1 for che-theia images

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia/.gitignore, dockerfiles/theia/e2e/Dockerfile, extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts, extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-quick-open.ts, yarn.lock
Fix build, add some missing native libs in `che-theia-dev` image
=> Fix build according to new Theia API, fix docker build

extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
Fix terminal shortCut for Mac.
https://github.com/eclipse/che-theia/issues/135
=> Fix terminal shortCut for Mac.

extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, yarn.lock
We need these changes to align task configuration with theia object after https://github.com/theia-ide/theia/pull/4847
=> Align task configuration with theia object

dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
This PR fixes build and adapts .Net runtime image to Alpine 3.9
=> Adapt .Net remote docker image to Alpine 3.9; Fix build

extensions/eclipse-che-theia-plugin-ext/webpack.config.js, yarn.lock
Add same `node` preferences as [Theia has ](https://github.com/theia-ide/theia/blob/master/dev-packages/application-manager/src/generator/webpack-generator.ts#L62)
=> Fix webpack config to fix build

extensions/eclipse-che-theia-dashboard/src/browser/che-theia-dashboard-frontend-contribution.ts, extensions/eclipse-che-theia-dashboard/src/browser/che-theia-dashboard-module.ts, extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts
* Adds menu entry item 'Share'. Click on it redirects a user to the Workspace Overview page where a workspace could be shared from.
* Collapses Dashboard navbar when Che Theia IDE is loaded
fix https://github.com/eclipse/che/issues/12722
fix https://github.com/eclipse/che/issues/12822
=> Added ability to redirect a user to Workspace Overview page

extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-client.ts
At the moment remote plugins can override task plugin handlers.
This way is described [here](https://github.com/eclipse/che-theia/issues/155#issuecomment-482510278).
The PR allows to handle all set subscribed handlers.  
https://github.com/eclipse/che-theia/issues/155
=> Do not override task plugin handlers

extensions/che-theia-hosted-plugin-manager-extension/src/node/che-workspace-hosted-plugin-uri-post-processor.ts, yarn.lock
This pull add implementation if one method that missing to restore build
=> Fix build according to Theia upstream changes

plugins/containers-plugin/package.json, plugins/containers-plugin/src/containers-service.ts, plugins/factory-plugin/package.json, plugins/factory-plugin/src/factory-plugin.ts, plugins/factory-plugin/src/projects.ts, plugins/factory-plugin/src/theia-commands.ts, plugins/factory-plugin/src/workspace-projects-manager.ts, plugins/factory-plugin/tests/git.spec.ts, plugins/factory-plugin/tests/projects.spec.ts, yarn.lock
Adds functionality to support devfile configuration of workspace on Theia UI. So now it supports both: devfile and workspace config.
The changes is mostly about projects sync between Theia and devfile projects section.
Also adds small changed to workspace panel to be able to show appropriate info from devfile. But with current state we cannot get information about volumes, so in case of devfile config the information about volumes is missing for now. See https://github.com/eclipse/che/issues/13290.
https://github.com/eclipse/che/issues/13112
=> CHE-13112: Respect workspaces based on devfile in Che Theia IDE UI

build_and_push_docker_images.sh
Enables building & pushing an image for the Kubernetes plugin 1.0.0 to DockerHub.
=> Enable build & push an image for the Kubernetes plugin 1.0.0 to DockerHub

plugins/factory-plugin/src/projects.ts
Fixup for https://github.com/eclipse/che-theia/pull/221 which corrects project deletion from devfile in case of the project deletion from filesystem.
=> Fix deletion of projects from devfile configuration

build_and_push_docker_images.sh, dockerfiles/remote-plugin-openshift-connector-0.0.21/Dockerfile, dockerfiles/remote-plugin-openshift-connector-0.0.21/build.sh
Adds Dockerfile for running OpenShift Connector Che Plugin v0.0.21
https://github.com/eclipse/che/issues/13379 partly
A related PR for plugin-registry will be opened once an image is built&pushed on DockerHub
=> Add Dockerfile for running OpenShift Connector Che Plugin v0.0.21

extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
Fix duplication typing after terminal reconnection.
https://github.com/eclipse/che/issues/13165
=> Fix duplication typing after terminal reconnection.

build_and_push_docker_images.sh, docker_image_build.include, set_theia_version.sh
=> add script for changing che-theia version

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia/Dockerfile, extensions/che-theia-hosted-plugin-manager-extension/package.json, extensions/che-theia-hosted-plugin-manager-extension/src/node/che-workspace-hosted-plugin-uri-post-processor.ts, extensions/che-theia-hosted-plugin-manager-extension/src/node/hosted-plugin-manager-contribution-extension-backend-module.ts, extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts, yarn.lock
Update che-theia generator, and fix all compilation error
=> Fix build according to Theia refactoring

extensions/eclipse-che-theia-plugin-ext/package.json, yarn.lock
=> Remove 'ts-node' dependency

dockerfiles/theia/Dockerfile
=> Set default Theia version to 'master'

build_and_push_docker_images.sh, docker_image_build.include
Add php-image for PHP remote plugins into build_and_publish script
https://github.com/eclipse/che-theia/issues/272
=> Add php-image into build_and_publish script

extensions/eclipse-che-theia-activity-tracker/package.json, extensions/eclipse-che-theia-dashboard/package.json, extensions/eclipse-che-theia-preferences-provider-extension/package.json, extensions/eclipse-che-theia-user-preferences/package.json
Add `"license" : "EPL-2.0"` to some `package.json`s
None.
=> Add the "license" key-value.

README.md
=> README badges: use right labels for question/bug

dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile, dockerfiles/theia-dev/Dockerfile, dockerfiles/theia-endpoint-runtime/Dockerfile, dockerfiles/theia/Dockerfile
Upgrades to newer `node`.
None.
=> [node] Use version 10.16.

dockerfiles/remote-plugin-dependency-analytics-0.0.12/build.sh
=> Add version for dependency-analytics remote plugin

plugins/task-plugin/package.json, set_theia_version.sh
This PR is part of preparation to have proper release
=> fix set_theia_version script, set inversify version to '4.14.0'

dockerfiles/theia/Dockerfile
Add latest Yeoman Theia plugin and Yeoman generator
=> Add latest yeoman plugin and generator

dockerfiles/theia-dev/Dockerfile
Update version of `@eclipse-che/theia-generator`.
=> Update version of @eclipse-che/theia-generator

extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Makes Plugins panel working for workspaces based on devfiles.
Works properly with workspaces having workspace config.
https://github.com/eclipse/che/issues/13747
https://github.com/eclipse/che/issues/13669
=> Devfile plugins

plugins/factory-plugin/src/theia-commands.ts
Use native git instead of git plugin in the factory plugin
fixes https://github.com/eclipse/che/issues/13796
=> Use native git instead of git plugin in the factory plugin

dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Fix `/go/pkg` folder permissions to allow LS to install dependencies.
https://github.com/eclipse/che/issues/13823
=> Fix /go/pkg folder permissions

extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Original PR merged in `master` https://github.com/eclipse/che-theia/pull/343
Makes Plugins panel working for workspaces based on devfiles.
Works properly with workspaces having workspace config.
https://github.com/eclipse/che/issues/13747
https://github.com/eclipse/che/issues/13669
=> Fix devfile plugins 7.0.0

.github/CODEOWNERS
Update CODEOWNERS sub sections
=> Update CODEOWNERS subsections for the Endgame

dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Fix permissions for `/go/pkg` folder
https://github.com/eclipse/che/issues/13823
=> Fix /go/pkg folder permissions (#348)

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
Removes hardcoded dummy plugin registry 
https://github.com/eclipse/che/issues/13904
=> Remove dummy plugin registry

plugins/ssh-plugin/package.json, plugins/ssh-plugin/src/ssh-plugin-backend.ts, yarn.lock
Store SSH private key file on the file system when key is generated from the SSH Plugin
PR to master: https://github.com/eclipse/che-theia/pull/352
fixes eclipse/che#13866
=> Store SSH private key on the file system from SSH plugin

plugins/task-plugin/src/machine/machine-exec-client.ts
Fix auth for task plugin task exited feature.
https://github.com/eclipse/che/issues/13970
=> Fix auth for task plugin task exited feature.

plugins/task-plugin/src/machine/machine-exec-client.ts
- Fix displaying theia tasks output;
- Don't use in the code concrete remote terminal implementation, use interface.
- Che-theia tasks - works;
- Che-theia terminal - works;
- Che-theia terminal plugin api - works;
- Theia tasks - works;
https://github.com/eclipse/che/issues/13876
=> Fix auth for task plugin task exited feature. (#371) (Cherry-pick to 7.0.0.)

generator/src/conf/.yarnclean
Fix che-theia-generator command che:theia clean
https://github.com/eclipse/che/issues/14047
=> CHE-14047: Fix che-theia-generator command che:theia clean

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts
cherry-pick https://github.com/eclipse/che-theia/pull/372/commits/5794953182bc2e32fff8d1fe9812f4043eb991f8 into [7.0.0](https://github.com/eclipse/che-theia/tree/7.0.0)
=> fix reloading Che Theia within iframe

dockerfiles/theia/build.sh, dockerfiles/theia/push-cdn-files-to-akamai.sh
Remove check on unused variable, to enable pushing to CDN
eclipse/che#14039
=> push to CDN on each build

dockerfiles/theia/build.sh, dockerfiles/theia/push-cdn-files-to-akamai.sh
Cherry-pick of https://github.com/eclipse/che-theia/pull/385
=> push to CDN on each build (#385)

devfiles/che-theia-all.devfile.yaml
Add more ram to build che-theia and more ram for che-theia hosted instance debug.
=> Add more ram to build che-theia and more ram for che-theia hosted instance.

dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
change cypress selector for 'Explorer' view to fix e2e test
=> change cypress selector for 'Explorer' view

dockerfiles/theia-dev/build.sh
Fixes broken code in `theia-dev/build.sh`.
fixes eclipse/che#14120.
=> Fix to create `eclipse-che-theia-generator.tgz`. (eclipse/che#14120)

dockerfiles/theia/README.md
Updates documentation explaining how to build docker images.
https://github.com/eclipse/che/issues/14053
=> Update theia-dev doc

generator/src/templates/assembly-package.mst, generator/tests/init-sources/assembly-example/assembly-package.json, generator/tests/production/assembly/package.json
Removes @theia/cpp extension
https://github.com/eclipse/che/issues/13698
=> Remove @theia/cpp extension in favor of plugin

extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-variables-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-devfile.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-factory.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-ssh.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-user.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-variables.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-workspace.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/node/che-api-node-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/webworker/che-api-worker-provider.ts, extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts, yarn.lock
Fix imports according to https://github.com/theia-ide/theia/pull/5464 upstream changes.
> Please do not merge until https://github.com/theia-ide/theia/pull/5464 is merged
https://github.com/theia-ide/theia/issues/3871
=> replace 'api' with 'common' in imports of Theia API

dockerfiles/theia/e2e/src/package.json, extensions/eclipse-che-theia-plugin-ext/package.json, generator/package.json, yarn.lock
Upgrades some node packages that are marked as vulnerable and Eclipse CQ approved.
None.
=> Upgrade node packages

extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts, yarn.lock
Add implementation of 'getPluginDependencies', to restore build
=> Add implementation of 'getPluginDependencies'

README.md
Fixes alignment of Che and Theia logos in README.md by applying the same height.
See [how it was before](https://github.com/eclipse/che-theia/blob/master/README.md).
=> Logo alignment

extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts, yarn.lock
Fix che-theia build after upstream change https://github.com/theia-ide/theia/pull/6038
none.
=> Fix build.

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx, extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Displays dropdown with available versions for each plugin. 
https://github.com/eclipse/che/issues/13913
=> Makes it possible to change installed plugin version

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Solves feedbacks for the PR https://github.com/eclipse/che-theia/pull/417
It was occasionally merged.
https://github.com/eclipse/che/issues/13913
=> Plugin Versions: solve feedbacks

plugins/containers-plugin/src/containers-service.ts, plugins/containers-plugin/src/containers-tree-data-provider.ts
In the "My Workspace"-view on the right side, there are commands shown. This PR adds a command-line into each workspace command tooltip.
https://github.com/eclipse/che/issues/13149
=> Add a command-line into workspace command tooltip

extensions/eclipse-che-theia-about/scripts/generate-about-details.js, extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts
Fixes broken link to commit from which Che Theia was built.
Also opens the commit in separate tab instead of replacing the IDE.
Privides fix for https://github.com/eclipse/che/issues/14092
=> Fix commit reference in the About dialog

extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts, yarn.lock
Quick and dirty fix to restore build
eclipse/che#14618
=> Fix build by calling internal method

extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
Fix remote plugin/workspace start
eclipse/che#14645
=> Fix undefined error

docker_image_build.include, dockerfiles/theia/Dockerfile, extensions/che-theia-hosted-plugin-manager-extension/package.json, extensions/eclipse-che-theia-about/package.json, extensions/eclipse-che-theia-activity-tracker/package.json, extensions/eclipse-che-theia-git-provisioner/package.json, extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-frontend-service.ts, extensions/eclipse-che-theia-plugin-remote/package.json, extensions/eclipse-che-theia-plugin-remote/src/node/hosted-plugin-remote.ts, extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts, extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts, extensions/eclipse-che-theia-plugin-remote/src/node/server-plugin-proxy-runner.ts, extensions/eclipse-che-theia-plugin-remote/src/node/terminal-container-aware.ts, extensions/eclipse-che-theia-preferences-provider-extension/package.json, extensions/eclipse-che-theia-terminal/package.json, extensions/eclipse-che-theia-user-preferences/package.json, plugins/containers-plugin/package.json, plugins/factory-plugin/package.json, plugins/ports-plugin/package.json, plugins/ssh-plugin/package.json, plugins/task-plugin/package.json, plugins/welcome-plugin/package.json, yarn.lock
Make remote extension compliant with upstream theia
Some changes were made in Eclipse Theia upstream that broke totally the remote extensions
Fix in upstream performed there: https://github.com/eclipse-theia/theia/pull/6301
https://github.com/eclipse/che/issues/14685
Change-Id: Id5cb613ca44e3e86ed22000ab2dd674f8dce4f91
=> Use of theia upstream master branch

plugins/containers-plugin/src/containers-service.ts
This PR sorts container's commands in alphabetical order
https://github.com/eclipse/che/issues/14000
=> Sort runtime's commands

plugins/ssh-plugin/src/ssh-plugin-backend.ts
Apply SSH generate/create key name validation
fixes https://github.com/eclipse/che/issues/14218
depends on https://github.com/eclipse-theia/theia/issues/6245
=> Apply SSH generate/create key name validation

plugins/task-plugin/package.json, yarn.lock
Upgrade vscode-ws-jsonrpc version
Fixes https://github.com/eclipse/che/issues/14724
https://github.com/eclipse/che/issues/14724
Run any che task.
You should get pop-up when the task is completed.  
=> Upgrade vscode-ws-jsonrpc version

docker_image_build.include, dockerfiles/remote-plugin-openshift-connector-0.1.0/Dockerfile, dockerfiles/remote-plugin-openshift-connector-0.1.0/build.sh
Adds Dockerfile for building an image for OpenShift Connector Che Plugin v0.1.0.
See https://github.com/eclipse/che-plugin-registry/pull/238
https://github.com/eclipse/che/issues/14605
https://github.com/eclipse/che/issues/14287
=> Add Dockerfile for OpenShift Connector plugin v0.1.0 image

plugins/containers-plugin/src/containers-tree-data-provider.ts
Align `source` for che tasks with theia project. 
Fixes https://github.com/eclipse/che/issues/14770 
https://github.com/eclipse/che/issues/14770
Try to run any che task from `My Workspace` panel
=> Use root uri as source for tasks

dockerfiles/remote-plugin-openshift-connector-0.1.0/Dockerfile
Updates the parent image for `remote-plugin-openshift-connector-0.1.0` since I've committed it by mistake with my previous PR.
=> Change a parent image for remote-plugin-openshift-connector-0.1.0

docker_image_build.include
=> feat(core): add Camel K docker file to the list of image to build

extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, plugins/task-plugin/src/task/converter.ts, yarn.lock
Add _scope to TaskConfiguration to fix build
=> Add _scope to TaskConfiguration

yarn.lock
Upgrade dependency (to remove an unwanted 3rd party dependency)
related to https://github.com/eclipse/che/issues/14804
Change-Id: I5eb908b1b121e675e1ff1ca18ea03ea37504aadf
=> fix(dependencies): Update che-workspace-client dependency to remove github dependency

.gitignore, dockerfiles/theia/build.sh, extensions/eclipse-che-theia-about/scripts/generate-about-details.js, extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts
fix about dialog properties
for now theia and che-theia have same sha1 !
N/A
=> fix(about-dialog): Wrong sha1 and repository link

devfiles/che-theia-all.devfile.yaml, extensions/eclipse-che-theia-plugin-remote/devfile.yaml
Fix `Generate Hello World plugin package` command for remote endpoint devfile. Use next editor for che-theia devfile.
none. Development enhancements.
=> Fix and improve devfiles.

build.include
=> Fix publish images function

dockerfiles/theia/Dockerfile
Add VS Code yeoman generator
N/A
Change-Id: I1484e51ee555d7ed424c16cd5ec21c39e2958103
=> feat(theia-image): Add code yeoman generator to generate VS Code extensions

plugins/factory-plugin/package.json, plugins/factory-plugin/src/git.ts, plugins/factory-plugin/src/theia-commands.ts, yarn.lock
Implements sparse checkout feature for git type of projects.
Implements frontend part of https://github.com/eclipse/che/issues/13671
Sparse checkout feature is added for git type of projects
https://github.com/eclipse/che-docs/pull/842
=> Handle sparseCheckoutDir parameter of project source in devfile

extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-github-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-github.ts, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, plugins/ssh-plugin/package.json, plugins/ssh-plugin/src/ssh-plugin-backend.ts
In case when git clone by ssh url has failed by permission error, ask to upload an SSH public key to GitHub and try again. In case when push by ssh url has failed, ask to upload an SSH public key and show a notification to retry push. Authenticate to GitHub by oAuth if needed.
**HOW TO TEST**
1. Try to clone (`F1 => Git: Clone`) a GitHub repository by SSH url => See a notification that asks to generate if needed and upload public SSH key to GitHub. The clone will be restarted automatically.
2. Try to push (`F1 => Git: Push`) from a git repository without public SSH key in the GitHub => See a notification that asks to generate if needed and upload public SSH key to GitHub. The push command will not be restarted automatically.
https://github.com/eclipse/che/issues/14615
=> CHE-14615 Apply automatic SSH public key upload to GitHub

dockerfiles/theia/Dockerfile
They're not included in Che-Theia, so avoid to download/compile dependencies.
N/A
Change-Id: I441cb489c5553e62d26a77945b2954a3d3ea7a6c
=> chore(build): Remove some folders that don't need to be compiled

build.include
Fix publishing `next` docker images
=> Fix image name

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile, dockerfiles/theia-endpoint-runtime/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-install-dependencies.dockerfile
This reverts commit bd08f269f8dcab8a66d750225ab6d9d620626c6c.
It has been merged without any approval
https://github.com/eclipse/che-theia/pull/507
=> Revert "add URL from which container is fetched so... (#507)"

extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote.ts
This PR adds handling of unhandled promises rejection (like it is already done on Theia side) in Che Theia remote plugin nodejs instance. The fix prevents crash of the remote plugin runtime in case if a plugin throws an exception to plugin API code.
The problem was found while working on https://github.com/eclipse/che/issues/14942
=> Prevent remote plugin nodejs instance crash in case of unhandled exception inside a plugin

build.include, extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-content-reader-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-resource.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-content-reader.ts, extensions/eclipse-che-theia-plugin-remote/src/node/che-content-aware-utils.ts, extensions/eclipse-che-theia-plugin-remote/src/node/document-container-aware.ts, extensions/eclipse-che-theia-plugin-remote/src/node/languages-container-aware.ts, extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
Allows to open file in the Theia IDE from a sidecar container.
https://github.com/eclipse/che/issues/13614
=> Allow to open file in the Theia IDE from a sidecar container

generator/src/templates/assembly-package.mst
Signed-off-by: Michal Vala <mvala@redhat.com>
As a part of workspace monitoring effort we would need to enable metrics plugin in che-theia.
https://github.com/eclipse/che/issues/13270
https://github.com/eclipse/che/issues/14888
n/a
n/a
=> add metrics plugin

dockerfiles/theia-dev/Dockerfile
Remove che-theia generator archive from theia-dev image after installation.
None. Clean up.
=> Remove che-theia generator archive from theia-dev image after installation.

build.include, dockerfiles/remote-plugin-camelk-0.0.10/Dockerfile, dockerfiles/remote-plugin-camelk-0.0.10/build.sh
Tooling extension eclipse/che#15086
eclipse/che#15086
=> feat(core) Use a newer Kamel executable for the latest VS Code Camel K

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx, extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css
Signed-off-by: che <che@eclipse.org>
Fixes notification text in the Plugins view 
https://github.com/eclipse/che/issues/15045
=> Fix notification in Plugins view

extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-https.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Fix get plugins from theia-ide does not work if che deployed with switched on TLS
CRW-466
=> Use self signed certificate when do request to plugin registry

extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-https.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Cherry-pick of https://github.com/eclipse/che-theia/pull/539
CRW-466
=> Use self signed certificate when do request to plugin registry (#539)

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-widget.tsx, extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css
Asks the Dashboard to restart the workspace after plugin installation. 
https://github.com/eclipse/che/issues/15006
=> Use dashboard to restart the workspace

extensions/eclipse-che-theia-user-preferences/package.json, extensions/eclipse-che-theia-user-preferences/src/browser/che-theia-user-preferences-frontend-module.ts, extensions/eclipse-che-theia-user-preferences/src/browser/theme/theme-preferences.ts, extensions/eclipse-che-theia-user-preferences/src/browser/theme/theme-synchronizer.ts
Persist Theia theme in user preferences
eclipse/che#15104
=> Persist Theia theme in user preferences

plugins/welcome-plugin/resources/welcome-page.css, plugins/welcome-plugin/src/welcome-page.ts
Removes blinking of product logo in Welcome page when loading Theia.
https://github.com/eclipse/che/issues/15100
https://github.com/eclipse/che/issues/15197
=> Prevent blinking of product logo in Welcome page

extensions/eclipse-che-theia-plugin-ext/package.json, generator/package.json, generator/tests/init-sources/init-sources.spec.ts, plugins/ssh-plugin/package.json, yarn.lock
Upgrade 'axios' to 0.19.0
eclipse/che#14676
=> Upgrade 'axios' to 0.19.0

plugins/ssh-plugin/src/ssh-plugin-backend.ts
This changes proposal add an ability to use theia api proposed in PR: https://github.com/eclipse-theia/theia/pull/6554 to upload private ssh key using new action item located in command list.
Demo of usage:
Linked PR: https://github.com/eclipse-theia/theia/pull/6554
https://github.com/eclipse/che/issues/14911
Add an ability to upload private SSH keys
=> Upload private ssh key

yarn.lock
needs to update yarn.lock dependencies to take these new changes else we're still stuck to old versions
CI builds
Change-Id: If07fb47ccfb0f81e4db3fe91fa58abbdd4c68fa4
=> fix(dependencies): needs to update yarn.lock dependencies to use upstream enhancements

extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-frontend-contribution.ts, extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-preferences.ts, extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-service.ts, extensions/eclipse-che-theia-user-preferences/src/browser/che-theia-user-preferences-frontend-module.ts, extensions/eclipse-che-theia-user-preferences/src/browser/theme/theme-preferences.ts, extensions/eclipse-che-theia-user-preferences/src/browser/theme/theme-synchronizer.ts, extensions/eclipse-che-theia-user-preferences/src/common/storage-server.ts, extensions/eclipse-che-theia-user-preferences/src/node/che-storage-server.ts, extensions/eclipse-che-theia-user-preferences/src/node/che-theia-user-preferences-backend-module.ts
Implements 'StorageService' to store Theia state in workspace. Before Theia uses browser `LocalStorage` to store it state, but in Che after each workspace start html page with Theia has different host, so we loose that state. With this PR we store state inside workspace.
=> Implement 'StorageService' to store Theia state in workspace

plugins/containers-plugin/src/containers-service.ts
Locate kubernetes tasks under corresponding containers
For example:
```
components:
-
type: kubernetes
alias: go-k8s
mountSources: true
referenceContent: |
kind: List
items:
- kind: Pod
apiVersion: v1
metadata:
name: go-runner
spec:
containers:
- name: go-110-server
image: quay.io/eclipse/che-golang-1.10:nightly
- name: go-112-server
image: quay.io/eclipse/che-golang-1.12:nightly
commands:
- name: test k8s component
previewUrl:
port: 8080
path: /hello
actions:
-
type: exec
component: go-k8s
command: "go run main.go 8080 /hello"
workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server
```
Before the PR changes:
After:
https://github.com/eclipse/che/issues/15042
1. Use the following devfile, which contains the reference for image with changes related to the current PR (you can check it using `Help=> …
=> Locate kubernetes tasks under corresponding containers

dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile, dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile
Bring git help man pages in theia-dev container
Fixes https://github.com/eclipse/che/issues/15161
Change-Id: Ieb72135418c88e17684427e7b7de638694b9e247
=> feat(git): Add git man pages in theia-dev container

plugins/welcome-plugin/resources/welcome-page.css
Recovery welcome plugin styles after changing webview implementation.
https://github.com/eclipse/che/issues/13442 
https://github.com/eclipse/che/issues/15334
=> Recovery welcome plugin styles after changing webview implementation.

dockerfiles/theia-dev/Dockerfile
Adds VS Code extension packager to `theia-dev` container.
https://github.com/eclipse/che/issues/14228
=> Add VS Code extension packager

plugins/task-plugin/src/task/che-task-provider.ts, plugins/task-plugin/src/task/che-task-runner.ts
Fix che tasks after changes in Theia
=> Fix che tasks after changes in Theia

dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
Fix the previous html selector
e2e test
Change-Id: I4c25ebf8c970815f57104b1ce925beaba47cd0d1
=> fix(e2e): Update selector entry

RELEASE.md
Provides `RELEASE.md` file with the release instructions.
https://github.com/eclipse/che/issues/15506
=> Release instructions

.github/CODEOWNERS
Update code owners to match new teams
N/A
=> chore(github): Update code owners of che-theia repository

extensions/eclipse-che-theia-plugin-ext/src/browser/che-frontend-module.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/style/tasks.css, extensions/eclipse-che-theia-plugin-ext/src/browser/task-status-handler.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-task-service.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-task-impl.ts, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, plugins/task-plugin/src/che-task-backend-module.ts, plugins/task-plugin/src/task-plugin-backend.ts, plugins/task-plugin/src/task/che-task-runner.ts, plugins/task-plugin/src/task/task-status.ts, yarn.lock
Set task status to the corresponding terminal widget when a task is completed
Please see the video: https://youtu.be/q1aBmr2bkUs
https://github.com/eclipse/che/issues/14132
=> Set task status when a task is completed

extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-telemetry-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-telemetry.ts, extensions/eclipse-che-theia-plugin-remote/src/node/execute-command-container-aware.ts, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, plugins/telemetry-plugin/src/telemetry-plugin.ts
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
Track 'git commit' and 'git push' commands and push corresponded telemetry events
eclipse/che#15622
=> Track 'git commit' and 'git push' commands and push corresponded telemetry events

dockerfiles/theia/Dockerfile, generator/package.json, generator/src/init-sources.ts, generator/src/init.ts, generator/src/templates/assembly-compile.tsconfig.json, generator/tests/init-sources/assembly-example/configs/root-compilation.tsconfig.json, generator/tsconfig.json, package.json, yarn.lock
yarn.lock is using old dependencies, regenerate it
remove from root-config some external files
https://github.com/eclipse/che/issues/15851
=> Update to latest theia upstream

generator/src/scripts/override-vs-loader.js
This PR is required to also fix the CDN support of static artifacts that are related to the Monaco editor.
This PR is a follow up of PR https://github.com/eclipse/che-theia/pull/607
=> Also rename the zip of the monaco vs loader

extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
To avoid spamming in log will create telemetry client on start and use it. 
Look like no sense create new one ob each event.
https://github.com/eclipse/che/issues/15923
=> Create telemetry client on start

dockerfiles/theia/README.md
Add `--dockerfile` param
N/A
Change-Id: Ia3525137ef443d42030240b034523d34bad4a1ce
=> docs(README): Add section about --dockerfile parameter for theia build docker image

extensions/eclipse-che-theia-plugin-ext/src/node/che-client-ip-service.ts
fix for https://github.com/eclipse/che-theia/pull/624
eclipse/che#15624
=> Try to get client IP from header 'x-forwarded-for'

extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts, extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts, yarn.lock
Recovery terminal and activate terminal search.
none. Reaction on upstream feature.
=> Activate terminal search.

extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts, extensions/eclipse-che-theia-user-preferences/src/browser/che-storage-service.ts
=> Fix formatting issue

cico_build_nightly.sh
Do nothing for now on nigthly jobs as it may push invalid artifacts/docker images
N/A
Change-Id: I0743c5b1ca95ebbe0fc57ed6ca85e2a5a9b4c335
=> fix(nightly): add no-op for nightly build

generator/src/templates/theiaPlugins.json
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>
(cherry picked from commit 1d4267cd5fa5c7a861df00487e5a484ec14729e6)
This PR is just a cherry-pick of https://github.com/eclipse/che-theia/pull/648 into the 7.9.x branch
=> Add in vscode-builtin-php

extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts, yarn.lock
Fix build
N/A
Change-Id: Ica616a2fa4a9e9bd5fcf059b912db56d05f2c79e
=> fix(build): Update the import path due to upstream breaking change

extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts, yarn.lock
Upstream theia reverted a change
https://github.com/eclipse-theia/theia/pull/7276
Change-Id: Ib2a8347e40981288e711057d1d40de619284660b
=> fix(revert): Upstream theia reverted a breaking changes

extensions/eclipse-che-theia-about/package.json, extensions/eclipse-che-theia-activity-tracker/package.json, extensions/eclipse-che-theia-dashboard/package.json, extensions/eclipse-che-theia-logging/package.json, extensions/eclipse-che-theia-preferences-provider-extension/package.json
Change-Id: Ibdd0bfe5ab80818dc3fba4b879dd1d6a77ee717e
Use same range of dependencies
Fix https://github.com/eclipse/che/issues/16337
=> fix(dependencies): Use same dependencies everywhere

dockerfiles/theia/build.sh
Includes the latest version of `@theia/yeoman-plugin` to Che-Theia build.
It's cherry-picking of the commit from the PR https://github.com/eclipse/che-theia/pull/666
https://github.com/eclipse/che/issues/16354
=> Use the latest yeoman-plugin

plugins/workspace-plugin/src/theia-commands.ts
Backports https://github.com/eclipse/che-theia/pull/672 into 7.9.x branch
=> Fix import of zip project which hosted with cluster self-signed certificate

cico_build_master.sh, cico_common.sh, extensions/eclipse-che-theia-about/package.json
This PR actually a copy of https://github.com/eclipse/che-theia/pull/617 but with disabled publishing of `@eclipse-che/theia-about` module as it causes the error on CI https://ci.centos.org/view/Devtools/job/devtools-che-theia-che-nightly/60/consoleFull
`@eclipse-che/theia-about: [compile] src/browser/about-che-theia-dialog.ts(14,44): error TS2307: Cannot find module '@eclipse-che/theia-plugin-ext/lib/common/che-protocol'.`
The modules what will be published:
- [`@eclipse-che/plugin`](https://github.com/eclipse/che-theia/blob/4c09edcde15018a55faadc55164222b55eab9b3e/extensions/eclipse-che-theia-plugin/package.json#L21) - provides Che specific Theia Plugin API
- [`@eclipse-che/theia-terminal`](https://github.com/eclipse/che-theia/blob/4 …
=> Publish npm modules on each master build on CI

extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.tsx, extensions/eclipse-che-theia-about/src/browser/style/che-theia-about.css, extensions/eclipse-che-theia-plugin-ext/src/browser/che-devfile-main.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-view-toolbar.tsx, extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins-caching.css, extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins-notification.css, extensions/eclipse-che-theia-plugin-ext/src/browser/style/che-plugins.css, plugins/task-plugin/resources/preview-urls-view.css
It's a backport of https://github.com/eclipse/che-theia/pull/656 from 7.10 to 7.9.x
=> Update Che Theia CSS styling to respect the VS Code theming approach

dockerfiles/theia/Dockerfile
Fixes https://github.com/eclipse/che/issues/16084
Change-Id: I5110ae857e6849b8b8d0ecda67903b612ab59616
=> fix(git): Add correct permissions for shell scripts like git (#673)

extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts, yarn.lock
Align `RemoteTerminalWidget` object to upstream changes
Tested using `che-in-che` development:
https://github.com/eclipse/che/issues/16469
=> Align remote terminal object to upstream

devfiles/che-theia-all.devfile.yaml
Updates [che-theia-all.devfile.yaml](https://github.com/eclipse/che-theia/blob/9af2c68c0a4f0f638e2c030c40af398bb73af324/devfiles/che-theia-all.devfile.yaml#L51-L54) to use the existing Che Theia sources instead of cloning from GitHub when calling `che-theia: init`.
=> Update Devfile to use the existing Che Theia sources

extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts, yarn.lock
Support proxy in plugin service.
https://github.com/eclipse/che/issues/16482
N/A
N/A
=> Support proxy in plugin service

extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts, yarn.lock
Support proxy in plugin service.
Back port of https://github.com/eclipse/che-theia/pull/690
https://github.com/eclipse/che/issues/16482
N/A
N/A
=> Support proxy configuration in plugin service

extensions/eclipse-che-theia-activity-tracker/src/node/activity-tracker-service.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts, yarn.lock
It's a back-port of #686 from 7.11 to 7.9.x
=> Rework activity-tracker extension to respect Che with TLS (#686)

extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-content-reader.ts, extensions/eclipse-che-theia-plugin-remote/src/node/che-content-aware-utils.ts, extensions/eclipse-che-theia-plugin-remote/src/node/document-container-aware.ts, package.json, yarn.lock
adapt code to upstream changes
https://github.com/eclipse-theia/theia/pull/7506
Change-Id: I8a580fe99eb3bdb17e69e5eeacbd523b712eaa0b
=> fix(vscode-uri): Changes due to upstream changes of vscode-uri

.github/CODEOWNERS
Updates GitHub CODEOWNERS with the new team members.
=> Update CODEOWNERS with the new team members

generator/src/templates/assembly-package.mst, yarn.lock
Use Eclipse Che as product name (like in dialog box)
Also with https://github.com/eclipse-theia/theia/pull/7642 it will allow to use that name inside webviews, etc.
Fixes https://github.com/eclipse/che/issues/16677
Change-Id: I0881b1749e69502265d89b4048e92eea3bd48f92
=> feat(product): Add Eclipse Che as product name

dockerfiles/theia-dev/Dockerfile
Avoid to see 'There appears to be trouble with your network connection' messages in build logs.
Slowing builds.
Change-Id: I9466b92f0c5f46af3c4353cbb9527c40536ac7ba
=> feat(timeout): Increase default yarn timeout

extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts
Align terminal shortcuts with VSCode
none. Internal use...
=> Align shortcuts with VSCode.

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Change-Id: I328d1d977eb5ff95849358fb4403b3bb656c73aa
[base] Update from ubi8-minimal:8.1-409 to ubi8-minimal:8.2-267
Change-Id: I328d1d977eb5ff95849358fb4403b3bb656c73aa
=> [base] Update from ubi8-minimal:8.1-409 to ubi8-minimal:8.2-267

dockerfiles/theia/docker/alpine/runtime-install-dependencies.dockerfile, dockerfiles/theia/docker/ubi8/runtime-install-dependencies.dockerfile, plugins/ssh-plugin/src/ssh-plugin-backend.ts
cherry-pick [Support encrypted SSH private keys](https://github.com/eclipse/che-theia/pull/719)
=> Support encrypted SSH private keys

extensions/eclipse-che-theia-messaging/src/node/messaging/che-messaging-contribution.ts
Allows WebSocket connections from any of the known origins.
closes https://github.com/eclipse/che/issues/17047
=> Allow WebSocket connections from any of the known origins

plugins/task-plugin/package.json, plugins/task-plugin/src/machine/websocket.ts
Support proxy configuration for tasks related functionality
=> Support proxy configuration for tasks related functionality

plugins/task-plugin/package.json, plugins/task-plugin/src/machine/websocket.ts
Support proxy configuration for tasks related functionality
=> Support proxy for tasks related functionality

plugins/workspace-plugin/src/askpass.ts, plugins/workspace-plugin/src/exec.ts
Fixes a problem with cloning project on proxy environment
https://github.com/eclipse/che/issues/17017
=> Fix problem with cloning project on proxy environment

.github/PULL_REQUEST_TEMPLATE.md
You can choose stable or next release of che to test your PR
Fixes https://github.com/eclipse/che/issues/17360
Change-Id: I0bf13fbc1bb013177da90f4fcbf05b4f332b0ed2
=> chore(github): Update template with happy path channel selector

.github/workflows/pr.yml, cico_common.sh, dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile, dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile, dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/Dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/alpine/runtime-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-from.dockerfile, dockerfiles/theia/docker/alpine/build-result-from.dockerfile, dockerfiles/theia/docker/alpine/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile, generator/package.json, generator/tests/init-sources/assembly-example/package.json, package.json, plugins/ports-plugin/package.json, plugins/ssh-plugin/package.json, plugins/workspace-plugin/package.json, plugins/workspace-plugin/src/exec.ts, yarn.lock
Bump che-theia to nodejs 12
https://github.com/eclipse/che/issues/17441
Change-Id: I976de042d113dbeda26c7c8cf35ef0892e74e9e6
=> feat(nodejs-12): Bump che-theia to nodejs 12

.github/PULL_REQUEST_TEMPLATE.md
fix typo
N/A
Change-Id: Ifac233f772379fcd927c45b87d71de7af5fde5ad
=> chore(github): Fix typo of pr template

extensions/eclipse-che-theia-git-provisioner/package.json, extensions/eclipse-che-theia-user-preferences/package.json, generator/tests/init/root-folder/packages/core/package.json, package.json, yarn.lock
Fix CVE of dependencies
N/A
Change-Id: I59f234daed1ae35dd9429cf24681cc104b9dd7be
=> fix(cve): Fix cve issues

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
- Update from ubi8-minimal:8.2-267 to ubi8-minimal:8.2-345 
- Update from ubi8/nodejs-12:1-45 to ubi8/nodejs-12:1-52
Change-Id: I04e01b1ef59cf90c6c2dad32b483a757a8e03ce1
=> chore(base images): Update base images

generator/README.md
Fixes a tiny typo in README.md. Not serious.
None.
=> Fix typo in README.md.

generator/src/templates/theiaPlugins.json
Update git extension to 1.44.2
Depends on https://github.com/eclipse/che-theia/pull/823
https://github.com/eclipse/che/issues/16041
=> Update git extension to 1.44.2

extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
Fix plugin url for single-host mode
https://github.com/eclipse/che/issues/17749
=> Fix plugin url for single-host mode

generator/src/templates/assembly-package.mst
Set default theme and icon theme
https://github.com/eclipse/che/issues/17978
=> Set default theme and icon theme

make-release.sh
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
Fix the malformed JSON that occurs during the release
https://github.com/eclipse/che/issues/18078
=> Fix replacement of dependency version during release

extensions/eclipse-che-theia-remote-api/package.json
Fix of fix publishing the modules to npmjs.org
https://github.com/eclipse/che-theia/pull/879
Change-Id: Iabbf8a779b05549c88d9101824250efec58e7ace
=> fix(package): make package public to make it available at publish step

package.json, yarn.lock
Update jest library
It's because I've no percentage in html code coverage output for now.
N/A
Change-Id: Iabe1d2deae673f6a020288806ed776f4b7d3c365
=> feat(jest): Update jest components

extensions/eclipse-che-theia-plugin-ext/src/browser/che-github-main.ts, plugins/github-auth-plugin/src/github-auth-plugin.ts
invalid format in the files.
This is changes that I get after running yarn in che-theia
N/A
Change-Id: I8b83b9e2a849af66ddf00b580479db69ba64b19d
=> fix(formatting): Some files are updated after running yarn.

extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
This is a backport of https://github.com/eclipse/che-theia/pull/894 to 7.20.x
=> Add missing initialization of certificateService

extensions/eclipse-che-theia-plugin-remote/src/node/languages-container-aware.ts
Cherry picked version of #892
(cherry picked from commit c9c64c99f262ce7f5c1b9d7972260262b3a93528)
=> Fix definitions when overriding for containers

extensions/eclipse-che-theia-remote-api/src/node/che-server-certificate-service-impl.ts
Fixes reading public certificates.
One more PR to fix https://github.com/eclipse/che/issues/18211 + [CRW#1300](https://issues.redhat.com/browse/CRW-1300)
In addition to the previous one - https://github.com/eclipse/che-theia/pull/894
=> Fix reading public certificates

generator/src/templates/theiaPlugins.json, plugins/github-auth-plugin/src/github-auth-plugin.ts
This reverts commit 666e14a802561273619b2726af54b961713dd22a.
Revert "Add vscode github built-in plugin as a default plugin"
This commit causes a bug: https://github.com/eclipse/che/issues/18227
=> Revert "Add vscode github built-in plugin as a default plugin"

generator/src/templates/theiaPlugins.json
Includes [VS Code Solarized-light](https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Solarized-light) Theme
The extension page on Open VSX Registry https://open-vsx.org/extension/vscode/theme-solarized-light
No issue
=> Add Solarized-light VS Code theme

extensions/eclipse-che-theia-remote-api/package.json, yarn.lock
Update `eclipse-che/workspace-client` version to get the changes https://github.com/eclipse/che-workspace-client/pull/44
https://github.com/eclipse/che/issues/18278
There was a problem related to starting IDE, please see https://github.com/eclipse/che/issues/18255
The `latest` version should bring the changes https://github.com/eclipse/che-workspace-client/pull/44 and there should be no problem with starting IDE.
=> Update 'eclipse-che/workspace-client' version

extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.tsx
Adds `rel='noopener noreferrer'` to <a> alements.
This will reduce some risks by tabnabbing attacks.
None
Open the "about" dialog.
=> Add `rel='noopener noreferrer'` to <a> alements.

plugins/ports-plugin/tests/devfile-handler/devfile-handler-che-server-impl.spec.ts
Use empty env to be sure existing env variables will not affect the test
-->it will likely fail on hosted che development
N/A
hosted che development (by not using my workspace on che.openshift.io which had the right workspace names)
Test should work whatever the running environment is.
Use hosted che mode or add other env variables with JWT_PROXY
=> fix(tests): Always start from a fresh environment without any existing variables

dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-from.dockerfile, dockerfiles/theia/docker/alpine/build-result-from.dockerfile, dockerfiles/theia/docker/alpine/runtime-from.dockerfile
Update nodejs to a more recent version : 12.20.0
N/A
Change-Id: Ie9e472e30bfeb03c5cd3eb91247fbabf8793d232
N/A
=> feat(nodejs): Bump to a newer nodejs version: 12.20.0

yarn.lock
Fix CVE-2020-7789
CVE-2020-7789
It should work as before, only minor .z semver dependencies are updated
Change-Id: I2cfe3093cff9538785c1da7539fae164b5ec11f7
=> chore(deps): Update dependencies and it should also fix CVE of node-notifier CVE-2020-7789

plugins/workspace-plugin/src/ca-cert.ts, plugins/workspace-plugin/src/theia-commands.ts
Backport PR https://github.com/eclipse/che-theia/pull/960 to 7.24.x
https://github.com/eclipse/che/issues/18654
Follow https://github.com/eclipse/che-theia/pull/960
=> [cherry-pick] Use CA bundle when cloning ZIP projects (#960)

.github/workflows/happy-path-tests.yaml
Allow to run Happy Path tests within a github action.
Allow to check both alpine and ubi8 images
N/A
Check PR check
=> Launch happy path tests inside github actions

.github/CODEOWNERS
Adds @sunix to the CODEOWNERS file for our team's area.
N/A
N/A
N/A
=> Add Sun to CODEOWNERS for che-theia plugins

extensions/eclipse-che-theia-plugin-ext/package.json, generator/package.json, generator/tests/init-sources/init-sources.spec.ts, plugins/ssh-plugin/package.json, yarn.lock
Upgrades `axios` to 0.21.1 to fix the known vulnerability.
fixes https://github.com/eclipse/che/issues/18916
=> Upgrade axios

README.md, cico_build_master.sh, cico_build_pr.sh, cico_build_release.sh
Disables obsolete cico jobs that were replaced by the corresponding GitHub Workflows.
=> Disable obsolete cico jobs

README.md
Update README.md with correct links
N/A
Fix https://github.com/eclipse/che/issues/18951
Preview the README.md
=> chore(README): update badges in README.md

.github/workflows/release.yml, make-release.sh
Add workflow for releasing che-theia on GitHub actions. Adapt make-release.sh script for this workflow
=> Add GitHub release workflow

extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-manager.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/plugin/che-plugin-service-client.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-plugin-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
* Refresh the `plugins` view when a new plugin registry is added in the `settings.json`.
* If the new plugin registry is not valid, show a notification about it.
https://issues.redhat.com/browse/CRW-1449
fixes https://github.com/eclipse/che/issues/17263
1. Open a workspace from devfile:
```
metadata:
name: testnjz3q
components:
reference: 'https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1002/che_theia_meta.yaml'
- id: github/vscode-pull-request-github/latest
```
2. Open `Plugins` view.
3. Open `settings.json` file in the `.theia` directory in the user folder.
4. add a new value to the `chePlugins.repositories` field e.g.
```
{
"chePlugins.repositories": { "test": "https://test.com" }
}
```
5. The …
=> Validate plugin registry in the settings.json

build.include
Update theia reference to b4270a3d
=> Update theia reference to b4270a3d

extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-backend-module.ts, extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devfile-service-impl.ts, extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-devworkspace-env-variables.ts, extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-workspace-service-impl.ts, extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-devfile-service-impl.spec.ts
remove circular dependency
Circular dependency
Should work in dev Workspace mode.
=> fix(circular-dependency): Remove warning about circular dependency workspaceService-->devFileService --> workspaceService

extensions/eclipse-che-theia-remote-api/package.json
Fixes publishing to npmjs within the workflow https://github.com/eclipse/che-theia/actions/workflows/build-publish-next.yml
=> Fix publishing to npmjs

devfiles/vscode-extensions.devfile.yaml
Fixes `che-theia-dev` image for vscode-extensions devfile
Try to start the workspace from vscode-extensions.devfile.yaml
=> Fix image in vscode-extensions devfile

.github/workflows/release.yml
move MM notification to a separate job step
Change-Id: I1c30760aa4886d16a18ba64aa10e0ca5cb7b7576
N/A
N/A
=> move MM notification to a separate job step so it's in its own container

plugins/github-auth-plugin/.gitignore, plugins/ssh-plugin/.gitignore, plugins/task-plugin/.gitignore, plugins/telemetry-plugin/.gitignore, plugins/welcome-plugin/.gitignore
This changes proposal updates .gitignore files in plugins and adds `coverage` directory to excluded directory lists.
N/A
fixes https://github.com/eclipse/che/issues/19130
During the build of che-theia you shouldn't see `coverage` directory in git index.
=> Update .gitignore files according to che#19130

extensions/eclipse-che-theia-plugin-ext/src/browser/che-openshift-main.ts, extensions/eclipse-che-theia-remote-api/src/browser/oauth-utils.ts
Revert https://github.com/eclipse/che-theia/pull/773. Since `che.openshift.io` has been shut down we don't need this any more.
fixes https://github.com/eclipse/che/issues/17951
=> Revert: Handle get token request for che.openshift.io

dockerfiles/theia-dev/docker/alpine/install-dependencies.dockerfile, dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile
Fixes https://github.com/eclipse/che/issues/19296
Signed-off-by: Aaqa Ishtyaq <aaqaishtyaq@gmail.com>
Add patch in `theia-dev` alpine image. 
https://github.com/eclipse/che/issues/19296
Add a patch in `dockerfiles/theia/src/patches/master` and try to build `theia` image, it will fail as there is no package called patch
=> add patch in theia-dev image

plugins/task-plugin/src/che-workspace-client.ts
Error message was confusing after converting task-plugin to devfile 2.0, here is an attempt to improve it.
https://github.com/eclipse/che-theia/pull/1024#discussion_r595935257
review error message
Change-Id: I5c884a3e1136d042c4ed47b1d3faf21a36613336
=> feat(task-plugin): Improve error message

extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, yarn.lock
Align TaskScope with upstream API
https://github.com/eclipse/che/issues/19338
Che tasks should work.
=> Align TaskScope with VS Code API

.github/workflows/happy-path-tests.yaml
Perform disk cleanup just before running happy path tests
on ubi8, last run fail with 'no space left on device'
Check if at least one happy path succeed on ubi8 (so it fixes the problem) and that happy path is still green on alpine as well :-)
Change-Id: I94c326f77c52b3c8abcbac38c4487836946b2222
=> feat(happy-path): Cleanup images to have more disk space

.github/workflows/happy-path-tests.yaml, .github/workflows/pr.yml
Do not trigger PR checks on push event
it will reduce by 2 the numbers of jobs as 80% of people are not using forks on che-theia
N/A
Check if PR checks are green
=> chore(workflows): Reduce the number of workflows as most of people are not using forks

package.json, yarn.lock
Update lerna to use ssri >= 8.0.1 dependency
It should fix https://github.com/eclipse/che-theia/security/dependabot/yarn.lock/ssri/open
check that all stuff where lerna is involved is working
Change-Id: I77247c0ac1ad10dbb2a8e3d46e068f07df558357
=> feat(lerna): Bump to lerna 4 to have a newer ssri dependency

.ci/publish-report.sh, .github/workflows/release.yml, CONTRIBUTING.md, README.md, RELEASE.md, che-theia-init-sources.yml, devfiles/che-theia-all.devfile.yaml, devfiles/hosted-che-dogfooding.devfile.yaml, devfiles/vscode-extensions.devfile.yaml, dockerfiles/theia/Dockerfile, dockerfiles/theia/README.md, extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.tsx, generator/README.md, generator/tests/init-sources/init-sources.spec.ts, plugins/ext-plugin/README.md, plugins/task-plugin/src/task/che-task-runner.ts, plugins/workspace-plugin/tests/projects.spec.ts, plugins/workspace-plugin/tests/theia-commands.spec.ts, tools/automation/README.md, tools/automation/package.json
Updates the references to the `eclipse` GitHub organization to `eclipse-che`.
https://github.com/eclipse/che/issues/19391
=> Update the references to the new GitHub organization

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Change-Id: Idaeaf4e1a8c9a209c1b4ab5470ea548c085af5a4
[base] Update from ubi8-minimal:8.3-201 to ubi8-minimal:8.3-291
Change-Id: Idaeaf4e1a8c9a209c1b4ab5470ea548c085af5a4
=> [base] Update from ubi8-minimal:8.3-201 to ubi8-minimal:8.3-291

README.md
Updates `Join the community` part in the README.md.
=> Update the community info

plugins/resource-monitor-plugin/tests/resource-monitor.spec.ts, plugins/workspace-plugin/tests/workspace-projects-manager.spec.ts, yarn.lock
For some reason after removing yarn.lock the build was failed. This PR provides a fix for tests which were failed and updates yarn.lock.
Try to build the project
=> Fix tests in plugins

extensions/eclipse-che-theia-remote-api/src/common/devfile-service.ts, yarn.lock
new DTO has been published at https://www.npmjs.com/package/@eclipse-che/api
and codebase is not compliant with this API
N/A
N/A
Just look at the build, it fixes the unknown type to the more specific type added by upstream Che API
Change-Id: Ib3520ee06a3a5300e236984245997da704729130
=> fix(dto): Fix type of preferences from DTO object

.github/workflows/happy-path-tests.yaml
Minikube 1.20.0 is working fine with Eclipse Che, we can use this version
N/A
Look at happy path tests run in github action
Change-Id: I9bda1f03033f8dac3074e0738414a165d50fd068
=> chore(tests): Use newer minikube 1.20.0 to run happy path tests

dockerfiles/theia-dev/Dockerfile, dockerfiles/theia-endpoint-runtime-binary/Dockerfile, dockerfiles/theia/Dockerfile
Change-Id:...
fix copyrights for dockerfiles
Change-Id: I73a0bd86e41925d92a005e9b357230b79c0c07cd
N/A
N/A
=> chore: fix copyrights for dockerfiles

tools/devworkspace-handler/package.json
Publish npm module
https://github.com/eclipse/che/issues/19230
run publish:next and you should see this module is added in the list of publication
Change-Id: I1ff83dc745eb52b4d2481e45ca282d3e63343a1e
=> chore(publish): Publish devworkspace-handler module on npmjs

plugins/recommendations-plugin/package.json, plugins/recommendations-plugin/src/find/find-file-extensions.ts, plugins/recommendations-plugin/src/plugin/recommendations-plugin.ts, plugins/recommendations-plugin/tests/find/find-file-extensions.spec.ts, plugins/recommendations-plugin/tsconfig.json
Bugs around finding files were fixed so we can delegate the search of files to theia API now
https://github.com/eclipse-che/che-theia/pull/1134
Some dependencies around this plug-in are not resolved
Open repositories and check it recommends some plug-ins (like java-plugin, python plug-in, etc)
Change-Id: Ie482fbc86c6faca8c74f53ec194a7d3f6672a793
=> feat(recommendations): delegate find to theia API

.github/workflows/happy-path-tests.yaml
Disables running the HappyPath GH Actions when no code is changed.
https://github.com/eclipse/che/issues/19850 (fixes partly)
=> Don't run Happy Path GH Workflow when the changes are not related

.github/workflows/pr-build.yml, .github/workflows/pr-lint.yml
https://github.com/eclipse/che/issues/19850
=> Split the GH Workflow to avoid running the build jobs when no code is changed

extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts, extensions/eclipse-che-theia-plugin-ext/src/browser/che-http-main.ts, extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts, extensions/eclipse-che-theia-plugin-ext/src/plugin/che-http.ts, extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts, extensions/eclipse-che-theia-remote-api/src/browser/che-remote-api-frontend-module.ts, extensions/eclipse-che-theia-remote-api/src/common/http-service.ts, extensions/eclipse-che-theia-remote-impl-che-server/package.json, extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-remote-impl-che-server-backend-module.ts, extensions/eclipse-che-theia-remote-impl-che-server/src/node/che-server-http-service-impl.ts, extensions/eclipse-che-theia-remote-impl-k8s/__mocks__/axios.ts, extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-backend-module.ts, extensions/eclipse-che-theia-remote-impl-k8s/src/node/k8s-http-service-impl.ts, extensions/eclipse-che-theia-remote-impl-k8s/tests/node/k8s-http-service-impl.spec.ts, yarn.lock
Provides http service allowing to fetch resources by having proxy being configured and certificate authority configured as well (in case of https resource)
https://issues.redhat.com/browse/CRW-1702
Use this service or look at tests on how it should fetch resources
There will be a follow-up with recommendation plug-in using this service
=> feat: introduce http service to fetch resources with proxy and certificate authorities for https configured

extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts, extensions/eclipse-che-theia-remote-impl-k8s/package.json, yarn.lock
After introducing a new http service to fetch resources, remove custom service using same logic but internally
https://github.com/eclipse-che/che-theia/pull/1140#discussion_r652652301
https://issues.redhat.com/browse/CRW-1702
Try to look at plug-ins view, it should be displayed as before
Change-Id: I0e2a817586f036e9ca658d75f6de82273c5f04dc
=> feat(plugins): use common http service instead of private Axios instance

plugins/recommendations-plugin/src/strategy/featured-plugin-strategy.ts, plugins/recommendations-plugin/tests/strategy/featured-plugin-strategy.spec.ts
This is a backport of https://github.com/eclipse-che/che-theia/pull/1148 for 7.32.x branch
https://github.com/eclipse-che/che-theia/pull/1148
https://github.com/eclipse/che/issues/19883
Please follow https://github.com/eclipse/che/issues/19883 steps
Change-Id: I3c0ef5d37a855e5212d08f051f943fb5888b7a86
=> fix(recommendations-plugin): avoid duplicated plug-ins

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia-vsix-installer/docker/ubi8/from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Change-Id: I51b004407b136df5c9aa0aa4ff35889ab55e44bf
chore: Update base from ubi8-minimal:8.4-200 to ubi8-minimal:8.4-205
Change-Id: I51b004407b136df5c9aa0aa4ff35889ab55e44bf
=> chore: Update ubi8/minimal to 8.4-205 and ubi8/nodejs-12 to 1-90

dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile, dockerfiles/theia/docker/ubi8/runtime-install-dependencies.dockerfile
Signed-off-by: Kirk Crane <kcrane@redhat.com>
=> crw-1995: libsecret-devel required for keytar build on ppc64le and s390x

.github/workflows/release.yml
bump to latest mattermost/action-mattermost-notify@1.1.0 (1.0.2 is broken)
Change-Id: I2a0a81756d969787263a524e184efc0972919713
N/A
N/A
=> chore: bump to latest mattermost/action-mattermost-notify@1.1.0 (1.0.2 is broken)

plugins/ssh-plugin/src/util/util.ts
Code cleanup for async function.
No issue, please see https://github.com/eclipse-che/che-theia/pull/1171#pullrequestreview-711408094
I think - no compilation errors are enough.
=> chore: Code cleanup for async function

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia-vsix-installer/docker/ubi8/from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Change-Id: I4dad534da5d98825dce5603ce490f36f49bd90d9
=> chore: Update ubi8/minimal and ubi8/nodejs-12 images

CONTRIBUTING.md
Follow up https://github.com/eclipse-che/che-theia/pull/1178
che-theia-all.devfile is renamed to che-theia-dev.devfile but CONTRIBUTING.md still refers old path
=> chore: che-theia-all.devfile -> che-theia-dev.devfile

dockerfiles/theia-dev/docker/ubi8/install-dependencies.dockerfile, dockerfiles/theia/docker/ubi8/runtime-install-dependencies.dockerfile
chore: CRW-1995 fix s390x rpm URL; refactor yum logic to do only one install (not two) and remove ||true 
Change-Id: Ie263bee67847aded8f2399184d925854d96c3d2f
N/A
https://issues.redhat.com/browse/CRW-1995
N/A
=> chore: CRW-1995 fix s390x rpm URL; refactor yum logic to do only one install (not two) and remove `||true`

extensions/eclipse-che-theia-plugin-ext/src/browser/container-picker.ts, extensions/eclipse-che-theia-terminal/src/browser/contribution/terminal-quick-open.ts, extensions/eclipse-che-theia-workspace/src/browser/che-quick-open-workspace.ts
Updates our usages of some quick-input API to a new version.
https://github.com/eclipse/che/issues/20320
Run the che-theia as of this PR and use the "open workspace", "open recent workspace" and "open terminal in a specific container" commands.
=> fix: Adapt QuickInputItem#execute to new API

extensions/eclipse-che-theia-plugin-ext/package.json, extensions/eclipse-che-theia-plugin-ext/webpack.config.js, generator/package.json, generator/src/templates/assembly-package.mst.json, package.json, yarn.lock
* Updates the webpack build of the front-end che API to Webpack 5
* Add the necessary dependencies for building with Webpack 5 in a non-source linked case
https://github.com/eclipse/che/issues/20083
See the linked issue  for setup instructions. Build che-theia and run che-theia according to instructions.
=> fix(webpack): webpack 5 build

plugins/containers-plugin/src/containers-tree-data-provider.ts
Reverts https://github.com/eclipse-che/che-theia/pull/1138 as it was decided here https://github.com/eclipse/che/issues/19805#issuecomment-893487933
https://github.com/eclipse/che/issues/19805
https://github.com/eclipse/che/issues/19825
=> fix(tasks): revert temporary fixup of task reveal - che-theia/pull/1138

.github/PULL_REQUEST_TEMPLATE.md
Adds an item to GitHub Pull Request template to remind the contributor to pay attention to the PR for HappyPath tests.
=> chore: Add an item to GitHub Pull Request template to remind the contributor about the PR for HappyPath tests

dockerfiles/theia-vsix-installer/src/entrypoint.sh
The URL provided by dashboard is a public one and then we may not have right certificates to reach this URL anyway (like self-signed certificates)
So use the default internal link instead
https://issues.redhat.com/browse/CRW-2200
Starts che with devWorkspace + self-signed certificates + offline registry
Change-Id: I4c24c12d7077191c676e8b77109b52d745aa8889
=> fix: use internal service name instead of public URL if defined

generator/src/templates/assembly-package.mst.json
Adds the `process` package to the Che assembly dependencies. Needed for building with CDN enabled.
https://github.com/eclipse/che/issues/20390
You can't, it will hopefully fix the action that published che-theia:next
=> Add process package

.github/workflows/pr-build.yml
closes https://github.com/eclipse/che/issues/20391
=> Enable CDN support for PR build check

.github/workflows/check-theia-branch.yml, .github/workflows/next-build.yml
chore: since PR check working, enable travis for next-build and check-theia-branch
Change-Id: Ia838ca3eeefc16b05dfdb6c7e9b81d803a06137d
N/A
https://github.com/eclipse/che/issues/19688
N/A
=> chore: since PR check working, enable travis for next-build and check-theia-branch

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Change-Id: I3a58541a0d82f164f62e572b153e0fa7eeebfa5f
=> chore: Update from ubi8-minimal:8.4-208 to ubi8-minimal:8.4-210 + ubi8/nodejs-12:1-95 to ubi8/nodejs-12:1-98

CONTRIBUTING.md, README.md
=> chore: Fix typos in readme and contributing guides

.travis.yml, dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/alpine/builder-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/builder-from.dockerfile, dockerfiles/theia/docker/alpine/build-result-from.dockerfile, dockerfiles/theia/docker/alpine/runtime-from.dockerfile
CRW-1215 update to multiarch che-custom-nodejs-deasync:12.20.1 (includes x, z, p)
Change-Id: I166f161083b88a843a893d43a17247bc7dd8441d
N/A
N/A (or see commit messasge above for issue number)
N/A
=> chore: CRW-1215 update to multiarch node 12.20.1 (includes x, z, p)

.github/workflows/release.yml, make-release.sh
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>
- fix sending success notification on release fail
- fix CURL requests not returning anything
=> fix: Fix release workflow

plugins/containers-plugin/__mocks__/@eclipse-che/plugin.ts, plugins/containers-plugin/__mocks__/@theia/plugin.ts, plugins/containers-plugin/tests/containers-plugin.spec.ts, yarn.lock
Add tests for the Containers plugin.
https://github.com/eclipse/che/issues/19214
CI build must be successful.
=> fix: Add tests for the Containers plugin

make-release.sh
Provides several optimizations to the release script, before providing a couple of bugfixes.
Note, it's better to review the changes by separate commits. GitHub shows a lot of modified LoC while there was just one if-condition added in the second commit.
=> Several optimizations to the release script, before providing the bugfixes

yarn.lock
Update yarn.lock so that we're fetching latest telemetry client without forked moxios library
Fixes https://github.com/eclipse/che/issues/20716
Check that image is being built
Change-Id: Ie76e95009e3721411ae8abd4eae6863c41c1b4c8
=> chore: refresh dependencies

.github/workflows/happy-path-tests.yaml
Use a more recent minikube version for tests
N/A
Look at happy path tests tests
Change-Id: I91c0bce7109faaf3b6009ad1496de8780b2c2d32
=> chore: Use a newer minikube version

tools/devworkspace-handler/package.json, tools/devworkspace-handler/src/entrypoint.ts
Fixing `npx @eclipse-che/che-theia-devworkspace-handler` command that is failing
Fixes https://github.com/eclipse/che/issues/20780
try with a test package published on npmjs incorporating these changes
```
npx @tmpwip/ctdw@0.0.1-20211116
```
=> fix: Make devworkspace-handler library executable with npx

tools/devworkspace-handler/README.md
Contributes the minimal README file for DevWorkspace Handler to allow people know what is it for and how to use it.
related to https://github.com/eclipse/che/issues/20074
=> docs: Add minimal README file for DevWorkspace Handler

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia-endpoint-runtime-binary/docker/ubi8/runtime-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
Change-Id: I93c87d4f66f89f952a5f7d51585cf4e8f2943399
=> chore: Update from ubi8-minimal:8.4-212 to ubi8-minimal:8.5-204

tools/devworkspace-handler/package.json, tools/devworkspace-handler/tests/generate.spec.ts
Check we have 100% of tests
N/A
check github action : should be green
Change-Id: I72e1d02cf152b02a63b7619f8eca8b7a5cb08e3d
=> tests: ensure thresholds

dockerfiles/theia-dev/docker/ubi8/setup-yarn.dockerfile, dockerfiles/theia/docker/ubi8/runtime-setup-yarn.dockerfile
latest ubi8/nodejs-12:1-104 includes node 12.22.5 and yarn 1.22.17
Change-Id: I52d74b6f782f76cd9413cb346b4716bed021872b
N/A
N/A
=> chore: update to latest yarn 1.22.17

package.json, yarn.lock
fix: pin to the same lerna version in devDeps as in resolutions, so we can use package.json for offline brew builds; also update yarn.lock to remove some of the errors
Change-Id: I3b6b72893ff3396d871f3a630831fa01e52882bf
N/A
https://issues.redhat.com/browse/CRW-2600
Followup tio https://github.com/eclipse-che/che-theia/commit/86effe8bbe572dcd076641d65fdc91f748c668bd
Before this PR:
```
$ yarn check
yarn check v1.22.5
warning Lockfile has incorrect entry for "lerna@^4.0.0". Ignoring it.
...
error Found 2791 errors.
```
After this PR:
```
$ yarn check
...
info Found 28 warnings.
error Found 181 errors.
```
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its …
=> fix: pin to the same lerna version in devDeps as in resolutions, so we can use package.json for offline brew builds

.github/CODEOWNERS
Updates the `CODEOWNERS` file to reflect the latest org changes.
=> Update the `CODEOWNERS` file

dockerfiles/theia/Dockerfile
=> Ovewrite the upstream lerna 4 dep to 2.2.0

package.json
Removes redundant `lerna` resolution.
=> Remove redundant `lerna` resolution

dockerfiles/theia/Dockerfile
Overwrites the upstream lerna 4.0.0 dep to 2.11.0.
=> Overwrite the upstream lerna 4 dep to 2.11.0

dockerfiles/theia/Dockerfile, package.json, yarn.lock
apply downstream transforms to dockerfiles/theia/Dockerfile, package.json and yarn.lock to pin node-addon-api@3.1.0 and keytar@7.6.0 (CRW-2656)
Change-Id: I9f2809af66416f3871842d33934a2fa36078ca4a
N/A
N/A
=> fix: apply downstream transforms to dockerfiles/theia/Dockerfile, package.json and yarn.lock to pin node-addon-api@3.1.0 and keytar@7.6.0 (CRW-2656)

extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts
Fix a bug when no event is fired when theia user preferences file `settings.json` is changed.
https://github.com/eclipse/che/issues/20622
1. Setup `git.user.name` and `git.user.email` in the `settings.json` file or via preferences view.
2. Check the `/home/theia/.gitconfig` file and see the setting present.
=> fix: Filre user preferences changed event

yarn.lock
It's code clean up after merging https://github.com/eclipse-che/che-theia/pull/1308.
I tried to build `che-theia` from scratch - so, clone the repo, then yarn build.
As result I have got these changes for yarn.lock file.
N/A
N/A
1. Clone che-theia 
2. build it using yarn
3. check that there are no changes for yarn.lock file
=> chore: Update dependencies related to keytar in yarn.lock file

.github/CODEOWNERS
Adds Roman and Vlad as the `Default Owners` (for the root-based files).
=> chore: Add Roman and Vlad as the `Default Owners` (for the root-based files)

dockerfiles/theia-dev/docker/ubi8/builder-image-from.dockerfile, dockerfiles/theia/docker/ubi8/build-result-from.dockerfile, dockerfiles/theia/docker/ubi8/runtime-from.dockerfile
update to latest node-14 base images
Change-Id: I6a4e821f4403920e9f35821696c8f652f9c9380e
N/A
N/A
=> chore: update to latest node-14 ubi8 images

generator/src/init.ts
It turned out that after a couple of last commits in 7.44.x branch, the build became broken.
This PR adds the missing code from the `main` branch to override the Node.js version in the root package.json and to fix the build.
=> Add the missing code from the `main` branch

extensions/eclipse-che-theia-plugin-ext/src/node/che-github-service.ts
Align to new git credentials file path
depends on https://github.com/eclipse-che/che-server/pull/292
https://github.com/eclipse/che/issues/21336
=> fix: Align to new git credentials file path

extensions/eclipse-che-theia-mini-browser/src/browser/che-mini-browser-environment.ts
Initializes `this._hostPattern` in `CheMiniBrowserEnvironment` `postConstruct()` to enable mini-browser.
Closes https://github.com/eclipse/che/issues/21510.
1. Create sample workspace.
2. Create `aaa.html` file.
3. Type `aaaaa`.
4. Click on Open Preview.
5. Tab with HTMP preview is opened to the right side.
=> fix: Initialize '_hostPattern' in mini-browser environment

.github/workflows/check-theia-branch.yml, .github/workflows/happy-path-tests.yaml, .github/workflows/next-build.yml, .github/workflows/pr-build.yml, .github/workflows/release.yml, extensions/eclipse-che-theia-logging/package.json, tools/automation/package.json, yarn.lock
chore: CRW-3162 update to moment 2.29.4 for CVE fix
Change-Id: Id6468f81410942d1e1883322964cadfa317fc91d
Signed-off-by: Nick Boldt <nickboldt@gmail.com>
N/A
N/A
=> chore: CRW-3162 update to moment 2.29.4 for CVE fix

.github/workflows/check-theia-branch.yml, .github/workflows/happy-path-tests.yaml, .github/workflows/next-build.yml, .github/workflows/pr-build.yml, .github/workflows/release.yml, extensions/eclipse-che-theia-logging/package.json, tools/automation/package.json, yarn.lock
chore: [CRW-3163](https://issues.redhat.com/browse/CRW-3163) update to moment 2.29.4 for CVE fix
Change-Id: Id6468f81410942d1e1883322964cadfa317fc91d
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
N/A
=> Draft: chore: CRW-3163 update to moment 2.29.4 for CVE fix

plugins/containers-plugin/src/containers-service.ts
Backports the patch from the mainstream  https://github.com/eclipse-che/che-theia/pull/1366
=> Filter the containers list in the Workspace panel (#1366)

.github/CODEOWNERS
remove benoitf as code owner
N/A
N/A
=> chore: remove benoitf as codeowner

extensions/eclipse-che-theia-remote-impl-che-server/package.json, make-release.sh, yarn.lock
Recently, the [breaking changes](https://github.com/eclipse-che/che-workspace-client/pull/95) were introduced in the [`@eclipse-che/workspace-client`](https://www.npmjs.com/package/@eclipse-che/workspace-client). Considering https://github.com/eclipse/che/issues/21771, we don't need these changes in Che-Theia. So, this PR pins `@eclipse-che/workspace-client` version to a particular one instead of `latest`.
https://github.com/eclipse/che/issues/21915
=> Pin `workspace-client` version
